### ISSUE TITLE
Exit 0 datacheck

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#1]
From rickmastfan67

Hey Jim, I just noticed that there isn't a mention for a version of the 'Exit 0' mention.

WV US-250 has a 'Exit #0' mentioned ( I-70(0A) ), but it isn't flagged like the I-70 tag was.  Maybe there should be something in your code that could flag any '(0)' or '(0x)' tag as well so it can be double checked too.

**Comment by yakra** [comment]
It now works, at least for (0) style labels.
tx.us085;I-10(0);;;EXIT0;
I don't see any (0A) style labels in datacheck.php to see whether it tags those examples.

Can this issue be closed?

**Comment by rickmastfan67** [comment]
Can't be closed yet.  Still isn't flagging my example as mentioned in the original post.

**Comment by jteresco** [comment]
We're getting these now, I believe.  Will leave this open for a day or two just in case I'm wrong.

**Comment by michihdeu** [comment]
I think this issue can be closed.

**Comment by jteresco** [comment]
We seem to be leaning toward eliminating the Exit 0 (and Exit 999) datachecks.  I'll leave this open until we do so (or not).
