### ISSUE TITLE
Colocated points

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#10]
Colocated points (waypoints at intersections, waypoints along concurrencies, border crossings) are detected in the python data processing script.  They should be added to the DB in a way so they're useful in mapping (for better labels) and in the HB (for intersecting route links).

**Comment by jteresco** [comment]
The graphs likely contain more information to help out here.

**Comment by yakra** [comment]
Intersecting route links are enabled now.
Are colocated points now in the DB?

**Comment by jteresco** [comment]
They're not.  Instead, they are detected as any other points with exactly the same coordinates right here:

https://github.com/TravelMapping/Web/blob/de7414554b81358df43a1b0af4a9255eed93ec19/lib/waypoints.js.php#L233

Which seems to indicate that this issue is now irrelevant.

**Comment by yakra** [comment]
> Which seems to indicate that this issue is now irrelevant.

Shall we close it?

**Comment by yakra** [comment]
Closing, as colocated points are now looked up in the DB via other means.
