### ISSUE TITLE
Table of system-level updates

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#11]
It would make sense to create a separate DB table and separate updates HTML table for changes to status of highway systems, as these should stand out above the route-level changes that populate most of our updates table.

**Comment by yakra** [comment]
Seconded.

**Comment by rickmastfan67** [comment]
Thirded.

**Comment by jteresco** [comment]
OK, good.  A first attempt at this is done and live in TM.  It still might make sense to add an HB link, but it wasn't completely trivial (need not to add links if a system is deleted, for example) and I need to get to (real) work...  So I'm going to leave the issue open for now.

**Comment by michihdeu** [comment]
Thanks. I'm not sure that it's good to have both update lists on one page only.

The more entries Highway the "Data System Status Changes" table will have the more difficult it will be to "find" the "Updates to Highway Data in Active Systems" table. Maybe there should be a link on the top "Goto Updates to Highway Data in Active Systems"!?

In addition, what do you want to display in the new "Highway Data System Status Changes" table? Only activation of new systems or do you want to add new devel systems and devel --> preview changes too?

I'd prefer the latter (but w/o details about the routes of non-active systems).

**Comment by jteresco** [comment]
I agree that down the road, these might be separate pages, or able to be selected on the same page.  I also think we'd want to be able to filter by date, region, system, and who knows what else, maybe even on highways we have in our own files.  But until the updates page becomes more integrated with the evolving new overall design, I don't think it's worth the time to separate out.

For the new table, I would like to see entries for every status change: new systems that are beginning development, systems upgraded from devel to preview, and systems upgraded from preview to active.  I'm open to other opinions on the matter, though.

I don't think we'd ever want to start creating updates entries for devel or preview systems.  We have those "lower" status levels specifically because we know we're making changes and that users should be aware that things could change without update.

**Comment by michihdeu** [comment]
Agree. Thanks.

**Comment by michihdeu** [comment]
The recently added "devel" systems are missing in the new table.

**Comment by yakra** [comment]
@michihdeu wrote:
>The recently added "devel" systems are missing in the new table.

Yes., that's right... Si's Super Fun System Explosion #343 comes to mind. Anything else?

@Jteresco write:
>For the new table, I would like to see entries for every status change: new systems that are beginning development, systems upgraded from devel to preview, and systems upgraded from preview to active. I'm open to other opinions on the matter, though.

What to do when usaky3 is activated, not as a discrete usaky3 set, but merged into the larger usaky proper? Thoughts?

Maybe something like a simple...
2021-01-19;(USA) Kentucky;usaky;Kentucky State Highways 1000-1499;active
that still fits within the existing systemupdates.csv framework?

**Comment by michihdeu** [comment]
@yakra, yep, especially Si's systems (but I'm not able to specify all because it was too much) should be added if we really want to handle the list according to @jteresco's proposal.

btw: The systemupdates.csv column headline is "StatusChange" which should/could be changed to "NewStatus". The php page column name is ok ("New Status").

**Comment by jteresco** [comment]
I've changed the column in the csv to "NewStatus" and we've started to use "merged" as a new status for systems like the usaky3 example that ends up being merged into an existing active system.

It does not seem that those starting new systems in "devel" status have been sending in entries for systemupdates.csv.  While I think I'd like to see them there so users and other developers have an easy way to know what's in progress, I am not concerned enough to press the issue.

I'll close this issue some time soon unless there's further discussion.

**Comment by michihdeu** [comment]
Agree but I'd still prefer having two separate pages for system updates and simple updates of active systems.

**Comment by jteresco** [comment]
I'm going to close this but I definitely think we will want to improve the updates page in many ways, including possibly separating out system updates onto their own page, and more importantly, being able to restrict the list by various things such as date ranges or by region or by system.
