### ISSUE TITLE
".gra format graph file"

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#114]
https://github.com/TravelMapping/DataProcessing/blob/5b718fedfb6c42fc3bb1102dcb91a28330fe095e/siteupdate/python-teresco/siteupdate.py#L608-L610
Should this now say `.tmg format graph file` instead?

**Comment by jteresco** [comment]
That method is no longer called.  The equivalent is now on line 1708, I believe.  I suppose dead code like that should be removed.  Please feel free!

**Comment by jteresco** [comment]
Also not useful anymore.  Snip away.
