### ISSUE TITLE
pointsinuse.log syntax

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#12]
This isn't a very big deal, but nonetheless...

I still use Tim's WPTEdit to edit my route files, and paste in CHM's *labelsinuse.php* listing into the *In-use Labels* box.
When adding in the data from *pointsinuse.log*, I first copy to a text editor, then find & replace to remove all the commas and single quotes, to put it into a format that WPTEdit can read.
This is very simple to do, but even so, listing the data in pointsinuse.log in the same format (separated only by spaces) would streamline the process a bit and make things more convenient.

**Comment by jteresco** [comment]
As long as no one is depending on the current format, I have no problem changing pointsinuse.log entries to match what's found on the CHM page.

A related question: how long do we continue to care about points in use in CHM .lists that are not yet moved over to TM?  As we continue to go forward with highway data fixes, updates, and expansion, lists on CHM are more and more stale, and I'd think someone who migrates over to TM now is already going to have some work to do...

**Comment by yakra** [comment]
True. I won't give any hard answer to the "How long to care?" question, and just leave it up the the preference of the individual collaborator working on a given route or region. For my part, I'll continue to consult the CHM lists for a while longer at least. Anything that avoids breaking a user's .list file and cuts down on the amount of work they have to worry about when migrating helps out, in aggregate.
The only real effect I could see from this is having some extraneous AltLabels in our WPTs, which really does no harm. Those can be left for if-and-when the old labels might be needed at a new location.

**Comment by jteresco** [comment]
I definitely have no problem with anyone keeping hidden alternate point names around.  They add almost no cost to the site update process and no cost to the operation of the site following an update.

**Comment by jteresco** [comment]
Any objection to me editing the lines to be something like:

    alb.a002 (8): SH8 VLO

I have a pretty strong preference for the file root over the list file name, but I'd be OK with leaving out the number in parens (total number of points) if its presence is problematic at all.

**Comment by yakra** [comment]
This syntax will work with WPTedit. Everything before the colon will be interpreted as part of the route name. Try it out. Thanks!

**Comment by jteresco** [comment]
OK, done.  See what you think.
