### ISSUE TITLE
nearmatchfps.log formatting

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#133]
```
DCERROR: chngs.g2012;['NX/GS', 'S201'];VISIBLE_DISTANCE;17.94
FPENTRY: chngs.g2012;NX/GS;S201;;VISIBLE_DISTANCE;18.61
REPLACEWITH: chngs.g2012;NX/GS;S201;;VISIBLE_DISTANCE;17.94
```
The `DCERROR` datum is redundant, just the same info as the `REPLACEWITH` datum formatted differently.
It makes sense to someone who's been digging into siteupdate.py & learning about Python, but is probably just extra noise for those used to seeing FP Entries formatted as they are on [datacheck.php](http://travelmapping.net/devel/datacheck.php).
I propose removing `DCERROR`.

The remaining info will be easier on the eyes if aligned a constant amount from the left.
Suggest `FPENTRY` -> `FP_ENTRY` and `REPLACEWITH` -> `CHANGETO`, yielding:
```
FP_ENTRY: chngs.g2012;NX/GS;S201;;VISIBLE_DISTANCE;18.61
CHANGETO: chngs.g2012;NX/GS;S201;;VISIBLE_DISTANCE;17.94
FP_ENTRY: chngs.g22;G70_E;G312_Luo;;VISIBLE_DISTANCE;16.72
CHANGETO: chngs.g22;G70_E;G312_Luo;;VISIBLE_DISTANCE;16.91
FP_ENTRY: chngs.g3011tua;G215;X280;;VISIBLE_DISTANCE;23.24
CHANGETO: chngs.g3011tua;G215;X280;;VISIBLE_DISTANCE;13.84
FP_ENTRY: chngs.g3017;X184;JinAir;;VISIBLE_DISTANCE;26.69
CHANGETO: chngs.g3017;X184;JinAir;;VISIBLE_DISTANCE;27.07
FP_ENTRY: chngs.g7011;SN/GS;Xia;;VISIBLE_DISTANCE;11.20
CHANGETO: chngs.g7011;SN/GS;Xia;;VISIBLE_DISTANCE;11.22
...
```

Since I've been getting my hands dirty with siteupdate.py a lot lately, I volunteer to make these changes if there's consensus it's a Good Thing.

**Comment by jteresco** [comment]
Go for it!

**Comment by michihdeu** [comment]
Cool, I finally understand what this log means! Yes, go for it!
