### ISSUE TITLE
multiple hwys, multiple Roots, single Route name; .log file errors

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#14]
Noticed an odd error showing up in the logs for a .list file I maintain.
It's in both http://tm.teresco.org/logs/harvey.log
and http://tm.teresco.org/devlogs/harvey.log
though I'm primarily concerned about the devlogs version for now.

Specifically,
> Waypoint label(s) not found in line: VA VA7 I-81 US340

Checking out [VA7 in the HB](http://tm.teresco.org/devel/hb.php?r=va.va007), I see that both are legitimate waypoint labels.

I suppose that I could download the .list and WPT files and look for nonstandard, non-ascii characters, however...
• The .list seems highly unlikely, as I edited it perfectly normally in MS Notepad and then pasted it into GitHub.
• The WPT seems unlikely as well, as it was successfully processed & appears in the HB perfectly normally.

Any insight as to what's going on?

**Comment by jteresco** [comment]
Don't have a chance to check at the moment, but it could be that we have some VA routes active in one of the grabbag systems, so omitted from usava for now.

**Comment by yakra** [comment]
Yes, that looks like the cause of the trouble. There's a collision in the route field:
**USANSF.CSV:**
usansf;VA;VA7;;;(Freeway);va.va007fwy;
**USAVA.CSV:**
usava;VA;VA7;;;;va.va007;

The list file appears to map to the USANSF version, which contains neither waypoint.

**Comment by jteresco** [comment]
Is this worth trying to resolve, or are efforts better spent trying to review usava so it can be activated?

**Comment by yakra** [comment]
The latter, I think.
Or, as a stopgap, pull a Texas: review and extend the USANSF routes, comment out their USAVA counterparts, and not feel pressured to rush on USAVA.

If this issue comes up again with any preview systems, we can decide then how to resolve it: via data processing, or by just eliminating the Route name conflict.

I suppose an alert during data processing, a notification of the Route name collision, could be useful to head off future occurrences, but I don't think it's of burning importance.

**Comment by jteresco** [comment]
I think our approach here should be as @yakra suggests and see if we can get a quick review of the usava routes that are also in usansf so the extended versions can become active while remaining usava peer review continues.
