### ISSUE TITLE
Route.line & ConnectedRoute.line

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#140]
https://github.com/TravelMapping/DataProcessing/blob/b8af79317d9ccdb21896b04da34c0a5e12b09658/siteupdate/python-teresco/siteupdate.py#L676
https://github.com/TravelMapping/DataProcessing/blob/b8af79317d9ccdb21896b04da34c0a5e12b09658/siteupdate/python-teresco/siteupdate.py#L804

I don't see these used anywhere else in the code. OK to get rid of them?

**Comment by jteresco** [comment]
Sure.  Easy enough to put back if they were ever needed again.
