### ISSUE TITLE
ConnectedRoute.mileage comment

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#142]
This comment dates to Jul 8, 2015, about 4 months before the active/preview/devel classification of systems was implemented.
https://github.com/TravelMapping/DataProcessing/blob/b8af79317d9ccdb21896b04da34c0a5e12b09658/siteupdate/python-teresco/siteupdate.py#L836
Should it now read `# will be computed for routes in active & preview systems later`?

**Comment by jteresco** [comment]
I believe it should.
