### ISSUE TITLE
Divide by zero errors when no preview systems

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#16]
Some parts of siteupdate.py assume at least one preview system or a divide by zero error occurs.  This is a reminder to look into this some time.  Low priority since we are likely to have preview systems for a long time to come.

**Comment by yakra** [comment]
It also assumes at least one active system.
Also a very low priority, because in the real world we have active systems now that in theory should remain active indefinitely.

**Comment by yakra** [comment]
With latest C++, apparently no longer an issue. No crashes.
