### ISSUE TITLE
"Update in Progess" message

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#17]
To try:

http://tm.teresco.org/forum/index.php?topic=293.msg1448#msg1448

**Comment by Thing342** [comment]
Maybe a backup copy of the database can be used while production is offline for updating? That seems like a simple way to reduce sever downtime.

**Comment by jteresco** [comment]
As a quick and easy improvement, there will now be a message displayed across the top of all pages while the DB is being updated during site update.  Not ideal and hopefully will be replaced with something like what @Thing342 mentions above or a similar "near 0 downtime" solution somewhere down the line.

**Comment by jteresco** [comment]
The localupdate process when we move the production site to the new server does the backup DB idea, so closing this issue.
