### ISSUE TITLE
Canonical route name replacement with itself?

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#170]
From user htm_duke with his latest email list submission:

> I've had the same error line pop up in my log file for months:
> 
> Note: deprecated route name US67BusAvr -> canonical name US67BusAvr in line TX US67BusAvr US67_S US67_N
> 
> I don't think this should be happening, given that the deprecated and canonical route names are the same, and I just wanted to point that out.

Something for me or maybe @yakra to check out when we have a chance.

**Comment by yakra** [comment]
goofy usausb.csv line:
`usausb;TX;US67;Bus;Avr;Alvarado, TX;tx.us067busalv;US67BusAvr`

**Comment by yakra** [comment]
I changed the root, but not the abbrev:
https://github.com/TravelMapping/HighwayData/commit/89910af99065e2b9d5160f6aa5faed71eb5be1ac
Will submit a fix.

**Comment by yakra** [comment]
https://github.com/TravelMapping/HighwayData/pull/2526

**Comment by jteresco** [comment]
Thanks - figured it had a better chance of being a data problem than a code problem.
