### ISSUE TITLE
Graph generation: save "release" versions

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#177]
The graphs generated by TM are used by the METAL project for educational purposes.  When students are using METAL, graph generation is normally suspended, so consistent results can be produced as students use the graphs in HDX and in their own programs.

It would be good to make periodic "release" versions of the graphs that would be guaranteed to stay around for some amount of time.  METAL users could point to specific releases and be assured that the graph data they're using will not change, while allowing TM to generate new graphs any time highway data changes significantly enough to justify it.

**Comment by yakra** [comment]
I don't have much skin in this game; if I need up-to-date graphs while generation is suspended, I can just run siteupdate.py to make them locally.

Would this require any changes on the DataProcessing / siteupdate.py end, or just a place on the web to store release versions while labs are ongoing?

**Comment by jteresco** [comment]
For automatic loading into HDX and for population of the list on the graph download page, the DB is used to find graph names, descriptions, and sizes.  I'd need a way to be able to save the DB information for each release and be able to specify it to the graph loading page and to HDX.

**Comment by michihdeu** [comment]
I second the idea. Creating own graphs, download them and load to HDX is annoying. I use HDX a lot, e.g. to check for concurrent routes before every change to active routes. It's just overloaded with markers you cannot hide. You need to zoom-in but that's damn slow due to the small step width. Well, I don't wanna complain, I just like the idea of keeping graphs up-to-date for TM hwy data managers 😃

**Comment by jteresco** [comment]
There is probably not a need even for monthly snapshots, just a few a year.  Saving too many snapshots seems like it could add unnecessary clutter with little added benefit.  I would want them to correspond to academic year cycles, one later in the summer, one near the end of the calendar year, and one late spring.  There seems to be no need to automate the process too much.  From the data processing side, this will be entirely independent of the site update process.  At snapshot time, it would take the current graph data and archive it, and save the DB information about the current graphs with a tag related to that snapshot so the graph data page (see https://github.com/TravelMapping/Web/issues/724) and HDX (see https://github.com/TravelMapping/EduTools/issues/418) could access it.

**Comment by jteresco** [comment]
Each graph archive set should end up in a GitHub repository.  This repository should have all of the graphs and the SQL that would add it to the DB table in the event that the entire table needed to be reconstructed.  The SQL would contain all of the graph information in #50.

**Comment by jteresco** [comment]
Two new DB tables are proposed: `graphArchives` and `graphArchiveSets`.   Each graph in `graphArchives` would refer to an entry in `graphArchiveSets` with information about the set's name, date, and `HighwayData` and `DataProcessing` versions that were used to generate that set.

Each graph in `graphArchives` would have the same information as the standard `graphs` table: `filename`, `descr`, `vertices`, `edges`, `travelers`,  `format`, and `category`, plus its set name and other stats about each graph that would be computed and stored as part of #50.

**Comment by yakra** [comment]
Should also record the `UserData` version for traveled graphs.

**Comment by jteresco** [comment]
The `TravelMappingTest` DB instance has the new tables, and `/fast/www/tm/grapharchives` has the actual graph archives being used for testing.  These are not yet integrated into any TM or METAL code, nor would their DB entries yet be preserved through our regular site update process.

I kind of like to keep the model where we clean out and repopulate the databases on each site update, so the `.sql` files to add entries to the new tables for each graph archive set will at some point need to be ingested as part of the site update process.  Fortunately, these will be tiny by comparison to the site update `.sql` file that gets imported into `TravelMapping` and `TravelMappingCopy` on each site update.

**Comment by jteresco** [comment]
Now live!
