### ISSUE TITLE
ClinchedSegmentEntry class

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#204]
Looks like the ClinchedSegmentEntry class doesn't do much of anything. They're just stored in TravelerList.list_entries, which itself is used only to add the `"Processed " + str(len(self.list_entries)) + " good lines marking " +str(len(self.clinched_segments)) + " segments traveled."` line to user log files.

Looking back at the siteupdate.py history, it didn't do more than this when first introduced either. (Whether, in the interim, some functionality was added and later removed, I didn't investigate.)

We can replace list_entries with an int used only during TravelerList construction, and write the log file that way. Losing the ClinchedSegmentEntry class will free up a small-moderate amount of RAM, simplify the code, and make things an imperceptibly tiny bit faster.

OK to snip this out?
Or, any good reason to keep it in? Any future functionality?

**Comment by jteresco** [comment]
I'm not sure if I had anything more elaborate in mind for it when it was introduced, but I agree that it has no useful purpose now and can go.

**Comment by yakra** [comment]
Once this is gone, there will no longer be any need for `canonical_waypoints` either.
