### ISSUE TITLE
graph edges in multiple regions

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#205]
https://github.com/TravelMapping/DataProcessing/blob/d49c2d4ab9dfbf8f25a607b20e2c4156e150d957/siteupdate/python-teresco/siteupdate.py#L1316-L1318
https://github.com/TravelMapping/DataProcessing/blob/8b2c5cdb996a29ec61d1855d1ed5453150eb2d33/siteupdate/cplusplus/classes/GraphGeneration/HGEdge.cpp#L34-L36

It may be a specialized and temporary case, but the in-progress split-up of France provides counterexamples to this assumption: An edge can be contained both in FRA and a new FRA-FOO subregion.

As a result, most but not all edges are included in the FRA-region graphs. Most of the new French subregion graphs have no edges; a few have 1, or 2 max.

**Comment by jteresco** [comment]
That kind of thing should not get into the production DB.  I need to make sure people can load disruptive changes like that into the test DB to avoid all the double-counting and things like the above.

**Comment by yakra** [comment]
Test DB... As opposed to the site at tmtest.teresco.org, ISTR a `db=travelmappingtest` option, or similar... You mean that?
I'm unsure about how to make that visible to the web front-end, but may be getting a bit ahead of myself.

As far as a fix for graph generation goes, we could just have a set of regions for each edge, as we do for vertices. A bit more RAM intensive, though.
This may be a low priority if we just accept that this situation is temporary, not likely to happen in the"real world", and can be avided in the future thru proper use of the test DB.

**Comment by jteresco** [comment]
Yes, the second DB which can be used with the production Web front end using the QS parameter.

I don't think we want to worry about this in general.  Hopefully the remaining France issues are soon to be cleared up, and I can get things set for the test TB before the next time a country is split into regions (assuming there are more that will be done).
