### ISSUE TITLE
allow tab as .list line delimiter

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#213]
https://github.com/TravelMapping/UserData/issues/2514

**Comment by jteresco** [comment]
I see no harm in allowing tabs.

**Comment by yakra** [comment]
**ToDo:** experiment with how Python splits fields in lines if separated by 2 or more delimiter characters (presently only spaces)

**Comment by yakra** [comment]
re.split. I get it. No need to experiment.
