### ISSUE TITLE
 localupdate.sh: defaults-group-suffix

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#235]
https://github.com/TravelMapping/DataProcessing/blob/b2f0fdb4e653fc4a10f113614a7040cc5d5089d7/siteupdate/python-teresco/localupdate.sh#L92
https://github.com/TravelMapping/DataProcessing/blob/b2f0fdb4e653fc4a10f113614a7040cc5d5089d7/siteupdate/python-teresco/localupdate.sh#L113

FWIW, I had to change the --defaults-group-suffix option from `tmapadmin` to `travmapadmin` to get localupdate.sh to work on my system.

**Comment by jteresco** [comment]
I think it's the way it is because in my `~/.my.cnf` file on noreaster I have the section where it stores the passwords in a section labeled `[clienttmapadmin]`.  @yakra can you change to match that on your system?

**Comment by jteresco** [comment]
I just realized this is related to the existing Web issue https://github.com/TravelMapping/Web/issues/305 about the documentation that sets all this up.
