### ISSUE TITLE
Timestamp in siteupdate.log

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#239]
`siteupdate.log` should get a timestamp so that one knows whether the file was generated with the latest or previous update.

Last nights update failed but `siteupdate.log` looks fine. I've [run data check](https://github.com/TravelMapping/HighwayData/pull/2951) and it also looks fine. If there had been a timestamp, I could directly see whether there was an issue with hwy or user data without running data check.

**Comment by jteresco** [comment]
It doesn't mean a timestamp in the log file would not be useful, but for now note that there's a date of last site update at the bottom of the TM home page, and there is a timestamp at the top of each of the other two log files linked in the same section as the siteupdate.log.

**Comment by yakra** [comment]
ToDo: add to C++ siteupdate
