### ISSUE TITLE
user log overall stats decimal places

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#240]
[On the forum](http://forum.travelmapping.net/index.php?topic=326.msg1682#msg1682), @michihdeu wrote:

> A little note: [Stats](http://tm.teresco.org/user/?u=michih) display 2 positions after decimal point but [log files](http://travelmapping.net/logs/users/michih.log) only 1 postition for %:
>
> Overall in active systems: 21444.42 of 601917.46 mi (3.**6**%)
> Overall in active+preview systems: 23430.16 of 795041.69 mi (2.**9**%)
>
> 21444.42/601917.46 mi (3.**56**%) Rank: TBD
> 23430.16/795041.69 mi (2.**95**%) Rank: TBD

Posting here in *DataProcessing* assuming a change of log files 1->2 places, rather than stats pages 2->1 places.

**Comment by michihdeu** [comment]
I've posted it two years ago.... 😮 but it's still annoying, thanks.

**Comment by jteresco** [comment]
Agree with the change to add a digit in the log rather than drop one on the web front end.  I'll take care of this while @yakra is deep in the web side.

**Comment by jteresco** [comment]
Fixed in both languages, tested in Python, but not C++.

**Comment by yakra** [comment]
Yay, our first C++ commit from another contributor! :+1:
Obviously something that doesn't need testing, but I tested it anyway; looks good.
Thanks for getting that.

**Comment by michihdeu** [comment]
@jteresco Log files have one digit again. Did anything go wrong with the files on the production server?

http://travelmapping.net/logs/users/michih.log
http://205.209.84.174/logs/users/michih.log

@yakra has not updated his mirror and it's still 2 digits there!

**Comment by jteresco** [comment]
Hmm, the site update program on the production server was last modified on July 11.  It looks like I never installed the fix at all.  Was it showing 2 digits at some point?

In any case, I just updated the site update program to the latest from GitHub, so we should be at 2 digits starting with the next run.

**Comment by michihdeu** [comment]
I'm not 100% sure that it was live on the production server. Maybe I've just seen it on the mirror? Or tmtest? Nevertheless, thanks for updating the production server now 😃

**Comment by jteresco** [comment]
Thanks for catching it.  I'm going to launch an update now.

**Comment by yakra** [comment]
I've not done much with my mirror in August. Sounds like it's good wrt this issue, but I'd still do well to remind myself of where its repos are at.
