### ISSUE TITLE
localupdate.sh fails if $datestr/$graphdir empty

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#245]
```
./localupdate.sh: creating zip archive of all graphs

zip error: Nothing to do! (graphs.zip)
```

**Comment by yakra** [comment]
siteupdate program aborts due to errors before building graph structure

**Comment by jteresco** [comment]
Maybe can address this as part of #551

**Comment by yakra** [comment]
[yakra](https://github.com/yakra) commented [on Jul 17, 2019](https://github.com/TravelMapping/DataProcessing/issues/245#issuecomment-512115137)
> siteupdate program aborts due to errors before building graph structure

Not sure when exactly this changed, but aborting due to ErrorList errors happens after graph generation now.
We should be all set. Only gotta watch out for crashes. ;)
