### ISSUE TITLE
LONG_UNDERSCORE datacheck

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#250]
Per [the manual](http://travelmapping.net/devel/manual/wayptlabels.php):
> Choose 3-letter suffixes for a nearby towns if they are fairly close. The 3-letter suffix should be the *first* 3 letters of the town name. Add a suffix with an underscore and those 3 letters.

3 letters, it's pretty clear. Not keeping 4-letter words as we would when truncating road names. Thus labels like
`ME US1 LinSt_SoPo MainSt_SoPo`
`ME ME11 PleSt_Milo`
`ME ME16 RivSt_Milo`
`ME ME77 SawSt_SoPo`
are out.

> If the town suffixes are not useful, are confusing, or require further elaboration (3+ junctions with same town), use the alphabetical suffixes instead. 

means labels like
`ME US1 ME161_CarA ME161_CarB ME161_CarC`
`ME ME161 US1_CarA US1_CarB US1_CarC`
are out.

These examples fall through the cracks because siteupdate only checks for suffixes of 5+ characters.
I propose also flagging 4-character suffixes not ending in `[NEWS]`.

**Comment by michihdeu** [comment]
> Not keeping 4-letter words as we would when truncating road names.

@si404 keeps 4-letter words though. Why should we go a different way for road names and "suffix" town names?

> I propose also flagging 4-character suffixes not ending in [code][NEWS][/code].

Sorry, I don't get it. What do you mean? Flagging the "Si-case" as data error?

**Comment by yakra** [comment]
> @si404 keeps 4-letter words though.

Lots of do many different things wrong, though. ;)

> Why should we go a different way for road names and "suffix" town names?

For road names, the road name itself is the descriptive part. US41, ME25Bus, MainSt, SealCoveRd... For a label with a suffix, there will already be a main descriptive part that it's *suffixed to* -- **NY9A**_Yon, **PondRd**_Alb... The suffix is just there for disambiguation.
Expand these simple suffixes out too far, and we start to get long clunky label names that go against the principle of brevity.

If there are no road names, we would also use town names, e.g.:

> The rule says:
`AbcRd_Yor` instead of `AbcRd_York`
If there is no road name it would be:
`York`
Odd!

On the flipside, imagine AbcRd in York Factory: `Abc_YorkFac`. Yecch!

I like to think of these as *abbreviations* -- going hand in hand with the city abbreviations, as used in system CSVs -- limited to 

>> I propose also flagging 4-character suffixes not ending in `[NEWS]`.
>
> Sorry, I don't get it. What do you mean?

Sorry, I wasn't too clear there. A bit of [Regular expression](https://en.wikipedia.org/wiki/Regular_expression)-speak; I've been doing a lot of [grep](https://linux.die.net/man/1/grep)ping lately. A suffix not ending with any of the characters within the brackets, i.e., ending with `N`, `E`, `W`, or `S`.

> Flagging the above mentioned case as data error?

Flagging as error all the examples I listed in the OP, yes.
`AbcRd_York` = flagged, because it doesn't end with [NEWS].
`AbcRd_YorN` = not flagged, because it does.
`AbcRd_Yorn` = flagged, because the check would be case sensitive.

**Comment by si404** [comment]
The vast majority of my 4 letter underscores are going to be NEWS ones.

**Comment by michihdeu** [comment]
Now I know what NEWS is, I like it 😄

**Comment by yakra** [comment]
The proposed datacheck change would end up flagging an estimated 147 new errors.
(Assuming everything would end with a letter; it's possible there are some labels ending in a numeral or parenthesis or underscore or something that I didn't find using grep. The actual datacheck would be more robust of course.)

Not bad at all considering the vast amount of data in the system.

**Some commands/scripts for noreaster or other Unix-like systems:**
To see the examples, to go the `hwy_data/` directory and enter:
```SH
for rg in `ls`; do grep -s '_...[A-DF-MO-RTUVXYZa-z] ' $rg/*/*.wpt; done
```
For the good [NEWS] examples:
```SH
for rg in `ls`; do grep -s '_...[NEWS] ' $rg/*/*.wpt; done
```
Here's a shell script to get counts per region:
```SH
echo -e 'region\tbad\tgood'
for rg in `ls`; do
  bad=`grep -s '_...[A-DF-MO-RTUVXYZa-z] ' $rg/*/*.wpt | wc -l`
  good=`grep -s '_...[NEWS] ' $rg/*/*.wpt | wc -l`
  if [ "$bad" != 0 ] || [ "$good" != 0 ]; then
    echo -e "$rg\t$bad\t$good"
  fi
done
```

To filter for a subset of regions, replace the \`ls\` with a space-separated list of regions, E.G.
```SH
for rg in CT KS MA ME NB NE NH NJ NS NY OK RI TX; do grep -s '_...[A-DF-MO-RTUVXYZa-z] ' $rg/*/*.wpt; done
```

**Comment by michihdeu** [comment]
@yakra please share the list of current "new errors" so that we can have a look at it whether we really wanna go this way. Maybe we would need more exceptions or whatever.

**Comment by michihdeu** [comment]
Just for fun: I bet that about 33 out of the 99 potential errors are in active systems I've reviewed 🤣

**Comment by yakra** [comment]
> @yakra please share the list of current "new errors" so that we can have a look at it whether we really wanna go this way. Maybe we would need more exceptions or whatever.

file | label
| - | - |
AL/usaal/al.al005.wpt | CR1_Bibb
AL/usaal/al.al134.wpt | CR55_Dale
ALB/alba/alb.a001.wpt | SH30_Reps
ALB/eure/alb.e851.wpt | SH30_Reps
AUS-WA/ausn/auswa.n001.wpt | ForRd_Fitz
AUT/autb/aut.b050.wpt | S31_EisM
CHN-AH/chng/chnah.g03.wpt | S103_Nihe
CHN-FJ/chng/chnfj.g1514.wpt | G104_Fuan
CHN-FJ/chng/chnfj.g76.wpt | G319_Hexi
CHN-FJ/chng/chnfj.g76.wpt | G319_Amao
CHN-GD/chng/chngd.g15.wpt | G325_Mata
CHN-GD/chng/chngd.g4511.wpt | S230_Dahu
CHN-GD/chng/chngd.g78.wpt | G206_Yuhu
CHN-GS/chng/chngs.g22.wpt | S202_Yima
CHN-GS/chng/chngs.g7011.wpt | S306_Tian
CHN-GS/chng/chngs.g75.wpt | G212_Wudu
CHN-GS/chng/chngs.g75.wpt | S206_Lute
CHN-GS/chng/chngs.g8513.wpt | S306_Tian
CHN-GX/asiahp/chngx.ah001.wpt | G324_Malu
CHN-GX/chng/chngx.g72.wpt | G322_Gujo
CHN-GX/chng/chngx.g75.wpt | G325_Nama
CHN-GX/chng/chngx.g75.wpt | G325_Nali
CHN-GX/chng/chngx.g80.wpt | G324_Malu
CHN-GZ/asiahp/chngz.ah003.wpt | G320_Puan
CHN-GZ/chng/chngz.g60.wpt | G320_Puan
CHN-HB/chng/chnhb.g42.wpt | S312_Wudu
CHN-HB/chng/chnhb.g50.wpt | G318_Yidu
CHN-HB/chng/chnhb.g70.wpt | G316_Anlu
CHN-HL/chng/chnhl.g11.wpt | G201_Jing
CHN-HL/chng/chnhl.g4512.wpt | G111_Laha
CHN-HL/chng/chnhl.g4512.wpt | G111_Keli
CHN-HN/chng/chnhn.g5513.wpt | S306_Cili
CHN-HN/chng/chnhn.g56.wpt | G319_Luxi
CHN-JL/asiah/chnjl.ah032.wpt | G302_Daan
CHN-JL/chng/chnjl.g12.wpt | G302_Daan
CHN-JS/chng/chnjs.g40.wpt | G328_Luhe
CHN-LN/chng/chnln.g11.wpt | G201_Xiao
CHN-LN/chng/chnln.g11.wpt | G201_Wulu
CHN-LN/chng/chnln.g16.wpt | S312_Ximu
CHN-NM/asiah/chnnm.ah006.wpt | G301_Bugt
CHN-NM/asiah/chnnm.ah006.wpt | G301_Hake
CHN-NM/asiah/chnnm.ah035.wpt | S205_Xila
CHN-NM/chng/chnnm.g06.wpt | G110_Qasq
CHN-NM/chng/chnnm.g07.wpt | G110_Qasq
CHN-NM/chng/chnnm.g10.wpt | G301_Bugt
CHN-NM/chng/chnnm.g10.wpt | G301_Hake
CHN-NM/chng/chnnm.g16.wpt | S205_Xila
CHN-QH/asiahp/chnqh.ah042.wpt | G109_Ledu
CHN-QH/chng/chnqh.g06.wpt | G109_Ledu
CHN-SC/chng/chnsc.g05.wpt | G108_Liqu
CHN-SC/chng/chnsc.g05.wpt | G108_Puba
CHN-SC/chng/chnsc.g76.wpt | G321_Quba
CHN-SD/chng/chnsd.g03.wpt | G104_Qufu
CHN-SN/chng/chnsn.g22.wpt | S201_Wazi
CHN-SN/chng/chnsn.g7011.wpt | G316_Puxi
CHN-SX/chng/chnsx.g05.wpt | G108_Wusu
CHN-SX/chng/chnsx.g55.wpt | G108_Dayu
CHN-SX/chng/chnsx.g55.wpt | G108_Wusu
CHN-SX/chng/chnsx.g55.wpt | G108_Yuci
CHN-XJ/asiah/chnxj.ah067.wpt | S221_Emin
CHN-XJ/chng/chnxj.g3014.wpt | G217_Wutu
CHN-XJ/chng/chnxj.g3015.wpt | S221_Emin
CHN-YN/asiahp/chnyn.ah014.wpt | G326_Yusa
CHN-YN/asiahp/chnyn.ah014.wpt | G320_Banq
CHN-YN/chng/chnyn.g56.wpt | G320_Banq
CHN-YN/chng/chnyn.g8011.wpt | G326_Yusa
CHN-YN/chng/chnyn.g80.wpt | G323_Boai
CHN-YN/chng/chnyn.g80.wpt | G323_Nasa
CHN-ZJ/chng/chnzj.g1512.wpt | S310_Yiwi
CHN-ZJ/chng/chnzj.g25lis.wpt | S328_Bihu
CT/usaus/ct.us005.wpt | CT15_EHar
FRA/fran/fra.n024.wpt | D724_Baud
FRA/fran/fra.n090.wpt | D990_Aime
FRA/fran/fra.n124.wpt | D924_Auch
FRA-ARA/franr/fraara.n090.wpt | D990_Aime
FRA-BRE/franr/frabre.n024.wpt | D724_Baud
FRA-OCC/franr/fraocc.n124.wpt | D924_Auch
GRC/eure/grc.e65.wpt | EO3_Vevi
GRC/eure/grc.e86.wpt | EO3_Vevi
GRC/grca/grc.a027flo.wpt | EO3_Vevi
GRC/grca/grc.a027flo.wpt | EO3_Niki
GRC/grceo/grc.eo003.wpt | A27_Vevi
GRC/grceo/grc.eo003.wpt | A27_Niki
IN/usain/in.in069.wpt | MainSt_MVer
IRL/eurtr/irl.waw.wpt | R239_Muff
IRL/irlr/irl.r238.wpt | R239_Muff
IRL/irlr/irl.r239.wpt | R238_Muff
IRN/asiah/irn.ah008.wpt | R49_Agha
IRN/irnf/irn.f001.wpt | R49_Agha
ISL/islth/isl.th085.wpt | *OldTH85_VopA
ISL/islth/isl.th085.wpt | *OldTH85_VopB
ISL/islth/isl.th085.wpt | OldTH85_VopC
ITA/itaa/ita.ra003.wpt | SR2_Mont
ITA/itaa/ita.ra003.wpt | SR2_Tava
ITA/itass/ita.ss016.wpt | SP3_Fano
ITA/itass/ita.ss690.wpt | SR82_Sora
JPN/jpne/jpn.e013mas.wpt | N13_Masu
JPN/jpne/jpn.e084.wpt | N1_Oiso
KS/usaks/ks.ks004.wpt | MainSt_Otis
MA/usaus/ma.us001.wpt | MA1A_SAtt
MA/usaus/ma.us001.wpt | MA1A_NAtt
MAR/marn/mar.n016.wpt | ToA7_MDig
ME/usame/me.me011.wpt | PleSt_Milo
ME/usame/me.me016.wpt | RivSt_Milo
ME/usame/me.me077.wpt | SawSt_SoPo
ME/usame/me.me161.wpt | US1_CarA
ME/usame/me.me161.wpt | US1_CarB
ME/usame/me.me161.wpt | US1_CarC
ME/usaus/me.us001.wpt | MainSt_SoPo
ME/usaus/me.us001.wpt | LinSt_SoPo
ME/usaus/me.us001.wpt | ME161_CarA
ME/usaus/me.us001.wpt | ME161_CarB
ME/usaus/me.us001.wpt | ME161_CarC
MI/usami/mi.mi183.wpt | 13_25Ln
MLT/mltt/mlt.t001.wpt | T8_Loga
MLT/mltt/mlt.t008.wpt | T1_Loga
MN/usaus/mn.us075.wpt | CR1_Kent
NE/usane/ne.ne092.wpt | US26_SBay
NE/usaus/ne.us026.wpt | NE92_SBay
NZL/nzlsh/nzl.sh008.wpt | ProRd_Cave
OK/usaok/ok.ok019.wpt | MainSt_Alex
ROU/eure/rou.e68.wpt | A1_Ilia
ROU/eure/rou.e81.wpt | A10_Aiud
ROU/roua/rou.a001sib.wpt | DN7_Ilia
ROU/roua/rou.a010.wpt | DN1_Aiud
ROU/roudn/rou.dn001.wpt | A10_Aiud
ROU/roudn/rou.dn007.wpt | A1_Ilia
SVK/eure/svk.e571.wpt | I16_Figa
SVK/eure/svk.e58.wpt | I16_Figa
SVK/svki/svk.i016.wpt | R2_Figa
TUN/tuna/tun.a004.wpt | RN8_Zana
TUN/tunrn/tun.rn008.wpt | A4_Zana
UT/usaut/ut.ut018.wpt | CenSt_Veyo
UT/usaut/ut.ut114.wpt | CenSt_Orem
VT/usaus/vt.us005.wpt | ChuSt_Bart
WI/usaus/wi.us063.wpt | CRE_WasA
WI/usaus/wi.us063.wpt | CRE_WasB
WI/usaus/wi.us063.wpt | CRE_WasC
WI/usawi/wi.wi013.wpt | CRC_AshA
WI/usawi/wi.wi013.wpt | CRC_AshB
WI/usawi/wi.wi013.wpt | CRC_AshC
WI/usawi/wi.wi054.wpt | CRH_JacA
WLS/gbna/wls.a0467.wpt | B4591_Cefn

Most of the examples in my regions have fixes committed to my branches, no pull requests just yet. I haven't fixed the US1/ME161 examples.

**Comment by michihdeu** [comment]
> AUT/autb/aut.b050.wpt | S31_EisM

M means _Mitte_ = Center. The real _Center_ is used quite often for motorway exit names all over Europe.

> WI/usawi/wi.wi013.wpt | CRC_AshA
> WI/usawi/wi.wi013.wpt | CRC_AshB
> WI/usawi/wi.wi013.wpt | CRC_AshC
> WI/usawi/wi.wi054.wpt | CRH_JacA

That's according to the rules, isn't it?

Nevertheless, I think we should not flag the ones where the fourth letter is a capital letter.

> Just for fun: I bet that about 33 out of the 99 potential errors are in active systems I've reviewed

I counted 8. Maybe I missed some but it's much less than expected.

**Comment by yakra** [comment]
> M means Mitte = Center. The real Center is used quite often for motorway exit names all over Europe.

In the context of using that as a direction letter, I'm hesitant because
http://travelmapping.net/devel/manual/wayptlabels.php
> Suffixes such as _W always refer to English direction words such as "west" and never to direction words in other languages, i.e., don't use _O for "oeste."

That aside, I'm not sure what you mean by "real *Center*"...

>> WI/usawi/wi.wi013.wpt | CRC_AshA
>> WI/usawi/wi.wi013.wpt | CRC_AshB
>> WI/usawi/wi.wi013.wpt | CRC_AshC
>> WI/usawi/wi.wi054.wpt | CRH_JacA
>
>That's according to the rules, isn't it?

As quoted in the OP,
> If the town suffixes are not useful, are confusing, or require further elaboration (3+ junctions with same town), use the alphabetical suffixes instead.

Again too, there are my labels like
`ME US1 ME161_CarA ME161_CarB ME161_CarC`
`ME ME161 US1_CarA US1_CarB US1_CarC`
which I've still not fixed yet.

Originally, ME161 followed what's now ME161BCar, for 1 intersection in Caribou & 2 in Fort Kent. I used _A _B _C labels.
Then, ME161 was relocated, for 3 intersections in Caribou. One or The _B or _C labels in Fort Kent were in use, and I didn't like the idea of _A _D _E _B _C labels out of order, so I did what I did.
(I'll note that there's precedent for _A _B _D _C out of order in [US7](192.168.2.7/hb/?r=ct.us007&lat=41.472155&lon=-73.408413&zoom=12) & [US202](192.168.2.7/hb/?r=ct.us202&lat=41.472155&lon=-73.408413&zoom=12).)
Now, these could (should?) be fixed. I just haven't had the stomach to yet.

That said...
> Nevertheless, I think we should not flag the ones where the fourth letter is a capital letter.

...I may just be in agreement here. Undecided. It does allow us a bit more versatility in choosing labels. (The recent cleanup of [NY9A](https://github.com/TravelMapping/HighwayData/commit/33a98beeb0a4852d6d345b979675d3f1b190d435#diff-8792f880bbbab9ff8fbd022c43a91061L49-L57) & [US9](https://github.com/TravelMapping/HighwayData/commit/33a98beeb0a4852d6d345b979675d3f1b190d435#diff-00c6cd7604bca247e2ef9b41fa4a6bc2L19-L24) was a doozy...) May be worth considering.

Not flagging the ones where the fourth letter is a capital letter does leave us a little more wiggle room if we decide to go that route in the future, and amend the manual. :)

**Comment by michihdeu** [comment]
> That aside, I'm not sure what you mean by "real Center"...

Exit "Center" = city center when we look at 
`5. Truncated junction name - for freeways/expressways with official destination-based named junctions`
we have to distinguish that too. For instance, there are often exits calles AbcTown-West, AbcTown-Center, Abc-Town-East et cetera. Or with urban district name, e.g. [Basel](
https://www.google.com/maps/place/Basel,+Schweiz/@47.5546466,7.5769503,14z/data=!4m5!3m4!1s0x479049c72769304f:0x361ceb70f36d8a90!8m2!3d47.5595986!4d7.5885761)-EuroAirport, Basel-St.Johann, Basel-Wettstein, Basel-Breite, Basel-Süd --> South, Basel-City, Basel-St.Jakob

When we keep option 5, we need to use capital letters for more than just NEWS - being the forth, third or second letter. I'm in favor to get rid of option 5 though.

And there should still be the option to mark it FP.

**Comment by yakra** [comment]
Those cases would just be a truncated name though... The same way we truncate road names. No underscore here, Ergo no suffix. These would not be picked up by the datacheck.

**Comment by michihdeu** [comment]
yep, my bad. Sorry.
