### ISSUE TITLE
waypoint simplification types: space -> underscore

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#262]
For the waypoint simplification actions performed in the `canonical_waypoint_name` function, changing the names written to waypointsimplification.log to use an underscore rather than a space...

with space | -> | with underscore
-- | -- | --
Straightforward concurrency: | -> | Straightforward_concurrency:
Straightforward intersection: | -> | Straightforward_intersection:
Exit/Intersection: | -> | Exit/Intersection:
3+ intersection: | -> | 3+_intersection:
Exit number: | -> | Exit_number:
Reversed border labels: | -> | Reversed_border_labels:
Keep failsafe: | -> | Keep_failsafe:

...would be more convenient when piping **diff**s to **cut**.

The 3 other actions, performed outside of `canonical_waypoint_name`, in the `HighwayGraph` constructor,
`Appended region:`
`Revert to simple:`
`Appended !:`
I think leaving the spaces in should be fine.

@jteresco, any objections?

**Comment by jteresco** [comment]
Sounds like a good idea to me, thanks.
