### ISSUE TITLE
Incorrect "Unprocessed wpt files" log (case sensitivity check)

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#27]
http://tm.teresco.org/logs/unprocessedwpts.log

`hwy_data/DEU/eursf/deu.L124.wpt
hwy_data/DEU/eursf/deu.L141n.wpt
hwy_data/DEU/eursf/deu.L232.wpt
hwy_data/DEU/eursf/deu.L260.wpt
hwy_data/DEU/eursf/deu.L3004.wpt
hwy_data/DEU/eursf/deu.L3005.wpt
hwy_data/DEU/eursf/deu.L3193.wpt
hwy_data/DEU/eursf/deu.L418.wpt
hwy_data/DEU/eursf/deu.L605.wpt
hwy_data/DEU/eursf/deu.L705.wpt`

All files with capital L are indicated as NOT processed but they are processed! It seems that there's a case sensitive check which is not required because it works.

eursf.csv uses "l" in wpt file name.

**Comment by jteresco** [comment]
It doesn't matter to me if they're capital or lowercase, but they do need to be consistent between the file names and the csv entries.  Yes, it will work sometimes (when I run a site update on my Mac, which is case preserving) but will also fail sometimes (when I run a site update on FreeBSD, which is fully case sensitive).

**Comment by michihdeu** [comment]
Ok, I'll change the file names.
