### ISSUE TITLE
hash tables for waypoint labels?

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#278]
https://github.com/TravelMapping/DataProcessing/issues/230#issuecomment-568206835 got me thinking... 

We already use a hash table for looking up region/highway combos.
How about a couple hash tables for each route, for looking up primary labels & AltLabels?

**Comment by yakra** [comment]
This, like #272, would also mean we're no longer counting `point_indices`, meaning no error in the user log when a duplicate label is used in a .list line, unless a solution to #275 is implemented.

**Comment by yakra** [comment]
Hash tables can be used in place of sets for the DUPLICATE_LABEL datacheck.
Conversion will be more straightforward in C++, where most datachecks have already been folded into the *Reading waypoints for all routes* process.

**Comment by yakra** [comment]
* [ ] clear `pri_label_hash` and `alt_label_hash` after .list processing to save RAM.

**Comment by yakra** [comment]
**C++ Progress:**
* No diffs in stats .csv files.
* User log diffs all make sense. All of them are the same basic idea as:
  ```diff
  dave1693.log:
  2d1
  < Waypoint label(s) not found in line: RI US1AltPro I-195(2) I-195(6)
  6c5
  < Processed 2577 good lines marking 27712 segments traveled.
  ---
  > Processed 2578 good lines marking 27712 segments traveled.
  ```
  `I-195(2)` and `I-195(6)` refer to the same waypoint due to the sequential -> mileage-based renumbering.
  * If we want, we can add a note to the .log file such as
    `Equivalent waypoint labels mark zero distance traveled in line: RI US1AltPro I-195(2) I-195(6)`
    and not count the line toward the total number of good lines.
* No diffs in nmp_merged .wpt files.
* No diffs in post-processed graphs.
* No diffs in main .log files, except...
* Old & new **pointsinuse.log** and **unusedaltlabels.log** differ.
  In a way that does not affect anybody's stats.
  The how-and-why should be pretty understandable. I see a `continue` that I should get rid of; I'll see where that takes me...

**Comment by yakra** [comment]
We're down to four labels that have left unusedaltlabels.log and entered pointsinuse.log:
* `VA US50 I-66(76)`
* `NC US17BusWlm MilCut`
* `RI RI1APro I-195(6)`
* `WI WI136 WI159`

All of these were used in .list lines paired with the same waypoint's primary label:
* `VA US50 I-66(76) VA/DC`
* `NC US17BusWlm MilCut US17_N`
* `RI US1AltPro I-195(2) I-195(6)`
* `WI WI123 CRDL WI159`

They correspond to `Waypoint label(s) not found in line:` errors as in the example in my last post; the AltLabels never got checked for usage:

```py
for w in r.point_list:                                             #
    upper_label = w.label.lstrip("+*").upper()                     #
    if list_label_1 == upper_label or list_label_2 == upper_label: # Primary label matches either list_label_1 or list_label_2,
        point_indices.append(checking_index)                       # and IF block executes.
        r.labels_in_use.add(upper_label)                           #
    else:                                                          # Thus this never happens.
        for alt in w.alt_labels:                                   #
            if list_label_1 == alt or list_label_2 == alt:         #
                point_indices.append(checking_index)               #
                r.labels_in_use.add(alt)                           #
                r.unused_alt_labels.discard(alt)                   #
```

These labels are unused in the sense that they don't result in any clinched mileage for anybody. Removing them from the .wpt files would not harm anyone's stats. Thus I like the idea of doing as the existing code does, and counting them as unused. We can cut out the cruft, allow them to expire and re-enter the stream. :)

>  * If we want, we can add a note to the .log file such as
    `Equivalent waypoint labels mark zero distance traveled in line: RI US1AltPro I-195(2) I-195(6)`
    and not count the line toward the total number of good lines.

* This would provide a little forewarning if a user checks their .log before we get around to removing the label and slapping them with a `Waypoint label(s) not found in line` error.
* It's a cheap thing to do (in the rare cases it happens) while getting these AltLabels to remain flagged unused and slimming down the code.
* In the immediate term during development, it yields the most sane user log diffs.

**Comment by yakra** [comment]
> We're down to four labels that have left unusedaltlabels.log and entered pointsinuse.log:
...
All of these were used in .list lines paired with the same waypoint's **primary** label:

Ignoring all entries where both labels refer to the same waypoint cuts many more entries out of pointsinuse.log, ones where both labels are alternates, or both are the same primary.

We also de-list labels, both alternate & primary, found only in bona fide *Waypoint label(s) not found in line* cases.

*(A temporary patch to my WIP recreates the same output (user logs, pointsinuse.log, and unusedaltlabels.log) as the current master version. This is only for devel/debug purposes, not desirable for the end product.)*

Some [discussion of what should flag a label as in-use](http://forum.travelmapping.net/index.php?topic=3613) is in order...

**Comment by yakra** [comment]
Holy cow. This cuts .list processing time almost but not quite in half.
Python may -- ***may*** -- fare even better?

**Comment by jteresco** [comment]
I have got to be keeping a list of these to use to justify how great hash tables are when I cover them in classes..

**Comment by yakra** [comment]
The obligatory C++ speed graph:
![List3](https://user-images.githubusercontent.com/13720877/82132107-479e1b80-97aa-11ea-95bb-49b1e371156e.png)
Compare to:
[graph](https://user-images.githubusercontent.com/13720877/81012108-019a9c80-8e27-11ea-9f08-6e32a8b16b9f.png) from #320
[graph](https://user-images.githubusercontent.com/13720877/79997397-8977c280-8487-11ea-95d9-53175ef44c77.png) from #313

Note the ever-so-slight uptick in processing time at the end of lab3's graph.
This may, finally, be [strtok_mtx](https://github.com/TravelMapping/DataProcessing/issues/274) coming into play. We may be getting to the point where eliminating it could have a (barely?) noticeable effect.

**Comment by yakra** [comment]
> Holy cow. This cuts .list processing time almost but not quite in half.
Python may -- ***may*** -- fare even better?

Python does fare slightly better. On lab1, faster by a factor of 1.95, compared to a factor of 1.91 for single-threaded C++ on the same machine.
14.78s -> 7.52s.

**Comment by yakra** [comment]
**Squashed commits on BiggaTomato**
in case I ever want to refer back to them individually...

1. `265c35d13a6a14e66da1d6cee134a3a31c038427` (#308)
   strip .list comments before counting fields
2. `1a2932ad6db82301d5c3d061c7d7772aebc112cb` (#58)
   C++: refactor chopped route (4-field) list line parsing into its own file
3. `f6f72bfa3c9eb08cde28323e7f9b8af2a31e7d8b` (#278, #325)
   label hashes & DUPLICATE_LABELS datacheck
4. `89cffb2dacf80d863e4b6c1a8fd2a122cfa96adb` (#278)
   Py comment cleanup before hash-based .list proc
5. `c9028d6f2ea77bdc06eb9c48e6446ce09fa7087c` (#278, #326)
   hash-based .list processing
6. `c705341ef8425ab5febb8f3f3fca6a7f2ea2e415` (#274)
   C++: eliminate strtok_mtx
7. `0ce95bf2f7d7db138cb37b1494e65fd25f3f8f9b` (#230)
   refactor pointsinuse.log & unusedaltlabels.log
   to be written in the same loops.
8. `9043605efd6b2197aaa42cfe561142ac1170ec8b` (#278)
   more precise label_hash comments
9. `d76378549eae291dd3b79c5c2c28c30fa21561a9` (#230)
   separate pri_list_hash & alt_list_hash
10. `34640f71e9567fd7813ef8ab3e90db5b80a413f9` (#230)
    listnamesinuse.log & unusedaltroutenames.log
11. `512988888016b945589a9428752ee4e08b2dbd52` (https://github.com/TravelMapping/DataProcessing/issues/58#issuecomment-629957813)
    Route::store_traveled_segments
12. `f904d4bf406af54ac600cdea06feb0acab7ae99e` (#275)
    user log warning for DUPLICATE_LABELs
13. `25a33ce0b019dfdae943caae6358369fc1f86418` (https://github.com/TravelMapping/DataProcessing/issues/326#issuecomment-631662636)
    control chars -> '?' in log error msg labels
