### ISSUE TITLE
Sortable table of graphs

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#29]
Future enhancement: make the tables of graph data sortable by size as well as alphabetically.

**Comment by jteresco** [comment]
This should be easier now with the graph list in the DB.

**Comment by jteresco** [comment]
This is much less important with recent HDX improvements for finding graphs.

**Comment by yakra** [comment]
http://travelmapping.net/graphs/ can sort by # of Vertices or Edges, or alphabetically by Graph Description. Can we close this?

**Comment by jteresco** [comment]
I'd say yes.
