### ISSUE TITLE
check all CSV lines for correct # of fields

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#295]
to be addressed in tandem with #56 & #247

**Comment by yakra** [comment]
Hm really, I've never observed that. Do you have a GitHub or forum link?
If not, no big deal; I should add a blank line to the end of one of every type of CSV and see what happens anyway.

**Comment by jteresco** [comment]
It doesn't happen much now that most people run datacheck all the time, but it did last night.  Such an easy mistake to make and not notice.

**Comment by yakra** [comment]
I should be able to find what I need from https://github.com/TravelMapping/HighwayData/commit/ed7db58fd51997f50eb7633c40cfced384390095

**Comment by yakra** [comment]
The C++ version will treat this as a line with one (blank) field:
https://github.com/TravelMapping/DataProcessing/blob/f12c775a9b14b674ca35a8c818c9c397840233a8/siteupdate/cplusplus/classes/ConnectedRoute.cpp#L21-L25
I think Python should do the same, as there's no `;` at which to `split`.

It would be easy to toss these out as Not A Line.

**Comment by yakra** [comment]
### C++:
The `HighwaySystem` constructor has the same issue.
The `Region` constructor has been redone: after every call to `strtok`, we check to see if the returned pointer is valid; if not, we `el.add_error` noting the unexpected number of fields. The very first time `strtok` is called, it will return the same pointer passed to it, the start of the CSV line. Unless the line is completely blank. That's the only time we'd need to test for a valid pointer after the first call to `strtok`, and why do that when we can avoid calling the constructor altogether?
Let's ignore blank CSV lines.

**Comment by yakra** [comment]
`yakra@BiggaTomato:~/TravelMapping/HighwayData$ git checkout 143811e9447d411958ff9e7660bbac96f8276e83`

The old C++ version crashed at mexf *(Interesting; wasn't expecting that)*. The new version did not.

**Comment by yakra** [comment]
> The old C++ version crashed at mexf *(Interesting; wasn't expecting that)*.

Trying to follow the `system` pointer before it was assigned.

```C++
// system
size_t left = line.find(';');
if (left == std::string::npos)
{	el.add_error("Could not parse " + system->systemname
		   + "_con.csv line: [" + line + "], expected 5 fields, found 1");
	return;
}
system = sys;
```
Good thing I checked it out; this bug still affects the new version. Also the `Route` constructor.
I'll look for similar places this could happen.
