### ISSUE TITLE
PlaceRadius.place

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#297]
The word "place" WRT area graphs is ambiguous. It can refer to:
* the [place](https://github.com/TravelMapping/DataProcessing/blob/889af2dba73d471cfe68c5cc33f76d745a692f61/siteupdate/python-teresco/siteupdate.py#L1603) property of a `PlaceRadius` object, corresponding to the 1st column of [areagraphs.csv](https://github.com/TravelMapping/HighwayData/blob/7482ea9e55271c0fa5f67544de18761c115dd883/graphs/areagraphs.csv#L1).
* the 2nd column of [areagraphs.csv](https://github.com/TravelMapping/HighwayData/blob/7482ea9e55271c0fa5f67544de18761c115dd883/graphs/areagraphs.csv#L1), corresponding to the [base](https://github.com/TravelMapping/DataProcessing/blob/889af2dba73d471cfe68c5cc33f76d745a692f61/siteupdate/python-teresco/siteupdate.py#L1604) property of a `PlaceRadius` object.

I'd like to clarify, and change the `PlaceRadius` variable to `descr`, and the areagraphs.csv column to base. Any objections?

**Comment by jteresco** [comment]
Sounds fine to me.

**Comment by yakra** [comment]
Or on second thought, how about instead of `base`, using `title`?
* CSV headers will be consistent with multiregion.csv & multisystem.csv.
* Change `base` to `title` in the `PlaceRadius` class for consistency with the CSV

**Comment by yakra** [comment]
* [ ] change header row in areagraphs.csv
