### ISSUE TITLE
ABBREV_NO_CITY

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#303]
http://forum.travelmapping.net/index.php?topic=2138.msg18215#msg18215
> On second thought...
It's possible there could be some rare (but legitimate?) reasons we'd want to do this. Take [KS171Pit](http://travelmapping.net/hb/?r=ks.ks171pit). There used to be an ordinary KS171, but KDOT decommissioned it. It makes sense to remove the City field, as there's no other KS171 to differentiate from.
Could I & should I rename it KS171 & make KS171Pit an AltLabel in this case. Yeah. But the point is...
Imagine that the original plain KS171 became an AltRouteName for another route, and that it remained [in-use](https://github.com/TravelMapping/DataProcessing/issues/230) in a .list file. KS171Pit would by necessity have to remain KS171Pit.
>
> It makes sense to have these not be a showstopper that terminates the siteupdate program. They could go into datacheck, with the route flagged as per normal, just with no waypoint labels listed, maybe with the system name .csv in the "Info" column to provide a little clarity.
If we really wanna get fancy with it, we could check for the corresponding abbrev-less route in [in-use AltRouteNames](https://github.com/TravelMapping/DataProcessing/issues/230), and if found, not flag the error. I think this could even be a `datacheck_always_error`.

**Comment by michihdeu** [comment]
yes, don't terminate the siteupdate but make it a data check error which might be marked FP.

**Comment by yakra** [comment]
I'm thinking check the AltRouteNames in use and find whether it *would* be an FP, and then potentially just not report it.

Can you think of any legitimate reason we'd want to allow this, other than as an AltRouteLabel?

**Comment by michihdeu** [comment]
You could check which exceptions we currently have. The cases which would be reported as potential data error.

I don't get why it should be important whether the AltRouteName is in use or not.

**Comment by yakra** [comment]
> You could check which exceptions we currently have. The cases which would be reported as potential data error.
```SQL
mysql> select * from routes where abbrev != '' and city = '';
Empty set (0.09 sec)
```

> I don't get why it should be important whether the AltRouteName is in use or not.

If there was another plain `KS KS171` as an AltRouteName for some other route, it would prevent our current `KS KS171Pit` from becoming the new plain `KS KS171`, to avoid breaking .list files.

Let's say we have `usaks;KS;KS171;;Pit;;ks.ks171;` triggering a datacheck. It should become either:
• `usaks;KS;KS171;;;;ks.ks171;`, or
• `usaks;KS;KS171;;Pit;Pittsburg;ks.ks171;`. But which?

So we search our routes for `KS KS171`. First, does it exist as a primary .list name?
* If so, then this should have a `City` added. Flag a datacheck error.
* If not, then does `KS KS171` exist as an AltRouteName?
  * If not, then `KS KS171Pit` can become `KS KS171`. Flag a datacheck error.
  * If so, then is this AltRouteName in use?
    * If not, then `KS KS171Pit` can become `KS KS171`. Flag a datacheck error.
    * If so, then `KS KS171Pit` can't become `KS KS171`. Don't flag.

---
Perhaps rather than ABBREV_NO_CITY, this could be further broken down into MISSING_CITY (1st case above) and EXTRANEOUS_ABBREV (2nd & 3rd cases).

**Comment by michihdeu** [comment]
got it. we really don't need FPs this way.

OTOH, it will be the first(?) data error to routes instead of wps.

Where http://travelmapping.net/devel/datacheck.php indicates "waypoints" we would need the wpt file name

**Comment by yakra** [comment]
Seems like overkill,  as the `Route` column already provides that.
While dealing with the occasional label lookup failure is an [issue](https://github.com/TravelMapping/Web/issues/387) we're already dealing with, we should avoid adding more processing time by adding lookups for fake "labels" we know don't exist. OTOH, if there are no labels at all, we can easily bypass the lookup altogether.

What I do think would be useful is the chopped routes .csv name in the `Info` column, to give the data contributors a more clear idea of what's going on.

**Comment by michihdeu** [comment]
Sorry, the route column was just the "column with link" to me. Sure, you're right and the waypoint column could stay empty.

**Comment by yakra** [comment]
http://forum.travelmapping.net/index.php?topic=3554.msg18440#msg18440
> Oops, I failed to notice:
`Duplicate main list name in nv.nv430: 'NV NV430' already points to nv.us395altwas`
No harm now, though, as `NV NV430` isn't in use in any .list files, and usanv is processed after usaus thus the .list name points to the correct route.
However, [this will matter in the near future](https://github.com/TravelMapping/DataProcessing/issues/316), so we should remove the AltRouteName from usausb.csv.

**Comment by yakra** [comment]
Testing with some changes to cannst.csv:
>systemName;region;route;banner;abbrev;city;root;altRouteNames
cannst;NS;NS1;;;;ns.ns001;
cannst;NS;NS1;;Smi;Smiths Cove;ns.ns001smi;
cannst;NS;NS1;;Yar;Yarmouth;ns.ns001yar;
cannst;NS;NS2;;;;ns.ns002;
cannst;NS;NS3;;;Halifax;ns.ns003;
cannst;NS;NS3;;Liv;~*Liverpool*~;ns.ns003liv;
cannst;NS;NS3;;Loc;Lockeport;ns.ns003loc;
cannst;NS;NS3;;She;Shelburne;ns.ns003she;
cannst;NS;NS3;;Pub;Pubnico;ns.ns003pub;
cannst;NS;NS3;;Yar;Yarmouth;ns.ns003yar;
cannst;NS;NS4;;Wen;Wentworth;ns.ns004wen;
cannst;NS;NS4;;NGl;New Glasgow;ns.ns004ngl;
cannst;NS;NS4;;Ant;Antigonish;ns.ns004ant;
cannst;NS;NS4;;Hav;Havre Boucher;ns.ns004hav;
cannst;NS;NS4;;;Sydney;ns.ns004;
cannst;NS;NS6;;;;ns.ns006;
cannst;NS;NS7;;;;ns.ns007;**NS19**
cannst;NS;NS8;;;;ns.ns008;**NS28**
cannst;NS;NS10;;;;ns.ns010;
cannst;NS;NS12;;;;ns.ns012;
cannst;NS;NS14;;**Foo**;;ns.ns014;
cannst;NS;NS16;;;;ns.ns016;
cannst;NS;NS19;;**Bar**;;ns.ns019;
cannst;NS;NS22;;;;ns.ns022;
cannst;NS;NS28;;**Baz**;;ns.ns028;

and a new line in yakra.list in order to flag the `NS NS19` AltRouteName as in-use:
> NS NS19 NS2 BedByp

**Results are as expected**, but the approach can be simplified.
Adding some commentary to my [post](https://github.com/TravelMapping/DataProcessing/issues/303#issuecomment-611341196) above:
> So we search our routes for `KS KS171`. First, does it exist as a primary .list name?
> * If so, then this should have a `City` added. Flag a datacheck error.
> * If not, then does `KS KS171` exist as an AltRouteName?
>   **If not a primary name, either an alt name or not a name at all.**
>   * If not, then `KS KS171Pit` can become `KS KS171`. Flag a datacheck error.
>     **Not an alt name = not a .list name at all, therefore can not be in use**
>   * If so, then is this AltRouteName in use?
>     **Thus this is the only question we care about.**
>     * If not, then `KS KS171Pit` can become `KS KS171`. Flag a datacheck error.
>     * If so, then `KS KS171Pit` can't become `KS KS171`. Don't flag.

* Instead of checking whether the potential .list name is in `alt_list_hash` and then if it is, whether it's in the system's `unusedaltroutenames` set...
* We can check whether it's in the system's `listnamesinuse` set.
* Just do 1 lookup instead of potentially doing 2.
* `system->listnamesinuse` will be a smaller set than `alt_list_hash`. This may not help efficiency all that much\* depending on how sets work under the hood, but it certainly can't hurt.
  \**(These cases are already exceedingly rare. Nothing in the wild, so I had to make some up for testing purposes.)*
