### ISSUE TITLE
Time for an @yakra addition as another author on this

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#306]
https://github.com/TravelMapping/DataProcessing/blob/7253076524e54e49aff9ddf5ddffddab7d630226/siteupdate/python-teresco/siteupdate.py#L6

**Comment by yakra** [comment]
Oops, forgot one!
https://github.com/TravelMapping/DataProcessing/blob/7253076524e54e49aff9ddf5ddffddab7d630226/siteupdate/python-teresco/siteupdate.py#L2
