### ISSUE TITLE
Data check error "LABEL_SELFREF" not detected

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#318]
I had some cases where LABEL_SELFREF where not detected in FRA-IDF and FRA-GES.
I guess it's in combination to the usage of banners for the French D routes.

- Plain [D906](https://github.com/TravelMapping/HighwayData/blob/eee8bae7c84c9cf82ff71ab1c5366b71e830bef6/hwy_data/FRA-GES/fragesd54/frages.d090654.wpt#L3) was not detected.
- Plain [D112](https://github.com/TravelMapping/HighwayData/blob/86fa76d7e691288503590646894a9ff03429c3d6/hwy_data/FRA-IDF/fraidfd78/fraidf.d011278.wpt#L4) was not detected.
- Plain [D120](https://github.com/TravelMapping/HighwayData/blob/86fa76d7e691288503590646894a9ff03429c3d6/hwy_data/FRA-IDF/fraidfd78/fraidf.d012078.wpt#L2) was not detected.
- [D60](https://github.com/TravelMapping/HighwayData/blob/86fa76d7e691288503590646894a9ff03429c3d6/hwy_data/FRA-IDF/fraidfd77/fraidf.d006077.wpt#L2) was not detected in D60/D108_W and D60/D108_E.
- But [D33](https://github.com/TravelMapping/HighwayData/blob/c95561fdb7870117b5a76a6248977c8cca1c7153/hwy_data/FRA-GES/fragesd08/frages.d003308.wpt#L22) in D8/D33 **was detected!?**

**Comment by yakra** [comment]
> - Plain [D906](https://github.com/TravelMapping/HighwayData/blob/eee8bae7c84c9cf82ff71ab1c5366b71e830bef6/hwy_data/FRA-GES/fragesd54/frages.d090654.wpt#L3) was not detected.
> - Plain [D112](https://github.com/TravelMapping/HighwayData/blob/86fa76d7e691288503590646894a9ff03429c3d6/hwy_data/FRA-IDF/fraidfd78/fraidf.d011278.wpt#L4) was not detected.
> - Plain [D120](https://github.com/TravelMapping/HighwayData/blob/86fa76d7e691288503590646894a9ff03429c3d6/hwy_data/FRA-IDF/fraidfd78/fraidf.d012078.wpt#L2) was not detected.

https://github.com/TravelMapping/DataProcessing/blob/8c633d2dff6bb430bc79e4f84dd4cdbce986e3f5/siteupdate/python-teresco/siteupdate.py#L3676
These labels don't contain a `/`, so we skip over that section of code.

https://github.com/TravelMapping/DataProcessing/blob/8c633d2dff6bb430bc79e4f84dd4cdbce986e3f5/siteupdate/python-teresco/siteupdate.py#L3689-L3690
`selfref_found` is unchanged, still `False`. Thus the banner is required to match, and these non-banner "banners" of `-54` & `-78` are not found in the labels, so nothing else happens.

---
> - [D60](https://github.com/TravelMapping/HighwayData/blob/86fa76d7e691288503590646894a9ff03429c3d6/hwy_data/FRA-IDF/fraidfd77/fraidf.d006077.wpt#L2) was not detected in D60/D108_W and D60/D108_E.

This label contains a `/`, so we do enter into the first big `if` block, but all the checks therein only scan the label starting after the `/`, so `selfref_found` remains `False` and we proceed as before.

---
> - But [D33](https://github.com/TravelMapping/HighwayData/blob/c95561fdb7870117b5a76a6248977c8cca1c7153/hwy_data/FRA-GES/fragesd08/frages.d003308.wpt#L22) in D8/D33 **was detected!?**

Here, `D33` is after the slash.
https://github.com/TravelMapping/DataProcessing/blob/8c633d2dff6bb430bc79e4f84dd4cdbce986e3f5/siteupdate/python-teresco/siteupdate.py#L3682-L3683
And badabing!

---
Implementing a "fix" for this would require ignoring a route's banner field, which would mean breaking every case where a bannered route's point's label contains its unbannered parent.
...to which I emphatically say **Nope!** :)

**Comment by michihdeu** [comment]
Another issue: https://github.com/TravelMapping/HighwayData/pull/4501/commits/bf30f26de278eed412a5716420541d7d869c4c6c#diff-bc7f7e44dde3d183158d81d437001af7a109fa5fcf8cdbe995310fd95e066f3a

**Comment by michihdeu** [comment]
Plain M62 not detected: https://github.com/TravelMapping/HighwayData/pull/4578/commits/f755054aef3a40afd3b643fedc6a7e57c48c4cc2#diff-0a8d538a6f603f2449e76519bad9b0f327cf216581de3e4c75ed820b21c74ca9

**Comment by yakra** [comment]
> ...unless we added in some kind of FRA-specific workaround?
...
This makes me bristle a bit though; it just seems like a [kluge](http://www.catb.org/jargon/html/K/kluge.html)...

A bit more palatable: Ignore Banners beginning with `-`.
Right now, these are only used for French department numbers.
Would just have to ensure that any future uses of `-XX` banners are a similar "non-banner" usage.

---

Marked FP now:
`frahdf.d093962cam;D901/D939;;;LABEL_SELFREF;`
* Currently flagged because after-slash checks still ignore banners.
* Phase 1 gets rid of it: same route + same "banner"
