### ISSUE TITLE
"ignoring" list

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#322]
https://github.com/TravelMapping/DataProcessing/blob/8c633d2dff6bb430bc79e4f84dd4cdbce986e3f5/siteupdate/python-teresco/siteupdate.py#L2376
->
```py
ignoring.append(line)
```
(line has already been `strip`ped [above](https://github.com/TravelMapping/DataProcessing/blob/8c633d2dff6bb430bc79e4f84dd4cdbce986e3f5/siteupdate/python-teresco/siteupdate.py#L2372)

---
https://github.com/TravelMapping/DataProcessing/blob/8c633d2dff6bb430bc79e4f84dd4cdbce986e3f5/siteupdate/python-teresco/siteupdate.py#L2423-L2424
->
```py
    for line in ignoring:
        print("Ignored comment in " + args.systemsfile + ": " + line)
```

**Comment by jteresco** [comment]
I support ignoring obsolete issues about ignoring.
