### ISSUE TITLE
nmpbyregion log with FPs only

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#329]
http://travelmapping.net/logs/nmpbyregion/

It's pain in the ass to deal with a nmp file like fra-idf.nmp when there are more than 400 entries and most are FP.

I'm used to remove lines from the nmp file and reload it to HDX so that I know what I've already checked. Of course, I just want to check NMPs **not** yet marked FP.

Sure, nice to have but still. Thanks.

**Comment by yakra** [comment]
You can run
`grep -v 'FP$' inputfile.tmg > outputfilename`
on noreaster
or
`grep -v 'FP$' inputfile.tmg | less`

**Comment by yakra** [comment]
My answer wasn't quite right - I'd forgotten that lines that are both marked FP and look intentional are marked `FPLI` rather than `LIFP`.
The proper grep command would be:
`egrep -v 'FP$|FPLI$' inputfile.nmp`
`grep -v 'FP$\|FPLI$' inputfile.nmp`
...and you can still redirect output (`>`) or pipe to another program (`|`) as above of course.

**Comment by yakra** [comment]
Edited my above response to add "or" -- you can use one or the other of those commands; don't need both.

Here's what I did on noreaster, I created a file `nmp.sh` in my home directory:
```sh
for rg in ct ks ma me ne nh nj ny ok ri tx ab mb nb ns pe nl; do
  if [ `grep -v "FP$\|FPLI$" /home/www/tm/logs/nmpbyregion/$rg.nmp | wc -l` != '0' ]; then
    grep -v "FP$\|FPLI$" /home/www/tm/logs/nmpbyregion/$rg.nmp | less
  fi
done
```
* Use the regions you're interested in, all lower case, without dashes, as they would appear in the .nmp filename itself: `fraidf`, *not* `fra-idf` or `FRAIDF` or `FRA-IDF`.
* You can create it directly on noreaster -- `emacs nmp.sh` & then type or paste it in. `Ctrl+x` `Ctrl+s` to save, followed by `Ctrl+x` `Ctrl+c` to exit... emacs love its arcane keyboard commands; make sure you don't make any typos, or else welcome to the land of confusion.
* Or alternately, you can create it locally and then upload to noreaster. On Unix-like systems, I use `scp`; I'm unfamiliar with PuTTY and how it handles the file transfer process, so you're on your own there.

&nbsp;
* Run it using either `./nmp.sh` or `sh nmp.sh`.
* It will cycle through all regions in the list, and if there are any NMPs left over after filtering out the FPs, display them in `less`.
* If there are more entries than can fit onscreen at once, you can scroll using arrow keys or PageUp/PageDown/Home/End
* press `Q` to exit `less`.
* If there's no output at all, if it looks like nothing happens, that means all NMPs are marked FP.

**Comment by michihdeu** [comment]
Thanks and sorry, but it's fine. Fine. Issue was closed
