### ISSUE TITLE
NMP: FP still indicated as error [Bug/Question]

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#346]
https://github.com/TravelMapping/HighwayData/blob/master/nmpfps.log#L1056

`frahdf.a016cha HDF/IDF (49.164654,2.231284) NMP fraidf.d030195ron HDF/IDF (49.164841,2.231735)`

but https://travelmapping.net/logs/nearmisspoints.log says:

```
fraidf.a014 4 (48.895054,2.227821) NMP fraidf.d002392 BlvdAimeCes_N (48.89471,2.227596) [MARKED FP]
fraidf.a016cha HDF/IDF (49.164654,2.231284) NMP fraidf.d030195ron HDF/IDF (49.164841,2.231735)
fraidf.a086 +X36 (48.892289,2.181859) NMP fraidf.d098692 +X86 (48.892289,2.181858) [LOOKS INTENTIONAL] [MARKED FP]
```

A16Cha should have a `[MARKED FP]` suffix but it hasn't. I don't get why.

**Comment by michihdeu** [comment]
The HDF points are also marked FP. I'm stumped...

**Comment by yakra** [comment]
fra***h***df vs fra***i***df

**Comment by michihdeu** [comment]
Thanks 😃 I marked the **H**DF entries by accident. Added the **I**DF entries now.
