### ISSUE TITLE
Omit user log lines for untraveled systems

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#363]
Omit lines like `System deuthl (active) overall: 0.00 of 2446.71 mi (0.00%)` from user logs.

**Comment by jteresco** [comment]
I thought about this in the past, not sure why I decided to leave them in other than that it wasn't bothering me enough to remove them.

**Comment by michihdeu** [comment]
Seconded!

**Comment by yakra** [comment]
Maybe the reason (if there was one) could have been that the overall mileage of the systems is listed. Though for that, we have highwaydatastats,log. There was less noise originally, when TM started out with 113 systems; there are 407 today.

Shall I go ahead & give it the axe?

**Comment by michihdeu** [comment]
> Shall I go ahead & give it the axe?

yep!

**Comment by jteresco** [comment]
I say axe it.
