### ISSUE TITLE
Inline commenting on *.list files

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#37]
tm.teresco.org/forum/index.php?topic=1820

`IL I-90 WI/IL I-294  #NW Tollway` should be supported

**Comment by ssoworld** [comment]
Low priority - see forum for why.

**Comment by jteresco** [comment]
Now supported.  Valid comments are now full-line ones (whole line starts with '#') or lines with 4 fields followed by a space followed by one or more additional fields, the first of which (and 5th on the line) must start with '#'.
