### ISSUE TITLE
Region class

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#370]
C++ siteupdate has a region class, but siteupdate.py doesn't.
Might help organization to keep all this stuff under one roof.
Potential future datachecks may involve sets of banners / abbrevs used in each region.
dict | keys | values | in c++ as
| - | - | - | - |
HighwaySystem.mileage_by_region | Region | double | same
TravelerList.active_preview_mileage_by_region | Region | double | same
TravelerList.active_only_mileage_by_region | Region | double | same
TravelerList.system_region_mileages | HighwaySystem<br>systemname | dict<Region,double> | same
active_only_mileage_by_region | Region | double | double Region::active_only_mileage_by_region
active_preview_mileage_by_region | Region | double | double Region::active_preview_mileage_by_region
overall_mileage_by_region | Region | double | double Region::overall_mileage_by_region
HighwayGraph.rg_vset_hash | Region | set<HGVertex> | unordered_set<HGVertex*> Region::vertices
all_regions | region code | Region | region_hash

**Comment by jteresco** [comment]
Since Python will eventually be retired, we'll not bother with such a reorg.
