### ISSUE TITLE
Threaded C++ site update on FreeBSD

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#376]
When threading is enabled, compiling with g++ on noreaster, the following run-time error occurs:

<pre>
ld-elf.so.1: /usr/local/lib/gcc5/libstdc++.so.6: version GLIBCXX_3.4.22 required by /tm-tmpfs/travelmapping/DataProcessing/siteupdate/cplusplus/siteupdate not found
</pre>

**Comment by yakra** [comment]
I've just had a handful of successful runs on noreaster, testing out as many as 8 threads.
`HighwayData @ 27a625459516a8f5c53f73a24ce51416ab991677`
`UserData @ 3ec63996d33e499027a3d4c8f47abc0d3ce7659f`

**Some times for a few select tasks:**
task | 1 thread | 4 threads | 8 threads
-- | -- | -- | --
Searching for near-miss points | 2.9 | 0.7 | 0.4
Processing traveler list files | 13 | 3.5 | 2
Augmenting travelers for detected concurrent segments | 5.4 | 1.4 | 0.7
Computing stats per traveler | 6.7 | 1.8 | 1.6
Creating per-traveler stats logs and augmenting data structure | 28.3 | 8.5 | 6.7
total time @ ErrorList abort | 195.8 | 125.7 | 123.4

Things seemed to slow down a bit on the bits that require more disk access, such as *Reading waypoints for all routes* and *Writing near-miss point merged wpt files.* @jteresco, I can see why you got that SSD. :)

Subgraph generation took about 38s even when I wrote the files to /dev/null. What this tells me is that httpd, mysqld, student programs, and whatever else keep the system busy enough to not leave as much L3 cache & memory bandwidth for siteupdate.

**There's a catch, though.**
[A devilishly weird, obscure-but-reproducible little bug](https://github.com/TravelMapping/DataProcessing/issues/375#issuecomment-764962926).
More to come at #375...

**Comment by yakra** [comment]
#407 closes this. The threaded version will compile & run on noreaster.
**Other remaining issues:**
* [clang/FreeBSD-friendly makefile](https://github.com/TravelMapping/DataProcessing/issues/377)
* [Concurrent segment detection crashes](https://github.com/TravelMapping/DataProcessing/issues/405)
