### ISSUE TITLE
C++ build process

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#377]
I'd like to add a `Makefile` that can build the C++ site update program with appropriate compiler options based on the machine where it's running.

**Comment by yakra** [comment]
`Make` is another thing I never learned my way around. I've always perceived it as something unimaginably complex & arcane, and have vague memories of trying to compile LAME when I was new to Linux, and eventually throwing up my hands.
OTOH, last year I followed the directions on the internet and compiled python3 no problemo.

What kind of options would we be looking at?
* Something to manage or take the place of the current `#define` to enable/disable threading?
* Optimizations for the machine where it's running, e.g. SIMD support, etc? I've always assumed g++ by default will optimize what it can, and not looked too closely at its options.
* Or are we talking more basic stuff like `-pthread` `-std=c++11`?

**Comment by jteresco** [comment]
The `Makefile` basically just defines a bunch of rules for how to take some set of input files (source code), possibly through the creation/update of some intermediate files (object files), to get your output files (executables).

At its simplest, it would just define a single rule to run the one `g++` command.  Better, it would compile only what is needed in a separate compilation setup.  And, we could set it up to detect the system we're building on and run the right C++ compiler with the right flags.  And yes, I would have it so it either would always unconditionally build both a single- and multi-threaded version of the executable, or have a `make` command line parameter to build the one we wanted (something like `make THREADS=1`).

One technique I like is to have a `make` command-line parameter choose the appropriate `-D` flags to the compiler to essentially `#define` one or more things from the compiler line rather than having to edit code to change values.

In any case, I can add a simple one to get started that would really only mean instead of typing the whole `g++` line to compile, you would just type `make` (or on FreeBSD, probably `gmake` to run GNU Make).

**Comment by yakra** [comment]
>  Better, it would compile only what is needed in a separate compilation setup.

Sounds like what you mentioned in https://github.com/TravelMapping/DataProcessing/issues/378#issuecomment-743782361 (more to come there shortly): *"any changes to code would only result in recompilation of those files that have changed (or which include .h files that have changed)"*.

> I would have it so it either would always unconditionally build both a single- and multi-threaded version of the executable, or

Sounds like a Good Thing. Convenient, too. Sometimes I'm hacking away at the threaded version and forget to even compile the single-threaded version and make sure nothing is broken...

> One technique I like is to have a `make` command-line parameter choose the appropriate `-D` flags to the compiler to essentially `#define` one or more things from the compiler line rather than having to edit code to change values.

This does sound better. My current approach of having to edit the code (in the working tree, meh...) does feel a bit wrong.

**Comment by yakra** [comment]
Commented out the line in enable_threading.cpp, and ran `g++ -std=c++11 -pthread siteupdate.cpp -D threading_enabled -o siteupdate_foo`. No diff from my previous compile. Ran fine, multithreaded. AW YISS.
* [ ] How about I get the heck rid of enable_threading.cpp ASAP?
  You won't need any special commandline flags to compile on noreaster or systems similarly missing pthread.
  I can add `-D threading_enabled` to my g++ commandline and keep on truckin'.

**Comment by yakra** [comment]
I want to get moving on this. As I get going on #378, it'll be good to have `Makefile` existing as early in the chain of commits as possible.

**thoughts:**
* [ ] Get rid of enable_threading.cpp; use `g++ -D threading_enabled` instead.
* [ ] To begin, define a single rule to run the one (or two) `g++` command(s).
  Evolve as work progresses on #378, compiling what we can in a separate compilation setup as needed.
* [ ] Always unconditionally build both single- and multi-threaded versions, as noted above.
  * What to call'em... `siteupdate` and `siteupdateST`? `siteupdate` and `siteupdate_st`?
  * @jteresco [wrote](https://github.com/TravelMapping/DataProcessing/issues/378#issuecomment-743782361):
    > if you have different executables with different parameters compiled in, it would mean any object files that depend on those parameters would also need to be recompiled.

    Sounds like I want to compile separate ST & MT object files as needed depending on whether we `#define threading_enabled`. These different-flavored object files would be used to `make` the different-flavored executables.

**Comment by yakra** [comment]
How's this to start out?
```make
all : siteupdate siteupdateST

siteupdate : siteupdate.cpp */*.cpp */*/*.h */*/*.cpp */*/*/*.cpp
	g++ -std=c++11 -pthread -D threading_enabled -o siteupdate siteupdate.cpp

siteupdateST : siteupdate.cpp */*/*.h */*/*.cpp */*/*/*.cpp classes/*.cpp functions/*.cpp tasks/*.cpp
	g++ -std=c++11 -o siteupdateST siteupdate.cpp
```
Nice concise single-line rules for now, though things may start to change as the transitions for #378 get underway.

**Comments?**

**Comment by jteresco** [comment]
> How's this to start out?
> 
> ```makefile
> all : siteupdate siteupdateST
> 
> siteupdate : siteupdate.cpp */*.cpp */*/*.h */*/*.cpp */*/*/*.cpp
> 	g++ -std=c++11 -pthread -D threading_enabled -o siteupdate siteupdate.cpp
> 
> siteupdateST : siteupdate.cpp */*/*.h */*/*.cpp */*/*/*.cpp classes/*.cpp functions/*.cpp tasks/*.cpp
> 	g++ -std=c++11 -o siteupdateST siteupdate.cpp
> ```
> 
> Nice concise single-line rules for now, though things may start to change as the transitions for #378 get underway.
> 
> **Comments?**

Yes, that looks good.  One thing to keep in mind if you haven't discovered it yet, is that `make` is very picky about the dependencies after the `:` line be separated by a tab not spaces, and that the build rules are all indented with a tab, not spaces.

**Comment by yakra** [comment]
I *think* I have it right...
The lines with the `:` list my `targets : dependencies`, and contain only spaces, no tabs at all.
The two command lines (`g++ ...`) are indented with tabs, and are called recipes?

When you say "the build rules are all indented with a tab, not spaces", are you referring to just the *commands* that help me *build*? The recipes?

In any case, if "Yes, that looks good", I'll open a pull request.

**Comment by jteresco** [comment]
You'll want a tab after the `:` and before dependencies.  And yes, the build rules are your `g++` lines.

**Comment by jteresco** [comment]
I should clarify, a tab after the `:` on the target line, but the list of dependencies are space-separated.

**Comment by yakra** [comment]
Like this?
```make
foo :	bar baz
```

**Comment by yakra** [comment]
```sh
yakra@BiggaTomato:~/TravelMapping/yakra/DataProcessing/siteupdate/cplusplus$ git checkout Makefile
Switched to branch 'Makefile'
Your branch is up to date with 'origin/Makefile'.
yakra@BiggaTomato:~/TravelMapping/yakra/DataProcessing/siteupdate/cplusplus$ make
g++ -std=c++11 -pthread -D threading_enabled -o siteupdate siteupdate.cpp
g++ -std=c++11 -o siteupdateST siteupdate.cpp
yakra@BiggaTomato:~/TravelMapping/yakra/DataProcessing/siteupdate/cplusplus$ touch siteupdate.cpp 
yakra@BiggaTomato:~/TravelMapping/yakra/DataProcessing/siteupdate/cplusplus$ make
g++ -std=c++11 -pthread -D threading_enabled -o siteupdate siteupdate.cpp
g++ -std=c++11 -o siteupdateST siteupdate.cpp
yakra@BiggaTomato:~/TravelMapping/yakra/DataProcessing/siteupdate/cplusplus$ touch functions/split.cpp 
yakra@BiggaTomato:~/TravelMapping/yakra/DataProcessing/siteupdate/cplusplus$ make
g++ -std=c++11 -pthread -D threading_enabled -o siteupdate siteupdate.cpp
g++ -std=c++11 -o siteupdateST siteupdate.cpp
yakra@BiggaTomato:~/TravelMapping/yakra/DataProcessing/siteupdate/cplusplus$ touch classes/Waypoint/Waypoint.cpp
yakra@BiggaTomato:~/TravelMapping/yakra/DataProcessing/siteupdate/cplusplus$ make
g++ -std=c++11 -pthread -D threading_enabled -o siteupdate siteupdate.cpp
g++ -std=c++11 -o siteupdateST siteupdate.cpp
yakra@BiggaTomato:~/TravelMapping/yakra/DataProcessing/siteupdate/cplusplus$ 
```

Ubuntu working as expected

---

```sh
[yakra@noreaster ~/TravelMapping/DataProcessing/siteupdate/cplusplus]$ git checkout Makefile
Switched to branch 'Makefile'
Your branch is up to date with 'origin/Makefile'.
[yakra@noreaster ~/TravelMapping/DataProcessing/siteupdate/cplusplus]$ make
g++ -std=c++11 -pthread -D threading_enabled -o siteupdate siteupdate.cpp
g++ -std=c++11 -o siteupdateST siteupdate.cpp
[yakra@noreaster ~/TravelMapping/DataProcessing/siteupdate/cplusplus]$ touch siteupdate.cpp 
[yakra@noreaster ~/TravelMapping/DataProcessing/siteupdate/cplusplus]$ make
g++ -std=c++11 -pthread -D threading_enabled -o siteupdate siteupdate.cpp
g++ -std=c++11 -o siteupdateST siteupdate.cpp
[yakra@noreaster ~/TravelMapping/DataProcessing/siteupdate/cplusplus]$ touch functions/split.cpp
[yakra@noreaster ~/TravelMapping/DataProcessing/siteupdate/cplusplus]$ make
g++ -std=c++11 -o siteupdateST siteupdate.cpp
[yakra@noreaster ~/TravelMapping/DataProcessing/siteupdate/cplusplus]$ touch classes/Waypoint/Waypoint.cpp 
[yakra@noreaster ~/TravelMapping/DataProcessing/siteupdate/cplusplus]$ make
[yakra@noreaster ~/TravelMapping/DataProcessing/siteupdate/cplusplus]$ touch threads/ReadWptThread.cpp 
[yakra@noreaster ~/TravelMapping/DataProcessing/siteupdate/cplusplus]$ make
[yakra@noreaster ~/TravelMapping/DataProcessing/siteupdate/cplusplus]$ 
```
FreeBSD appears to not expand wildcards that are part of directory names. Just the filenames. :(

**Comment by jteresco** [comment]
Try with gmake.

**Comment by yakra** [comment]
Works as expected with gmake. Even with the space after the `:`, i.e. `siteupdate : siteupdate.cpp */*.cpp */*/*.h */*/*.cpp */*/*/*.cpp`
Are we fine, or should I still put the tabs in?

**Comment by jteresco** [comment]
Let's not worry about it, since it works.

**Comment by yakra** [comment]
OK. All the examples I've been seeing use spaces after the colon, so that struck me as odd.
http://matt.might.net/articles/intro-to-make/
https://www.oreilly.com/openbook/make3/book/ch02.pdf
https://www.gnu.org/software/make/manual/html_node/Rule-Example.html#Rule-Example
https://www.gnu.org/software/make/manual/html_node/Rule-Syntax.html#Rule-Syntax
Reopening the pull request.

**Comment by yakra** [comment]
@jteresco wrote in the OP:
> I'd like to add a `Makefile` that can build the C++ site update program **with appropriate compiler options based on the machine where it's running.**

@jteresco wrote at https://github.com/TravelMapping/DataProcessing/issues/378#issuecomment-748740052:
> Also, for the `Makefile`, I like to define variables like
> 
> <pre>
> CXX=g++
> CXXFLAGS=-std=c++11 -pthread
> </pre>
> 
> This would allow (for now) the ability to edit those in one place when switching platforms/compilers.  And later, it can be used with some **conditional checks to define compliers and flags automatically based on where `make` is run.**

* It might be time to start looking into this. With #407, siteupdate compiles & runs on noreaster now.
How do we do these conditional checks?
* OTOH, the clang compile *seemed* to run a little faster on my Linux boxes, though that could easily just be wishful thinking on my part. If clang performs comparably or faster, we could keep it simple and forget about g++, including only clang in the makefile.
* OT3H, Ubuntu & CentOS come with gcc out of the box, but not clang. Sure, installing it on both was blindingly easy, but who knows how other distros roll?

**Comment by yakra** [comment]
https://github.com/TravelMapping/DataProcessing/blob/f3fb26e50f831c65d45d6119972367873ac24b96/siteupdate/cplusplus/classes/Route/read_wpt.cpp#L1-L2
If either of these files are renamed or updated without updating Route.cpp, the dependencies of Route.o will not be updated.
* [ ] Best solution as I see it is to compile them separately. We're already most of the way there.
* [ ] Also need to look for other places this may happen.

**Comment by yakra** [comment]
> OTOH, the clang compile seemed to run a little faster on my Linux boxes, though that could easily just be wishful thinking on my part. If clang performs comparably or faster, we could keep it simple and forget about g++, including only clang in the makefile.

Single-threaded, the clang build runs faster than the g++ build on both Ubuntu & CentOS.
Multi-threaded, clang is consistently faster on Ubuntu, and comparable on CentOS, just about too close to call.
Going to keep it simple, forget about the conditional checks, and just use clang.

**Comment by yakra** [comment]
:+1:
