### ISSUE TITLE
C++ code organization for separate compilation

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#378]
Coming at this from my perspective as an experienced C programmer but someone whose last real C++ work was over 20 years ago, I am not sure this is an important issue.  However, the code organization with a single `.cpp` file that `#include`s everything else seems to be an unusual approach for a program of this size.

I am wondering if we should aim to reorganize some of the code to allow separate compilation and to eliminate `#include`s of `.cpp` files.  In C projects, I always organize code so that each `.c` file gets compiled to a `.o` file and only includes structure definitions, function prototypes, and `#define`s from any relevant `.h` files.  Then at the end, they're all linked to create the executable.

@yakra I'm not proposing any changes here yet, and certainly not asking you to make them, but would be interested in your thoughts as someone who's (obviously) done C++ coding decades more recently than I have.

**Comment by yakra** [comment]
I may have hacked C++ as recently as last night, but that doesn't mean I'm doing things right or following all best practices.
I'm mainly self-taught, never really got the hang of linking or any related stuff, and not being forced to learn it, just kept on doing what worked for me in the beginning -- one simple painless g++ command.

* What are the advantages to this approach?
* Could there be performance penalties relative to the "one giant executable" approach used now?
* One thing I like to do is keep several executables around and have a shell script automate several hundred passes through them. This is how I get performance data and see how things scale with different numbers of threads, and make the graphs included in some issues & pull requests. This is easy with a self-contained executable for each revision of the code, but would it still be feasible if we're relying on separate object files?

**Comment by jteresco** [comment]
You'd still have a single executable.  It's all in how it's compiled and linked.  However if you have different executables with different parameters compiled in, it would mean any object files that depend on those parameters would also need to be recompiled.

From a C programmer's perspective, one advantage to separate compilation of each C file comes in that you're guaranteed only a single version of each function and a single declaration of each global variable (if you have any) which might not happen if C files start to include each other.  In header files, you'd have only the function prototypes, which can be redefined as much as you want, and any global variable declaration would have `extern` in the header and only be declared "for real" in one C file.

Another thing that's nice, but not a big thing for a relatively small project like this in the era of fast compile times is that combined with a nice `Makefile`, any changes to code would only result in recompilation of those files that have changed (or which include `.h` files that have changed), and then a relink.  This used to be a big deal for large-scale projects where a 20-minute full recompile could be replaced with a few seconds to recompile a file or two that changed and relink.

I have a little about this from the C perspective here:  https://courses.teresco.org/cs330_f20/labs/cessentials/ . I can email you a link to generate a repository of the example code.

**Comment by yakra** [comment]
> You'd still have a single executable. It's all in how it's compiled and linked. However if you have different executables with different parameters compiled in, it would mean any object files that depend on those parameters would also need to be recompiled.

One thing I don't yet understand is how it all looks and works when everything's all compiled and ready to go.
Hope I'm able to articulate this OK. Do we have...
* "a single executable" that refers to, that communicates with, separate `.o` files at runtime?
* `.o` files that are recompiled only when they need to be, and when it comes time to compile the executable, their pre-compiled code is included in that separate executable, saving us some compile time?
* something else?

> From a C programmer's perspective, one advantage to separate compilation of each C file comes in that you're guaranteed only a single version of each function and a single declaration of each global variable (if you have any) which might not happen if C files start to include each other.

No globals. One of the first things I *did* have drilled into my head back in the day was "Globals Bad!" :D
I'm having trouble following here -- "a single version of each function"? Surely if I were to try to define a function a second time, the compiler wouldn't allow that.

> In header files, you'd have only the function prototypes, which can be redefined as much as you want, and any global variable declaration would have `extern` in the header and only be declared "for real" in one C file.

`extern` is also something new to me; read up on it briefly. Sounds like something that'd only come into play if we go the route of compiling into separate (e.g. `.o`) files?

> Another thing that's nice, but not a big thing for a relatively small project like this in the era of fast compile times is that combined with a nice Makefile, any changes to code would only result in recompilation of those files that have changed (or which include .h files that have changed), and then a relink. This used to be a big deal for large-scale projects where a 20-minute full recompile could be replaced with a few seconds to recompile a file or two that changed and relink.

Potentially big enough of a thing. Right now recompiling everything takes about 10s. Just enough to get annoying.

> I have a little about this from the C perspective here: https://courses.teresco.org/cs330_f20/labs/cessentials/ . I can email you a link to generate a repository of the example code.

Thanks for the link. I hope to look at it in more detail before too long. Maybe it'll answer some questions I don't even know I have yet.
At this moment, I wanna make sure I'm not paying attention to too many things at once... :)

**Comment by yakra** [comment]
* [ ] Arguments
* [ ] ClinchedDBValues
* [ ] ConnectedRoute
* [ ] DatacheckEntry
* [ ] DatacheckEntryList *(fold into DatacheckEntry class, static?)*
* [ ] DBFieldLength
* [ ] ElapsedTime
* [x] ErrorList
* [ ] GraphGeneration
* [ ] HighwaySegment
* [ ] HighwaySystem
* [ ] Region
* [ ] Route
* [ ] TravelerList
* [ ] Waypoint
* [ ] WaypointQuadtree

**Comment by jteresco** [comment]
Please don't feel the need to make any reorganization a priority unless you're interested in doing so.  I'd be happy to take a look myself some time soon at how I think it might make sense to organize code with a nice OO design.

**Comment by yakra** [comment]
Interested. This is something I should have learned years ago. It's a good learning exercise/practice. Trying it out on a separate branch that I'm not necessarily worried about merging back in straight away.

>  I'd be happy to take a look myself some time soon at how I think it might make sense to organize code with a nice OO design.

In any case, interested in hearing your thoughts on this.

**Comment by yakra** [comment]
compile times for individual object files
```sh
rm `find . -name \*.o`
clear; for o in `grep ':' Makefile | cut -f1 -d: | grep '\.o'`; do
  echo -en "$o\t"
  ( echo -n "-$(date +%s)+"
    make $o > /dev/null
    date +%s
  ) | bc
done
```

**Comment by yakra** [comment]
Potentially make greater use of static elements in:
* [ ] Arguments
* [ ] ClinchedDBValues
* [ ] ElapsedTime
* [ ] ErrorList

**Comment by yakra** [comment]
Current state of reorganization:
https://github.com/yakra/DataProcessing/tree/CodeOrg or more permanently,
https://github.com/yakra/DataProcessing/tree/e831f413dd5a5dfbdd2231f547298e270dc27ebd

Compare: https://github.com/yakra/DataProcessing/compare/812df06fe8cd5fd6a7d43caae4ed1600c50004cf...e831f413dd5a5dfbdd2231f547298e270dc27ebd

---

One thing you might notice is that the Makefile has gotten huge, one ad-hoc step at a time.
A local uncommitted change tries out a [pattern rule](https://www.gnu.org/software/make/manual/html_node/Pattern-Intro.html#Pattern-Intro)...
```make
%.o : %.cpp %.h
	g++ -std=c++11 -o $@ -c $<
```
...to take the place of several of the simpler rules. Not too big a dent in the overall filesize though.
I'd like to try out automatic [prerequisites](https://www.gnu.org/software/make/manual/html_node/Automatic-Prerequisites.html#Automatic-Prerequisites)/[dependencies](http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/) but it'll take some time & experimentation before I get my head fully wrapped around it.

---

The number of [`#include`s in siteupdate.cpp](https://github.com/yakra/DataProcessing/blob/e831f413dd5a5dfbdd2231f547298e270dc27ebd/siteupdate/cplusplus/siteupdate.cpp#L16-L43) is down considerably. The only `.cpp` file among them is a template function.

---

@jteresco, comments?

**Comment by jteresco** [comment]
Yes, you'll want a wildcard rule to do all of the `g++` commands in your `Makefile`.  Then to get the dependencies on the appropriate `.h` files you can have dependency-only targets for `.o` files.  At least then you don't have to repeat all of those build rules.

I would simplify further by putting all or most of the code into a single directory.  The fact it's broken into separate files is already organizing it, and it makes your `#includes` a lot simpler.

Also, for the `Makefile`, I like to define variables like

<pre>
CXX=g++
CXXFLAGS=-std=c++11 -pthread
</pre>

This would allow (for now) the ability to edit those in one place when switching platforms/compilers.  And later, it can be used with some conditional checks to define compliers and flags automatically based on where `make` is run.

Thanks for all the work on the reorg.

**Comment by yakra** [comment]
> Yes, you'll want a wildcard rule to do all of the `g++` commands in your `Makefile`. 

I assume you're just referring to compiling. There's linking `siteupdate` and `siteupdateST`, and now `g++ -MM` to generate dependencies as outlined in the articles linked above.
There are 3 flavors of dependency-generation & compilation commands:
* multi-threaded objects
* their single-threaded counterparts
* objects common to both builds

> Then to get the dependencies on the appropriate `.h` files you can have dependency-only targets for `.o` files.

AIUI, these dependency-only targets add to the total dependency requirements for the `.o` files. The eventual build recipe is the eventual build recipe.

> At least then you don't have to repeat all of those build rules.

Yup. Slimming down the overall Makefile size, and number & complexity of build rules, was my main goal here. Maintenance of all that could be error-prone.

> I would simplify further by putting all or most of the code into a single directory.  The fact it's broken into separate files is already organizing it, and it makes your `#includes` a lot simpler.

Didn't have the stomach to reorganize all those files and their references in the `#include`s (not necessarily saying the idea's off the table for all eternity...); I wanted to get right on with trying out the new stuff. I just used sed to add the full path to `g++ -MM`'s output.

---

What I'm working with right this moment:
```make
MTObjects = siteupdateMT.o classes/GraphGeneration/HighwayGraphMT.o functions/sql_fileMT.o threads/threads.o
STObjects = siteupdateST.o classes/GraphGeneration/HighwayGraphST.o functions/sql_fileST.o
CommonObjects = \
  classes/Arguments/Arguments.o \
  classes/ClinchedDBValues/ClinchedDBValues.o \
  classes/ConnectedRoute/ConnectedRoute.o \
  classes/DatacheckEntry/DatacheckEntry.o \
  classes/DBFieldLength/DBFieldLength.o \
  classes/ElapsedTime/ElapsedTime.o \
  classes/ErrorList/ErrorList.o \
  classes/GraphGeneration/GraphListEntry.o \
  classes/GraphGeneration/HGEdge.o \
  classes/GraphGeneration/HGVertex.o \
  classes/GraphGeneration/PlaceRadius.o \
  classes/HighwaySegment/HighwaySegment.o \
  classes/HighwaySystem/HighwaySystem.o \
  classes/Region/Region.o \
  classes/Route/Route.o \
  classes/TravelerList/TravelerList.o \
  classes/Waypoint/Waypoint.o \
  classes/Waypoint/canonical_waypoint_name/canonical_waypoint_name.o \
  classes/WaypointQuadtree/WaypointQuadtree.o \
  functions/crawl_hwy_data.o \
  functions/double_quotes.o \
  functions/format_clinched_mi.o \
  functions/lower.o \
  functions/split.o \
  functions/upper.o \
  functions/valid_num_str.o

.PHONY: all clean
all: siteupdate siteupdateST

%MT.d: %.cpp ; g++ -std=c++11 -MM -D threading_enabled $< | sed -r "s~.*:~$*MT.o:~" > $@
%ST.d: %.cpp ; g++ -std=c++11 -MM $< | sed -r "s~.*:~$*ST.o:~" > $@
%.d  : %.cpp ; g++ -std=c++11 -MM $< | sed -r "s~.*:~$*.o:~" > $@

include $(MTObjects:.o=.d)
include $(STObjects:.o=.d)
include $(CommonObjects:.o=.d)

%MT.o: ; g++ -std=c++11 -o $@ -D threading_enabled -c $<
%ST.o: ; g++ -std=c++11 -o $@ -c $<
%.o  : ; g++ -std=c++11 -o $@ -c $<

siteupdate: $(MTObjects) $(CommonObjects)
	g++ -std=c++11 -pthread -o siteupdate $(MTObjects) $(CommonObjects)
siteupdateST: $(STObjects) $(CommonObjects)
	g++ -std=c++11 -o siteupdateST $(STObjects) $(CommonObjects)

clean:
	rm -f $(MTObjects)       $(STObjects)       $(CommonObjects)
	rm -f $(MTObjects:.o=.d) $(STObjects:.o=.d) $(CommonObjects:.o=.d)
```
Some comments:
* The syntax took some getting used to. I expected to be able to use `%` wildcards in commands, but it appears I'm restricted to [Automatic Variables](https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html#Automatic-Variables) there.
* When I added in the `%.o` rule, make seemed to want to interpret `all.o` as a target pattern, even though "`all.o`", `all`+`.o` together as such was not specified anywhere. I've not yet seen how/why this should happen in the GNU make manual, though there's a lot to wade through in there.
  * Specifying `.PHONY: all` made the problem go away.
  * Adding a `SUFFIXES:` line also works.
  * ...But if I also want `clean` to be phony, why not kill 2 birds with 1 stone.
* Ubuntu & CentOS start out with a bunch of `Makefile:40: classes/Waypoint/Waypoint.d: No such file or directory` type messages via `stderr`, then go ahead and compile anyway; noreaster compiles without complaining.
Is this normal? Are there changes I could make to the Makefile itself to prevent it?
---

> Also, for the `Makefile`, I like to define variables like
>
> <pre>
> CXX=g++
> CXXFLAGS=-std=c++11 -pthread
> </pre>

Aah yes, I've started noticing that these variables seem pretty standard. And that they're baked into the [Built-In Rules](https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html#Catalogue-of-Rules).

> This would allow (for now) the ability to edit those in one place when switching platforms/compilers.  And later, it can be used with some conditional checks to define compliers and flags automatically based on where `make` is run.

...For exactly this reason, I'm sure.

So, IIUC we'd get lines like `$(CXX) $(CXXFLAGS) -o $@ -c $<`.

WRT `-pthread`, it's only needed when linking the multi-threaded `siteupdate`. Including it in the command line the rest of the time doesn't cause any harm though. I thought about moving `-pthread` instead into a $(MTFLAGS) variable, along with `-D threading_enabled`. *(We can't assume every compiler will use `-D` to #define... but to that end, we can't assume `-o` & `-c` to be universal either...)* But that's used in compiling and finding dependencies for `%MT.o`; there's nothing really tying the 2 flags together. Seems `-pthread` could be in either variable. Or neither.
If we're already reliant on g++ for reporting dependencies -- reliant on `-c` or `-o` -- seems like it'd do no harm to have `-D` or both specified directly in the command itself. At least, until we get to work on adding options for more platforms/compilers.

It's hard to know what's best practice as a n00b.

**Comment by yakra** [comment]
> Ubuntu & CentOS start out with a bunch of `Makefile:40: classes/Waypoint/Waypoint.d: No such file or directory` type messages via `stderr`, then go ahead and compile anyway; noreaster compiles without complaining.
How is this different from requiring an `.o` file and not finding it, other than that these are single-line target:dependency-only rules?
Is this normal? Are there changes I could make to the Makefile itself to prevent it?

Normal. Make is trying to `include` a file that doesn't exist, and creates it.
Changing `include` to `-include` fixes this.

---

**make clean:**
One thing that annoyed me was that running `make clean` again when already clean would waste a bunch of time creating the `.d` files, only to delete them afterward. This is again due to the `-include`s: While we don't need to create them for the `clean` target, they're needed to complete *the Makefile itself*.

Sure, I could remember when I've made clean, and not make clean again.
But I wanted to see if I could pursue \*ahem\* a cleaner solution.

**solution?**
In theory I can get rid of the `.d` file & `-include` rules completely, and use the `shell` function with a [`.SECONDEXPANSION:`](https://www.gnu.org/software/make/manual/html_node/Secondary-Expansion.html#Secondary-Expansion) to grab my dependencies.

A couple hours of
[![monkeys](https://img.youtube.com/vi/H2uHBhKTSe0/0.jpg)](https://www.youtube.com/watch?v=H2uHBhKTSe0)
and
```make
.SECONDEXPANSION:
%.o  : $$(shell g++ -std=c++11 -MM $$(@D)/$$(*F).cpp | sed -e "s~.*$$(@F).~~" -e "s~ \\\\$$$$~~")
	g++ -std=c++11 -o $@ -c $(@D)/$(*F).cpp
```
seems to work. So far. If I add ` Makefile` to my `.PHONY` targets. :raised_eyebrow: (Huh?)
More testing to do.

It's nicer looking but less efficient, since it generates the info from the `.cpp` file each time, even if the `.o` is up-to-date, as opposed to checking the timestamp on a `.d` file and including it. *How much* less efficient? TBD...

**Comment by yakra** [comment]
The above approach does give us a cleaner Makefile, with fewer rules & fewer overall lines. Also no `.d` files lying around, though I don't find them much of an inconvenience.

The downside is, even when there's nothing to do, no compiling or linking, we still grovel through all the .cpp files to find our dependencies, a process that takes 2-3 s on my laptop or even noreaster, and will only take more time as the amount of code increases.
By contrast, if we have a full set of `.d` files, the `Nothing to be done` determination is pretty much instantaneous.

The best solution is for me to learn to not `make clean` more than once. :)
I'll just go no-build, except for changing `include` to `-include`, and also `@`ing out the `rm` commands in `clean`.

---

[Way up there](https://github.com/TravelMapping/DataProcessing/issues/378#issuecomment-743779730), I wrote:
> * Could there be performance penalties relative to the "one giant [file]" approach used now?

Yes, minuscule ones. Some tasks are faster on some machines, and some slower. Overall, it's the slightest bit (imperceptibly?) faster. Whether faster or even slightly slower, the overall advantages to organization & separate compilation make the new changes worth merging in.

---

Even if not where we might eventually like things to be (there's still no `CXX` or `CXXFLAGS` for example), I'd like to merge in my CodeOrg branch. Code has been reorganized, and the new Makefile allows much faster recompilation & linking.
To continue new development on the current master branch would just invite more merge conflicts.

**Comment by jteresco** [comment]
All done now, I believe.
