### ISSUE TITLE
Some nmpfps.log entries don't show up as [MARKED FP] in nearmisspoints.log

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#38]
http://tm.teresco.org/forum/index.php?topic=335.msg4438#msg4438
http://tm.teresco.org/forum/index.php?topic=335.msg2250#msg2250

**Comment by jteresco** [comment]
I believe this is now solved.  Please open a new issue with specific cases if any further problems are noticed.
