### ISSUE TITLE
No NMP files [bug]

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#387]
I just realized that https://travelmapping.net/logs/nmpbyregion/ does not contain the files anymore.
https://travelmapping.net/logs/nmpbyregion/nmpbyregion.zip does also not exist.

Only https://travelmapping.net/logs/tm-master.nmp is stil in place.

**Comment by jteresco** [comment]
That's just from my experiments running site updates off of a memory filesystem.  I'll add it into my experimental setup in case anyone's looking to use them.  I'll run an extra site update now that should generate them.
