### ISSUE TITLE
active/preview/devel checks

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#391]
One thing the C++ version has always done:
Instead of matching the entire `level` string to `active` / `preview` / `devel`, we can instead just match the first character to `a` / `p` / `d`.
When many of these operations are repeated at the Waypoint level(e.g. `is_or_colocated_with_active_or_preview()`), the savings could add up.

**Comment by yakra** [comment]
task | 496e840ea0dfc919b25840f7b2aeb9c50c20cf3b | 3a5f4086510ffdb962e09a50eb88a5151f97a7ea
-- | -- | --
Augmenting travelers for detected concurrent segments | tbd | tbd
Computing stats | tbd | tbd
Creating per-traveler stats log entries and augmenting data structure | tbd | tbd
Sorting graph index waypoints by name priority | tbd | tbd
Creating unique names and vertices | tbd | tbd
Creating edges | tbd | tbd
Creating area data graphs | tbd | tbd
Performing data checks | tbd | tbd
...systemMileageByRegion | tbd | tbd

**Comment by yakra** [comment]
No noticeable difference. I'll attribute this to string interning, and go no-build.

**Comment by jteresco** [comment]
Looks like Python's string compare is probably really efficient in those cases.  I'm still surprised it's not a little more improvement than that in the cases where it does match and has to check the whole word.

**Comment by yakra** [comment]
quote from https://rushter.com/blog/python-strings-and-memory/
>  Note that every string in Python takes additional 49-80 bytes of memory, where it stores supplementary information, such as **hash**, length, length in bytes, encoding type and string flags.

If we already have hashes, it makes sense to check if they're equal, and potentially save a long comparison.
