### ISSUE TITLE
Graph file recommendations

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#42]
The list of graphs on the web page is big and probably overwhelming.  We should have a list of recommended graphs for various purposes related to HDX/Visualization.

**Comment by yakra** [comment]
> The list of graphs on the web page is big and probably overwhelming

Grin grin -- I haven't even noticed! I just type "graphs" into the Firefox title bar, hit the down arrow a few times till I get a similar match from by browsing history, say, *http://tm.teresco.org/graphs/NY-all.tmg*, and then just edit the URL to get the region I'm looking for. :)

**Comment by jteresco** [comment]
The graph organization was improved significantly in Summer 2017, but we still don't really have a good set of recommendations.  @razieh provided a list a while back that would form a good basis for such a list of recommendations.

**Comment by jteresco** [comment]
Last comment is redundant with #50

**Comment by jteresco** [comment]
This is not really a Data Processing issue.  A related issue over in EduTools: https://github.com/TravelMapping/EduTools/issues/99
