### ISSUE TITLE
crash when Sorting waypoints in Quadtree

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#442]
HighwayData @ 2661ba63dcd717d679c5ce8f6bc8c1f94103c34b
UserData @ cdaaf1365cfb7181792fa906619962143da6ffc5
DataProcessing @ d384d727b750f41d61f19f3216c33f155895d823
```tail
==> sulogs/siteupdate_csv-NEer-3t6p.log <==
[8.82] Sorting waypoints in Quadtree.
```
A little too close for comfort to the old problems [Sorting colocation lists](https://github.com/TravelMapping/DataProcessing/issues/375#issuecomment-764962926).
Did it not actually get fixed? Or is this something a little different?

See also: #441 #405 #375

**Comment by yakra** [comment]
Problem persists with single-threaded sort.
Occurs when sorting points in quadtree node, not colocation lists.

**Comment by yakra** [comment]
There's a bad Waypoint pointer.
This cause can potentially explain all known BSD bugs.

Where's it coming from?

**Comment by yakra** [comment]
# ~The~ Smoking Gun
**Changes from 383f26991c77f292894164ceef56bbea9a4a5988 on noreaster:**
(`cd /home/yakra/TravelMapping/DataProcessing/siteupdate/cplusplus; git diff`)
* Makefile: compile with clang++ instead of g++.
* Force single-threaded quadtree & colocation list sorting, via commenting out some ifdefs.
  * WaypointQuadtree.h
  * WaypointQuadtree.cpp
  * siteupdate.cpp
* Debug text
  * Waypoint::sort_root_at_label: Print `Waypoint*` locations & the values they point to.
  * WaypointQuadtree::insert: Print locations of `Waypoint*`s and `WaypointQuadtree` nodes as insertions are made.
  * WaypointQuadtree::sort(): Print messages before & after `points.sort(sort_root_at_label);` & colocation list sorting.
* To save time, condition out everything after quadtree sorting until the final timestamps.

### Results:
```sh
$ grep -n 1ef93620 logs/siteupdate.log
1716534:Waypoint @ 0x91ef93620 inserted into Quadtree node @ 0x91b4b1580
8295287:                    0x7fffffffca80 points to 0x91ef93620 al.al168@US431
8295295:                    0x7fffffffcbf0 points to 0x91ef93620 al.al168@US431
8295302:sort_root_at_label: 0x7fffffffcd68 points to 0x91ef93620 al.al168@US431
8295304:sort_root_at_label: 0x7fffffffcd68 points to 0x91ef93620 al.al168@US431
8295306:sort_root_at_label: 0x7fffffffcd68 points to 0x91ef93620 al.al168@US431
8295308:sort_root_at_label: 0x7fffffffcd68 points to 0x91ef93620 al.al168@US431
8295359:                    0x7fffffffced0 points to 0x91ef93620 al.al168@US431
8295414:sort_root_at_label: 0x7fffffffd048 points to 0x91ef93620 al.al168@US431
8295455:sort_root_at_label: 0x7fffffffd048 points to 0x1ef93620
```
See how we read the pointer at `0x7fffffffd048`, got the address of `al.al168@US431`, read it again, and the value it stored magically lost 0x900000000.
This is in a single-threaded part of the program, after `points.sort(sort_root_at_label);` has already been called -- `siteupdate` doesn't have any other instructions in flight, and `std::list::sort` is *all* we're doing.

A pointer value decreasing by 0x900000000 is exactly what happened in https://github.com/TravelMapping/DataProcessing/issues/375#issuecomment-764962926.

A compiler bug looks unlikely here.
I see a couple possbilities...
* Bad RAM? This could mean memtest86 and downtime for noreaster... :(
* A rogue pointer from some other software is [writing to stuff it shouldn't](http://www.catb.org/jargon/html/F/fandango-on-core.html). This has its own set of troubleshooting challenges...

@jteresco, thoughts?

**Comment by yakra** [comment]
The Bad RAM Hypothesis is ruled out.
* Installed FreeBSD on lab4 and duplicated the bug.
* `siteupdate -t 1` has run in a loop 929 times & counting without crashing. With >1 thread, it rarely makes it beyond the low double digits.

This latter point is especially infuriating. It suggests the problem *is* in siteupdate.
Right after, per the previous post, the evidence said the problem *is not* in siteupdate, because our pointer is fine and then it's not, when all that's happening is `std::list::sort`.

Grasping at straws here...
Maybe a pointer runs out of bounds in siteupdate, which messes up another process (common to both our FreeBSD systems), which later on returns fire? Sounds unlikely but *whatever's* going on is pretty unlikely...

**What next?**
The next couple crashes observed after the one above happened [when Reading waypoints](https://github.com/TravelMapping/DataProcessing/issues/443). Makes sense to tackle that issue first. Happening first in the chain of events, that could be where some pointer first goes haywire and sets us up for failure later on.

**Comment by yakra** [comment]
The Bad RAM Hypothesis is... Eris having a laugh at my expense.
1. After maybe 50 passes of the next iteration of siteupdate with more debug text, lab4's front panel showed a message about RAM errors in DIMM1 thru DIMM8. Oh boy. I didn't notice when this first appeared, or if it was present around the time of the crash.
2. So I popped the hard disk into lab3 instead.
3. ...And now, that program that crashed right away in a low double-digit # of passes per quasi-expectation is running strong at 182 passes.
    * Either I'm unusually lucky this time thru, or...
    * [ ] I'm gonna try it out on lab4 again...

**Comment by jteresco** [comment]
If you'd like another option for testing, I can get you set up with an account on my home server, also running FreeBSD.  We can arrange that by email if you're interested.  It's an older machine running FreeBSD 11.4, due for an OS upgrade this summer.

**Comment by yakra** [comment]
Probably won't be necessary, but thanks though. I'll take a look at FreeBSD 13.0 soon, and if I decide I want to test out 11.4 as well I'll have a go at that with lab3 or lab4.

**Comment by yakra** [comment]
* [x] Observed crashes with FreeBSD 13.0; didn't investigate them in detail.
* [ ] Will probably also test out 11.4 for giggles.

**Comment by jteresco** [comment]
Helpful to get a FreeBSD VM install on the Siena cloud server?  I should be able to create one you could access by hopping through noreaster.

**Comment by yakra** [comment]
Should be easy enough to do it at home. FreeBSD installation is quick & painless, and I've hard disks to spare, easily swappable.

**Comment by yakra** [comment]
Closing this under the assumption it arises from the same cause as #443.
