### ISSUE TITLE
crash when Reading waypoints

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#443]
HighwayData @ 2661ba63dcd717d679c5ce8f6bc8c1f94103c34b
UserData @ cdaaf1365cfb7181792fa906619962143da6ffc5
DataProcessing @ 5ce722a5f24c5f6a0c88c860f89fa0588b9343a9

Happened during usapr, though that probably doesn't matter much.

* [x] **Yes,** spotted after [Waypoint "defrag"](https://github.com/TravelMapping/DataProcessing/pull/445).

**Comment by yakra** [comment]
**Comment out...**
* [x] Individually commenting out the 15 single-point Datachecks + the HighwaySegment ctor = crashes continue.
* [ ] per-route datachecks
* [ ] malformed_url
* [ ] label_too_long
* [ ] WaypointQuadtree::insert
* [ ] anything else?

**Verbosity**
* [ ] Crashes when reading usaca are very common. Add debug text; see if it hangs on a specific route.

**Comment by yakra** [comment]
## Does BSD clang (LLVM?) have a std::mutex bug?
Here's the code I just ran on noreaster: [tree](f8c262e0dc67b49e7c8df2c8af3ffc2a41e0cd1a) | [diff](https://github.com/yakra/DataProcessing/compare/383f26991c77f292894164ceef56bbea9a4a5988...f8c262e0dc67b49e7c8df2c8af3ffc2a41e0cd1a)
And a snippet from its siteupdate.log:
```
| itass      | ttomr      | mexf       | norfv       |
| itass      | tunrn      | mexf       | norfv       |
| tzat       | tunrn      | mexf       | norfv       |
| tzat       | ugam       | mexf       | norfv       |
| tzat       | usaal      | mexf       | norfv       |
| usaas      | usaal      | mexf       | norfv     ReadWptThread  1 BEG init insert al.al157@CR150      # |0x920cb40a0
| usaca      | usaal      | mexf       | norfv       |
| usaca      | usafl      | mexf       | ReadWptThread norfv0       |
| usaca      | usafl      | mexf       | usanyp      |
| usaca      | usafl      | mexf       | usapr       |
| usaca      | usafl      | usaush     | usapr       |
| vnmct      | usafl      | usaush     | usapr       |
| zafr       | usafl      | usaush     | usapr       |
```
The `ReadWptThread` text should not be interleaved with the system tables on the same line like this. Both readouts are firmly within mutexes:
https://github.com/TravelMapping/DataProcessing/blob/f8c262e0dc67b49e7c8df2c8af3ffc2a41e0cd1a/siteupdate/cplusplus/threads/ReadWptThread.cpp#L18-L27
https://github.com/TravelMapping/DataProcessing/blob/f8c262e0dc67b49e7c8df2c8af3ffc2a41e0cd1a/siteupdate/cplusplus/classes/WaypointQuadtree/WaypointQuadtree.cpp#L6-L7
https://github.com/TravelMapping/DataProcessing/blob/f8c262e0dc67b49e7c8df2c8af3ffc2a41e0cd1a/siteupdate/cplusplus/classes/WaypointQuadtree/WaypointQuadtree.cpp#L57-L64

### What does this mean?
* [ ] **Hypothesis:** We won't see these interleavings when compiling & executing on Ubuntu & CentOS.
* [ ] **Workaround:** Rather than have each ReadWptThread take the next available system to process, avoid a mutex by interleaving HighwaySystem::syslist indices across all threads. Inherently a bit less efficient, with more potential for some cores to sit doing nothing, but hey.
  * [ ] Will it prevent the crashes while *Reading waypoints for all routes*?
  * [ ] There's still potential for crashes with most other threaded tasks unless they're similarly converted.
* [ ] **Single threaded?** [The first big doozy of a BSD bug](https://github.com/TravelMapping/DataProcessing/issues/375#issuecomment-764962926) (which still has some uncomfortable similarities to what I'm seeing now) also affected siteupdateST. [The fix for that](https://github.com/TravelMapping/DataProcessing/commit/d6da5235958e8bf3c525d78d8db9e7105d8f3bb8#diff-9721521117deb219880b84df9ea144d87b74f1decb8ba492bf6f20a8eac159c6) may not have fixed things so much as swept the symptom under the rug for a while.
  * [ ] Will reordering the data in the Waypoint header be sufficient to restore the problem?
  * [ ] ...Or will I have to restore DataProcessing on a wider scale to *(approximately?*) whatever it was at the time?
  * [ ] [siteupdateST still uses has mutexes, even though they don't do anything. Will conditioning them out](https://github.com/TravelMapping/DataProcessing/issues/393) make the problem go away once it's been recreated?

**Comment by yakra** [comment]
**LOL disregard that last post.**
I ran my new code without compiling it first. :P

**Workaround** to iterate thru the systems list without a mutex:
Tried it anyway. No luck. Still crashes.

**Now what?**
Gotta observe what both threads are doing when the crash occurs, without producing an overly huge log file in the process.
This means filtering debug text for the 2 systems I expect to be in progress at the time.
It's usually usaal & usaca, so I'm filtering for that. This last time with the new code,  got usafl & usaca.
Gonna keep going till I get usaal & usaca, and see what I can see.

**Comment by jteresco** [comment]
One of the most frustrating things in my long-ago experiences debugging parallel code is that the fact you put in logging or write files to track down problems can change the timing and cause problems that weren't evident originally as well as mask problems you might have seen previously so they look like they're fixed...until you remove the debug code.

**Comment by yakra** [comment]
Taking 2 different approaches in parallel:
1. Add verbosity to everything that happens during Route::read_wpt, to see what both threads are doing at the time of the crash, and if there's something consistent. This may not be the most helpful if the effects of whatever goes amok aren't immediate.
2. [Keep on deleting code](https://github.com/yakra/TMMinimal) until the crashes stop.

**Comment by yakra** [comment]
> 1. Add verbosity to everything that happens during Route::read_wpt, to see what both threads are doing at the time of the crash, and if there's something consistent. This may not be the most helpful if the effects of whatever goes amok aren't immediate.

I don't see anything consistent. This approach is not helpful.

> 2. [Keep on deleting code](https://github.com/yakra/TMMinimal) until the crashes stop.

Doing this. Still though, need to go down 2 rabbit holes in parallel:
https://github.com/TravelMapping/DataProcessing/issues/443#issuecomment-869009824:
> WaypointQuadtree::insert = crashes continue.

Crashes continue in the DataProcessing variations where I'm adding debug text to the existing code.
In [TMMinimal](https://github.com/yakra/TMMinimal) however, after removing loads of other code, removing WaypointQuadtree::insert stops the crashes.

So there are at least 2 causes of crashes:
1. WaypointQuadtree::insert (what part of it?)
2. Something else, TBD

**Comment by yakra** [comment]
> In [TMMinimal](https://github.com/yakra/TMMinimal) however, after removing loads of other code, removing WaypointQuadtree::insert stops the crashes.

Or not. It could be that it just made them a lot less frequent.
[TMMinimal2](https://github.com/yakra/TMMinimal2) first removes a ton of code, but not as much as [TMMinimal](https://github.com/yakra/TMMinimal). Testing out removing WaypointQuadtree::insert from a range of commits, some ran 430, 1009, 437, 1952 or 2033 times before crashing. [One of them](https://github.com/yakra/TMMinimal2/tree/da37ef) is still going @ 2368, and expected to crash eventually.

> So there are at least 2 causes of crashes:

Could be 2 causes, could be just 1. It may be that our *Something else TBD* throws the ball, and WaypointQuadtree::insert is somehow better able to catch it.

This will take a lot of patience. If i'm not concerned with poring thru siteupdate.log anymore, hopefully >2 threads can bring on the crashes quicker. If I end up needing too many threads, I'll use lab3 rather than noreaster.

*To be continued...*

**Comment by yakra** [comment]
# [Grawlix](https://www.google.com/search?q=grawlix&tbm=isch).
Have I linked to http://www.catb.org/jargon/html/H/heisenbug.html yet? If not, doing so now.

[TMMinimal2@d646f31](https://github.com/yakra/TMMinimal2/tree/d646f31ce2b5ef58a954d6c442baa0e2b0ed5c78) crashed on noreaster, after 2051 passes. That's *good*. I *want* to see that.

And then there's [its child commit](https://github.com/yakra/TMMinimal2/commit/d3170c9a76fd9bfd011c1cd93b0fadb81d2eba89), which cuts out some unused code.
At this point in **TMMinimal2**, no TravelerList objects are ever created. The few non-static members left in the class are just there because they're referenced by some other part of the code *(Route, and... HighwaySegment?)* I'd yet to snip out.
TravelerList is only being kept around for its 2 remaining static members:
* Traverlist::mtx, which has been repurposed as a [terminal mutex](https://github.com/TravelMapping/DataProcessing/issues/443#issuecomment-869205837) for keeping the debug text readable.
* Travelerlist::ids, analogous to `traveler_ids` in siteupdate.py. The list of traveler ids is still populated in main() and takes up some memory, altering however subtly the operating environment once we start reading wpts.

I ran this code, and 3 of its child commits, in a loop via `untilcrash.sh`, approx 5100 times. 4 threads on noreaster, 6 on my BSD 13.0 machine.
So, what's different?
* A few static members of Travelerlist are gone, that took up a whopping 112 B.
* 5 functions are gone, including the TravelerList ctor. Even if they weren't called, these instructions all took up however much memory. *Right?*

It'd appear that getting this stuff out of memory changes where everything else sits in memory afterward, getting it out of the "danger zone". Our pointers there don't get mangled, and we don't *observe* the bug.
This doesn't solve the problem; it only masks the symptom.
I should be able to remove *any number of things* from [TMMinimal2@d646f31](https://github.com/yakra/TMMinimal2/tree/d646f31ce2b5ef58a954d6c442baa0e2b0ed5c78), doesn't particularly matter what, and similarly sweep the problem under the rug.

### This *has to be* a bug in BSD clang.
* Tens of thousands of runs built with ~clang~ G++ on Linux & I've not seen these crashes once.
* Built with clang... Hm. Maybe only about 1000? Time to run `untilcrash.sh` (f8c262e0dc67b49e7c8df2c8af3ffc2a41e0cd1a) on lab1 & lab2 to be absolutely sure...

It'd be nice to be able to submit a bug report to the developers, if I can ever isolate it. Of course, this means a **minimal** version of the program with only what's necessary to observe the crash. No good pointing them toward 7500+ lines of siteupdate and saying [Have fun finding the bug!](https://www.youtube.com/watch?v=AjUmULa0R-8)
I fear that I'll only sweep the problem under the rug before isolating it...

**What next?**
* [ ] Maybe go back to the first [TMMinimal](https://github.com/yakra/TMMinimal) (somewhere around `ac6eaf`) and leave WaypointQuadtree::insert in, making the crashes easier to observe, more frequent. Continue removing code, making sure it still crashes as long as it can.
* [ ] https://github.com/TravelMapping/DataProcessing/issues/442#issuecomment-869202225
    > Will probably also test out 11.4 for giggles.
    
    Have yet to do this. With any luck, the bug was introduced to the compiler between FreeBSD 11.4 & 12.2.

**Comment by yakra** [comment]
https://github.com/TravelMapping/DataProcessing/issues/443#issuecomment-872308126


>> In [TMMinimal](https://github.com/yakra/TMMinimal) however, after removing loads of other code, removing WaypointQuadtree::insert stops the crashes.
>
>Or not. It could be that it just made them a lot less frequent.

A hell of a lot less frequent.

>[TMMinimal2](https://github.com/yakra/TMMinimal2) first removes a ton of code, but not as much as [TMMinimal](https://github.com/yakra/TMMinimal). Testing out removing WaypointQuadtree::insert from a range of commits, some ran 430, 1009, 437, 1952 or 2033 times before crashing. [One of them](https://github.com/yakra/TMMinimal2/tree/da37ef) is still going @ 5007, and expected to crash eventually.

2 minutes after my last post, it finally crashed. After **10056** passes.

>This will take a lot of patience.

And so there's an indication of *just how much* patience...

---

https://github.com/TravelMapping/DataProcessing/issues/443#issuecomment-873219089
> Maybe go back to the first [TMMinimal](https://github.com/yakra/TMMinimal) (somewhere around `ac6eaf`) and leave WaypointQuadtree::insert in, making the crashes easier to observe, more frequent. Continue removing code, making sure it still crashes as long as it can.

For the sake of sanity, expedience, and the ability to observe crashes with any kind of regularity, this looks like a better option than continuing down the TMMinimal2 road.

**Comment by yakra** [comment]
### TMMinimal
Progress has been steady.
Everything after the *Reading waypoints for all routes* loop has been removed except for the *Total run time* text, in order to keep untilcrash.sh working.
Everything before it has been removed, except what's necessary to set it up.
The total line count of all .h + .cpp files is down to 731 from 7505.

### Waypoint class
Unnecessary variables removed from all classes except Waypoint. Changes to `sizeof(Waypoint)` could have big effects on where everything sits in memory, and possibly mask the problem. Best be cautious here.
Incidentally, [`sizeof(Waypoint)` differs between FreeBSD & Ubuntu](https://github.com/yakra/DataProcessing/issues/168#issuecomment-873455154) when compiled with clang (haven't looked at CentOS, and I wanna say g++ is the same on Ubuntu). Padding out the Waypoint structure to 192 bytes = it still crashes, unsurprsingly.

### Now the *real* fun begins...
...hacking away at parts of the loop itself, seeing what crashes and what doesn't.
First thing to go will be the set of all .wpt filenames in hwy_data/ used for tracking unprocessedwpts. I can cut out a good amount of code with minimal impact; early tests indicate I'll still see crashes.

**Comment by yakra** [comment]
* [TMMinimal@bdf9590](https://github.com/yakra/TMMinimal/tree/bdf9590468d2e4aeb1d4e29f00b733aa40096627) crashed, even if it took 13191 passes to do so.
  This means losing `WaypointQuadtree` = we still get crashes.
* [TMMinimal@d18a904](https://github.com/yakra/TMMinimal/tree/d18a9045d041a86c045f45d58439492a63d088b4)
  This means losing *everything but* `WaypointQuadtree` and what's absolutely necessary to keep the `ReadWptThread` loop running = we still get crashes.

This suggests that whatever's happening is during the barebones setup & `ReadWptThread` loop, and that removing `WaypointQuadtree` from `d18a904` (yielding[TMMinimal@9df3607](https://github.com/yakra/TMMinimal/commit/9df3607625a27c863db36518fc41fe40b1f20d20)) would still cause crashes, even if it takes thousands and thousands of passes to observe them.
Just started testing on noreaster:
* siteupdate -t 4
* siteupdate -t 1
* siteupdateST
  * Thinking back to https://github.com/TravelMapping/DataProcessing/issues/375#issuecomment-764962926, remember that even siteupdateST crashed. We're seeing the same... *(is it a cause or a symptom?)* now, of a pointer's value mysteriously decreasing by 0x900000000. Single-threaded crashes could still be a thing, if I'm patient & hang around long enough to observe them.
* Will reverting d6da5235958e8bf3c525d78d8db9e7105d8f3bb8 make crashes more frequent & easier to observe? Maybe, maybe not. **Testing** 2t, 1t & ST.
* Or could `std::list<Waypoint*> *colocated` having been after a bubble of empty space between `unsigned int point_num` and `std::string label` have been a factor? Reverting 383f26991c77f292894164ceef56bbea9a4a5988 & **trying that too**. 2t, 1t & ST.

Now to sit back and wait. For... however long it takes.
If I still see crashes, it might be time to go to https://llvm.org/docs/HowToSubmitABug.html ...
TMMinimal is down to 437 lines; hopefully that's not too much to wade through. :)

---

Still haven't looked at FreeBSD 11.4. Now's a good time...

**Comment by jteresco** [comment]
In my days of more heavy duty parallel programming, we had some high-end tools available to help find memory errors, including TotalView, which appears to remain in existence: https://totalview.io/products/totalview

It doesn't look like there's a FreeBSD version, however.

**Comment by yakra** [comment]
Giving valgrind a go on lab3.

**Comment by yakra** [comment]
OK. Wow. I think I've got it.
I'll post more when I can put a sentence together.
First, sleep.

**Comment by jteresco** [comment]
Good!  Awaiting the big reveal of what you've found out!

**Comment by yakra** [comment]
https://github.com/TravelMapping/DataProcessing/issues/443#issuecomment-869009824
> Crashes when reading usaca are very common. Add debug text; see if it hangs on a specific route.

Oh man. I came so close. It's difficult to identify a specific route via siteupdate.log because we may be a few routes farther along in the process before the crash happens (and I was focusing on what happens at the `Waypoint` level & missing the bigger picture).
I opened ca.ca061pos in the HB. May have even thrown it into [GHex](https://wiki.gnome.org/Apps/Ghex) at one point. Must not have done a text editor though, or I would have seen the [blank line at the beginning of the file](https://github.com/TravelMapping/HighwayData/blob/0d20522305b55ddb2ec026493bb226944f965bc7/hwy_data/CA/usaca/ca.ca061pos.wpt#L1).
There are 2 other offending files -- rou.dk142j, and it was pse.h060 that finally tipped me off.

A .wpt file is first slurped into core as  big-ol' `char` array. And then,
https://github.com/TravelMapping/DataProcessing/blob/b3f2440d24dd49e2fafa02ed080270b4a67e99ec/siteupdate/cplusplus/classes/Route/read_wpt.cpp#L36-L41
Paraphrasing for expository purposes, with `while` instead of `for`:
```C++
// split file into lines				// When 1st line is blank
size_t spn = 0;						// Here's what happens:
char* c = wptdata;					// ----------------------
while (*c)						// *c == '\n'; proceed
{	spn = strcspn(c, "\n\r");			// spn = 0
	while (c[spn] == '\n' || c[spn] == '\r')	// c[0] == '\n'; proceed
	{	c[spn] = 0;
		spn++;					// spn = 1
	}
	lines.emplace_back(c);				// lines[0] = wptdata
	c += spn;					// c = wptdata+1
}
```
The loop repeats starting at `wptdata+1` -- `c` is the start of the first waypoint label, and `lines[1]` becomes `wptdata+1`. SFSG.

The trouble starts when we go to strip whitespace from the end of `lines[0]`:
https://github.com/TravelMapping/DataProcessing/blob/b3f2440d24dd49e2fafa02ed080270b4a67e99ec/siteupdate/cplusplus/classes/Route/read_wpt.cpp#L53

• `lines[1]` is `wptdata+1`.
• Thus `endchar` is `wptdata-1`.
BLAMMO! **A pointer to** one byte **before the beginning of the file** in memory!
Now let's say we have a memory address stored there, like `0x912e2a0e0`.
Let's put these 8 bytes in little-endian order: `e0 a0 e2 12 09 00 00 00`.
Next line, https://github.com/TravelMapping/DataProcessing/blob/b3f2440d24dd49e2fafa02ed080270b4a67e99ec/siteupdate/cplusplus/classes/Route/read_wpt.cpp#L54

The incorrect assumption is that we're in the middle of the file somewhere.
This skips us back past the three `00`s, putting us at the `09`. Which is ascii TAB...
https://github.com/TravelMapping/DataProcessing/blob/b3f2440d24dd49e2fafa02ed080270b4a67e99ec/siteupdate/cplusplus/classes/Route/read_wpt.cpp#L55-L58
**...and gets zeroed out.**
And we proceed back through memory, to potentially do more damage. This explains the couplefew pointer values I saw with a high order `0x920` zeroed out; `0x20` is ascii Space.

---

Now that the problem is finally identified, fixing it will be very easy.
I see a couple ways to do it; just need to decide which is better.

**Comment by yakra** [comment]
So I was like "O HAY, the TravelerList constructor processes lines the same way; that'll need a fix too!"
[Oh look.](https://github.com/TravelMapping/DataProcessing/commit/73ed9a3a6cd2ca61ee96c74a464ce6aa842b78f9#diff-dd7b762a45d86c2a97f155349a22b5708ca404d010a4ec6929cb0160aaacaae2) It already got one a year ago.
If only I'd made the same connection back then... :rofl:

**Comment by jteresco** [comment]
And it look like the Python version doesn't care about a blank line because it breaks the file into lines first, strips off whitespace, and ignores any line that's empty after that.

**Comment by yakra** [comment]
Yup. C++ does the same thing too -- just not 100% successfully till now. :)

* Before:
  https://github.com/TravelMapping/DataProcessing/blob/b3f2440d24dd49e2fafa02ed080270b4a67e99ec/siteupdate/cplusplus/classes/Route/read_wpt.cpp#L59
* After:
  https://github.com/TravelMapping/DataProcessing/blob/e90d92c95b0c843a8e4d1552d5ccc3072d63fd9f/siteupdate/cplusplus/classes/Route/read_wpt.cpp#L54

The relevant part of the diff is [here](https://github.com/TravelMapping/DataProcessing/commit/e90d92c95b0c843a8e4d1552d5ccc3072d63fd9f#diff-2f5473880a30bc31196285e141743f822d5016cab7c4e72fb95946874519f63cL51-R59).

And as for *how* it does the splitting itno lines & stripping whitespace, well...
This kind of madness is the reason some languages don't do pointer arithmetic. :D

**Comment by jteresco** [comment]
I feel like my C class in the fall and my Programming Languages class whenever I can offer that next need to use this bug as a case study for the dangers of a language trusting the programmer too much.

**Comment by yakra** [comment]
It made me start looking into Rust.

Meanwhile, as the results of valgrind are starting to come in, see I'm doing similar stuff elsewhere, even if not with pointers.
https://github.com/TravelMapping/DataProcessing/blob/1e29902c4459ae85f1d5d374820e6ef72db59dbe/siteupdate/cplusplus/siteupdate.cpp#L268-L275

Quote from http://cplusplus.com/reference/string/string/back/
>  This function shall not be called on [empty strings](http://cplusplus.com/string::empty).

Ha. Guess what I'm doing.
I've [fixed stuff like this before](https://github.com/TravelMapping/DataProcessing/pull/403/commits/f6740874af4dfca69372a6c2a7269e45f4fd5463)...
How come I've never seen a crash like in #402 when reading nmpfps.log? It must depend on what's in memory before [line.data()](http://cplusplus.com/reference/string/string/data/)...

**Comment by yakra** [comment]
https://github.com/TravelMapping/DataProcessing/issues/443#issuecomment-874451505
> So I was like "O HAY, the TravelerList constructor processes lines the same way; that'll need a fix too!"
[Oh look.](https://github.com/TravelMapping/DataProcessing/commit/73ed9a3a6cd2ca61ee96c74a464ce6aa842b78f9#diff-dd7b762a45d86c2a97f155349a22b5708ca404d010a4ec6929cb0160aaacaae2) It already got one a year ago.

Still needs a fix, actually.
```C++
char * endchar = lines[l+1]-2; // -2 skips over the 0 inserted while separating listdata into lines
```
can still result in `endchar` being initialized to one byte before the beginning of the file.
