### ISSUE TITLE
Data check if "Abbrev" entry in csv is missing

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#45]
I've made a wrong entry in csv file with [this modification](https://github.com/TravelMapping/HighwayData/commit/9ab5149c5af6139c221f4485e5faee3c9d9f7b87#diff-25628a05b2b7c9ce49774966c3642fd9). "b062asteis" line misses an entry in "Abbrev" column.

hwy_data/_systems/deub.csv:

`deub;DEU;B62;AST;;Siegen;deu.b062ast;`
`deub;DEU;B62;AST;;Eiserfeld;deu.b062asteis;` <=====
`deub;DEU;B62;AST;Fri;Friedewald;deu.b062astfri;`

But there is no error log in http://tm.teresco.org/logs/siteupdate.log or http://tm.teresco.org/logs/highwaydatastats.log.

HB and mapview.php show the route and it's even (correctly) marked clinched if my user name is selected.

However, I get a error in my user log file:
Waypoint label(s) not found in line: DEU B62AST A45 B62

I'll make a pull request to fix the issue but it would be nice to have a data check to avoid future issues like this. Or is the user log file just a bug (I don't think so)?

**Comment by jteresco** [comment]
As far as the specific error log problem, I am guessing it's trying to match either the first or last file with that "list name" and it generates the error.  But maybe it then tries the other and marks it as clinched.

As far as the datacheck, I think I could check for the situation easily enough.  The way I'd likely do it is to flag any non-unique "list name" strings.

**Comment by jteresco** [comment]
I'm running a site update now that will include these as datacheck errors.  Here's the list, BTW:

`ERROR: Duplicate list name: MKD A1
ERROR: Duplicate list name: NOR Rv19
ERROR: Duplicate list name: POL DK12
ERROR: Duplicate list name: NM NM195
ERROR: Duplicate list name: LKA AH43
ERROR: Duplicate list name: CHN-YN G56
ERROR: Duplicate list name: CHN-SC G93
ERROR: Duplicate list name: CHN-GD G94
ERROR: Duplicate list name: DEU B62AST
ERROR: Duplicate list name: ESP NV
ERROR: Duplicate list name: ISL TH807
ERROR: Duplicate list name: VA VA7
ERROR: Duplicate list name: VA VA28
ERROR: Duplicate list name: VA VA168
ERROR: Duplicate list name: VA VA262
`

**Comment by michihdeu** [comment]
Thanks. I've fixed the DEU and ESP error: https://github.com/TravelMapping/HighwayData/pull/1290.

**Comment by ssoworld** [comment]
VA168 is duplicated as a Freeway (possibly the Select state freeways group) and a standard VA route. probably true for the other VA route(s) One is not able to enter the Freeway into the list.

**Comment by jteresco** [comment]
Yes, we need to deal with those VA routes.
