### ISSUE TITLE
Simplifying collapsed graph file names

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#450]
METAL treats the "collapsed" format graphs as the default in nearly all situations at this point.  There is no need for the "-collapsed" to be part of the filenames.  This should not require any significant changes (possibly none) in HDX, but some in the documentation.  The only change needed in the site update code should be to remove the extra text from collapsed-format filenames.

**Comment by yakra** [comment]
Should we, though? It was originally done this way, then "-collapsed" was added in around the time traveled graphs were implemented.

**Comment by jteresco** [comment]
I'm now thinking that wasn't necessary.  One of this summer's goals for HDX has been to remove or simplify anything that could add some confusion.  The vast majority of the users there won't need to know or care about the collapsing of edges to make these graphs.

**Comment by yakra** [comment]
OK, for the benefit of the students, the main users of HDX. :)
#451 closes this.
