### ISSUE TITLE
Split siteupdate.py into multiple files

### ISSUE THREAD

**Issue by wjorda** [TravelMapping/DataProcessing#46]
The current siteupdate.py script has become rather bloated (and thereby difficult to make edits to), with a large number of classes that look like they can easily be split off into separate modules. Is there a particular reason they're all smashed into a single massive script?

**Comment by jteresco** [comment]
Only because as I developed it, I kept it all in one file.  I've considered revisiting to break things out but it hasn't been a priority.

**Comment by jteresco** [comment]
Python site update is going to be retired in favor of C++.  No need to put time into code reorg at this point.
