### ISSUE TITLE
C++ -> production: scripts, documentation, miscellany

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#461]
I polluted up #375 with too many comments, so I'll let that be the issue for the siteupdate program itself, and this one can be for other things to get ready.

* [ ] @michihdeu mentioned [SETUP.md](https://github.com/TravelMapping/DataProcessing/blob/master/SETUP.md) [here](https://github.com/TravelMapping/DataProcessing/pull/459#issuecomment-924251583).

* [ ] [RUNNING.md](https://github.com/TravelMapping/DataProcessing/blob/master/RUNNING.md) too.
  Among other things, this specifically:
  > To run it, you will enter the following at your $ prompt:
  >
  > ```
  > cd ~/DataProcessing/siteupdate/cplusplus
  > git pull
  > sh datacheck.sh
  > ```
  >
  > The `git pull` makes sure you have the latest version of the site update program from the `DataProcessing` repository, and `sh datacheck.sh` does the real work.

  Thoughts on moving the `git pull` step into datacheck.sh itself, so we don't have to do that step manually?

* [x] [C++ flavored datacheck.sh already builds the latest binary.](https://github.com/TravelMapping/DataProcessing/blob/1afe93c7651b2f7d1ea8d6e63a81b9f63abf89a3/siteupdate/cplusplus/datacheck.sh#L43)

* [ ] Switch to multi-threaded `siteupdate` instead of `siteupdateST`?

* [ ] How many threads do we want to limit `siteupdate` to for datacheck.sh?

* [ ] Anything else I'm missing?

**Comment by jteresco** [comment]
This seems like an obsolete Issue.  Agree @yakra and @michihdeu ?
