### ISSUE TITLE
waypoint colocation stats verbosity

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#462]
https://github.com/TravelMapping/DataProcessing/blob/908c5d89e3a65ec259e8da16794fc137a18dce59/siteupdate/python-teresco/read_data.py#L1773

produces a big wall of text at the end of siteupdate. When this feature was introduced on 2015-12-26, there was a lot less HighwayData to report. Checking out [the then-most-recent HighwayData commit](http://github.com/TravelMapping/HighwayData/commit/22ff2e84d11a5c764d642708da0024028139034f), we see:

    10 are each occupied by  8 waypoints.
     6 are each occupied by  9 waypoints.
     2 are each occupied by 10 waypoints.
     0 are each occupied by 11 waypoints.
     0 are each occupied by 12 waypoints.
     8 are each occupied by 13 waypoints.
     0 are each occupied by 14 waypoints.
     1 are each occupied by 15 waypoints.
     1 are each occupied by 16 waypoints.

...for a total of **28** reported locations. But what's with having up to 16 colocated points, when today the max is 11? Turns out there were some placeholder files for yet-undrafted usaca business routes, copies of a random route near Petrograd, artificially inflating the colocation counts.

Fast-forward to 2016-03-28 [when the placeholders were eliminated](https://github.com/TravelMapping/HighwayData/commit/a1170958b5b55bb4be9efd407b162005620094d6) and we get:

    12 are each occupied by  8 waypoints.
     7 are each occupied by  9 waypoints.
     3 are each occupied by 10 waypoints.

...for a total of **22** reported locations.

Today, we have:

    32 are each occupied by  8 waypoints.
    14 are each occupied by  9 waypoints.
     7 are each occupied by 10 waypoints.
     1 are each occupied by 11 waypoints.

...for a total of **54** reported locations. That's a lot more text.

**Proposal:**
Report only locations with 9 or more waypoints.
We'd be back down to 2016 levels, **22** reported locations again.
Thoughts?
@jteresco, what say ye?

**Comment by jteresco** [comment]
No objection.  We can always change it again if a reason comes up.
