### ISSUE TITLE
same number different prefix

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#475]
https://travelmapping.net/hb/showroute.php?r=deuhe.l3308&lat=50.093618&lon=8.998216&zoom=17
https://travelmapping.net/hb/showroute.php?r=tx.tx070&lat=34.012174&lon=-100.828341&zoom=17

**Comment by michihdeu** [comment]
> https://travelmapping.net/hb/showroute.php?r=deuhe.l3308&lat=50.093618&lon=8.998216&zoom=17

Love it 😆

**Comment by yakra** [comment]
Although, shouldn't St3308Kah & St3205 be split into BY & HE segments?
Or else just delete their HE bits?

**Comment by michihdeu** [comment]
> Although, shouldn't St3308Kah & St3205 be split into BY & HE segments? Or else just delete their HE bits?

Nope. It is really very, very short....

**Comment by yakra** [comment]
Not really, different regions are different regions. St3308 looks to have about 20m in HE, about as much as [this last segment](https://travelmapping.net/hb/showroute.php?r=nh.me113cha&lat=44.201084&lon=-71.00583&zoom=19), which has the state line markers on the NE side of the junction. Of course, that's part of a longer chopped route that's going to be in NH anyway.
A few similar cases of a chopped route in a second region from its "home" are shorter than  St3205:
[NY PA44Cer](https://travelmapping.net/hb/showroute.php?r=ny.pa044cer)
[MD WV46Elk](https://travelmapping.net/hb/showroute.php?r=md.wv046elk)
[FRA-CVL D60-27](https://travelmapping.net/hb/showroute.php?r=fracvl.d006027)
Honorable mentions: [DEU-NW L3081](https://travelmapping.net/hb/showroute.php?r=deunw.l3081) is shorter than those 3, though surely the deunwl vs deuhel distinction is at play here.
Barely longer than "DEU-HE St3308" is the project's 4th-shortest route, [DEU-NW L280NiW](https://travelmapping.net/hb/showroute.php?r=deunw.l280niw), though it changes number when it crosses the border. OSM does show it as part of L282, though OSM is often wrong. Wish there was some GMSV to look at. :(
Finally, the 3rd & 2nd-shortest routes are genuine "away from home" cases again, both < 1/2 the length of "DEU-HE St3308":
[GA TN68](https://travelmapping.net/hb/showroute.php?r=ga.tn068)
[TN KY1076](https://travelmapping.net/hb/showroute.php?r=tn.ky1076)

**Comment by michihdeu** [comment]
> Not really, different regions are different regions.

Fair enough! Done.

**Comment by yakra** [comment]
Danke! :)
