### ISSUE TITLE
zero-distance points not merged into one

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#476]
To investgate: 

Why do wy.us026 +02 and wy.089 +05 not get merged into a common point.

**Comment by yakra** [comment]
WY US26's longitude has 7 digits after the decimal point.
WY US89's longitude has 6 digits after the decimal point.

**Comment by jteresco** [comment]
Seems unlikely to be intentional..

**Comment by the-spui-ninja** [comment]
Ah, I think I both forgot to delete the 7th decimal point from OSM data and then didn't highlight all the way to the end on US26 when I copied the concurrency over; fixed

**Comment by the-spui-ninja** [comment]
https://github.com/TravelMapping/HighwayData/pull/5296
