### ISSUE TITLE
Waypoint labels (or label suffix) beginning with lowercase character

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#488]
Just a little challenge for @yakra 

1. Do we have labels starting with lowercase characters?
2. Are they incorrect or do we have FPs?
2. Is it worth a data check?

It sometimes happens to me that I create wpts like rueMar instead of RueMar. Unfortunately, the wpt editor doesn't flag it wrong.

**Comment by yakra** [comment]
1. A quick grep, not an actual datacheck -- some of these are surely from *unprocessedwpts*, like the IDN & JPN examples.
   ```
   BRA-AL/brabr/braal.br101.wpt:usiSer http://www.openstreetmap.org/?lat=-9.909914&lon=-36.333193
   DNK/dnksr/dnk.sr467.wpt:lerVej http://www.openstreetmap.org/?lat=56.269858&lon=8.800435
   FRA-ARA/fraarad01/fraara.d0019d01.wpt:a http://www.openstreetmap.org/?lat=45.653340&lon=5.642026
   FRA-ARA/fraarad38/fraara.d002338.wpt:rouCouJac http://www.openstreetmap.org/?lat=45.567264&lon=5.263696
   FRA-ARA/fraarad74/fraara.d016074.wpt:eND http://www.openstreetmap.org/?lat=45.858321&lon=6.415565
   IDN-NU/idnnun/timor-leste.wpt:https://www.academia.edu/33524542/Minist%C3%A9rio_das_Infraestruturas_R%C3%A9publica_Democr%C3%A1tica_de_Timor-Leste_ROAD_GEOMETRIC_DESIGN_STANDARDS
   JPN/jpntk/jpn.hie5.wpt:jpntk;JPN;HiE;5;;(Hiroshima Expressway) Tobu Route
   MOZ/afrrtr/moz.rtr35.wpt:mam http://www.openstreetmap.org/?lat=-12.367125&lon=40.156059
   MS/usams/ms.ms015dib.wpt:xI-10/110 http://www.openstreetmap.org/?lat=30.453270&lon=-88.896088
   OH/usaoh/oh.oh309.wpt:lawAve http://www.openstreetmap.org/?lat=40.590010&lon=-83.093210
   ROU/roudn/rou.dn061.wpt:toDJ701 http://www.openstreetmap.org/?lat=44.550115&lon=25.489950
   RWA/rwanr/rwa.nr011.wpt:kay http://www.openstreetmap.org/?lat=-1.882250&lon=29.349418
   ```
   Filtered out of this list: 638 additional labels in IND, mostly single-letter or occasionally 2-letter labels, that appear to be placeholders while the systems are in devel & proper labels are still unknown.

2. Nothing jumps out at me as legit and intentional. I don't think we *have* FPs, but that they could be possible.
   * A [couple](https://travelmapping.net/hb/showroute.php?r=nj.atlbricon) [routes](https://travelmapping.net/hb/showroute.php?r=ny.i678) have lettered exits. I suppose some place somewhere sometime could do something similar, using lowercase letters?
   * It's possible some jurisdiction might use a lowercase prefix for a numeric system that gets added in the future.

   Neither of these happen now of course. One possibility is to initially have it as a datacheck_always_error, and then if there ever *are* any FPs, change it to allow marking them. Your thoughts?

3. Sure why not, what do you think? Super easy to implement.

**Comment by michihdeu** [comment]
> Neither of these happen now of course. One possibility is to initially have it as a datacheck_always_error, and then if there ever are any FPs, change it to allow marking them. Your thoughts?

Agree!

> Sure why not, what do you think? Super easy to implement.

Looking forward to get it 😄 Don't forget wpt editor and manual.

I will already fix 5 out of 12 error! (DNK, FRA-ARA and ROU for Lucian)

**Comment by yakra** [comment]
Off-topic now, but looking for routes with single-letter exits, I found:
```
FRA-ARA/fraarad07/fraara.d010407.wpt:C http://www.openstreetmap.org/?lat=44.522819&lon=4.338374
FRA-ARA/fraarad63/fraara.d078863.wpt:S http://www.openstreetmap.org/?lat=45.641667&lon=2.999560
FRA-BFC/frabfcd70/frabfc.d006470mag.wpt:C http://www.openstreetmap.org/?lat=47.870790&lon=6.370155
FRA-BFC/frabfcd90/frabfc.d003990.wpt:C http://www.openstreetmap.org/?lat=47.472083&lon=6.920137
FRA-GES/fragesd10/frages.d006810.wpt:D http://www.openstreetmap.org/?lat=48.417477&lon=3.451638
FRA-GES/fragesd51/frages.d040251.wpt:C http://www.openstreetmap.org/?lat=48.791190&lon=4.534521
FRA-GES/fragesd54/frages.d012554.wpt:C http://www.openstreetmap.org/?lat=49.434270&lon=5.755940
FRA-GES/fragesd55/frages.d012355.wpt:C http://www.openstreetmap.org/?lat=49.232217&lon=5.280199
FRA-GES/fragesd55/frages.d0171c55.wpt:C http://www.openstreetmap.org/?lat=48.867361&lon=5.563374
FRA-GES/fragesd57/frages.d0113e57.wpt:C http://www.openstreetmap.org/?lat=48.956139&lon=6.230270
FRA-GES/fragesd6ae/frages.d00526ae.wpt:C http://www.openstreetmap.org/?lat=47.974864&lon=7.610242
FRA-GES/fragesd6ae/frages.d07006ae.wpt:D http://www.openstreetmap.org/?lat=48.074260&lon=7.295032
FRA-HDF/frahdfd02/frahdf.d000202.wpt:C http://www.openstreetmap.org/?lat=49.161760&lon=3.716166
FRA-HDF/frahdfd02/frahdf.d002102.wpt:C http://www.openstreetmap.org/?lat=49.345337&lon=3.695580
FRA-HDF/frahdfd02/frahdf.d006602.wpt:C http://www.openstreetmap.org/?lat=49.957500&lon=3.606842
FRA-HDF/frahdfd02/frahdf.d009102.wpt:C http://www.openstreetmap.org/?lat=49.402446&lon=3.229119
FRA-HDF/frahdfd02/frahdf.d010402.wpt:C http://www.openstreetmap.org/?lat=49.408069&lon=3.706124
FRA-HDF/frahdfd02/frahdf.d022902.wpt:C http://www.openstreetmap.org/?lat=49.208037&lon=3.416850
FRA-HDF/frahdfd02/frahdf.d027102.wpt:C http://www.openstreetmap.org/?lat=49.397363&lon=3.661408
FRA-HDF/frahdfd02/frahdf.d042302.wpt:C http://www.openstreetmap.org/?lat=49.445466&lon=3.470347
FRA-HDF/frahdfd02/frahdf.d065402.wpt:C http://www.openstreetmap.org/?lat=49.530724&lon=3.516199
FRA-HDF/frahdfd02/frahdf.d068002.wpt:C http://www.openstreetmap.org/?lat=49.417253&lon=3.239583
FRA-HDF/frahdfd02/frahdf.d100302.wpt:C http://www.openstreetmap.org/?lat=49.045667&lon=3.349331
FRA-HDF/frahdfd02/frahdf.d129002vio.wpt:C http://www.openstreetmap.org/?lat=49.289728&lon=3.458671
FRA-HDF/frahdfd02/frahdf.d135102.wpt:C http://www.openstreetmap.org/?lat=49.342698&lon=3.538864
FRA-HDF/frahdfd60/frahdf.d008560.wpt:C http://www.openstreetmap.org/?lat=49.367464&lon=3.029123
FRA-HDF/frahdfd60/frahdf.d008860.wpt:C http://www.openstreetmap.org/?lat=49.216280&lon=2.991014
FRA-HDF/frahdfd60/frahdf.d012160.wpt:C http://www.openstreetmap.org/?lat=49.222515&lon=1.904291
FRA-HDF/frahdfd60/frahdf.d012560.wpt:C http://www.openstreetmap.org/?lat=49.252842&lon=2.153479
FRA-HDF/frahdfd60/frahdf.d015160.wpt:C http://www.openstreetmap.org/?lat=49.609695&lon=2.066106
FRA-HDF/frahdfd60/frahdf.d015560.wpt:C http://www.openstreetmap.org/?lat=49.353420&lon=2.673304
FRA-HDF/frahdfd60/frahdf.d053760.wpt:C http://www.openstreetmap.org/?lat=49.414954&lon=2.329000
FRA-HDF/frahdfd60/frahdf.d060360.wpt:C http://www.openstreetmap.org/?lat=49.178575&lon=2.361352
FRA-HDF/frahdfd60/frahdf.d060960.wpt:C http://www.openstreetmap.org/?lat=49.214973&lon=2.147913
FRA-HDF/frahdfd62/frahdf.d007162.wpt:C http://www.openstreetmap.org/?lat=50.474110&lon=2.231024
FRA-HDF/frahdfd62/frahdf.d013562.wpt:C http://www.openstreetmap.org/?lat=50.320165&lon=1.968811
FRA-NOR/franord61/franor.d075261.wpt:W http://www.openstreetmap.org/?lat=48.738283&lon=0.017960
FRA-NOR/franord61/franor.d078161.wpt:E http://www.openstreetmap.org/?lat=48.781737&lon=-0.172112
FRA-NOR/franord61/franor.d082761.wpt:N http://www.openstreetmap.org/?lat=48.544496&lon=-0.544156
FRA-OCC/fraoccd46/fraocc.d009246.wpt:C http://www.openstreetmap.org/?lat=44.693859&lon=1.966614
FRA-OCC/fraoccd81/fraocc.d009081.wpt:C http://www.openstreetmap.org/?lat=44.043610&lon=2.129733
FRA-PAC/frapacd13/frapac.d009913.wpt:C http://www.openstreetmap.org/?lat=43.789452&lon=4.759993
```

I suppose these might be similar to IND, placeholders used during development?

Back on topic, forgot to mention earlier:
Yes, there'd be 638 errors flagged in India. Although, if [datacheck errors](https://forum.travelmapping.net/index.php?topic=3512.msg26023#msg26023) are being left in place [as a reminder](https://forum.travelmapping.net/index.php?topic=3512.msg26031#msg26031) of what to check on in the future as development continues, then this is a feature not a bug. ;)
And if those are similar placeholders in FRA, if you changed to use lowercase placeholders too, then you'd also get a reminder ;)

> Looking forward to get it :smile: Don't forget wpt editor and manual.

Yup, I consider those part of the process of adding a new datacheck now, though nothing new has been added to wptedit in a while. Thanks for making syserr.php -- now that it's finally created it's easy to keep updated as datachecks are added/changed. :D

**Comment by michihdeu** [comment]
> I suppose these might be similar to IND, placeholders used during development?

C is intended for voie communale which is often just signed with C. I only use Cxx when it is confirmed by GSV because OSM is very often totally wrong. C means, it is really signed as C.

I need to look into the other.....

**Comment by michihdeu** [comment]
> I suppose these might be similar to IND, placeholders used during development?

NEWS were label renaming issues. I put "Dxxx_" into the field and add the NEWS suffixes later by using the renaming feature. I obviously overwrote the numbering by mistake.

Both D cases were likely placeholders.

btw: You didn't catch all single-letter exits 😄 

`FRA-OCC\fraoccd34\fraocc.d000534.wpt	? http://www.openstreetmap.org/?lat=43.515273&lon=3.683220`

**Comment by yakra** [comment]
# [:drum:](http://instantrimshot.com/)
/me greps with a new-n-improved regex, and still doesn't find it due to working with a repo >8 days old. :D

**Comment by michihdeu** [comment]
A123_w or B456_s is also incorrect. I'm not aware of any (correct) suffix beginning with lowercase character. Do we have any @yakra?

**Comment by yakra** [comment]
```FRA-ARA/fraarad63/fraara.d005763.wpt:D205_w
IND-WB/indwb/indwb.wb012a.wpt:mat_e
IND-WB/indwb/indwb.wb012a.wpt:mat_n
PAK/pakn/pak.n005.wpt:N5_new
QC/canqc/qc.qc172.wpt:RueSag_w
```
I don't think this should ever be correct. Allowed:
* _N _S _E _W
* _A _B _C etc.
* city suffixes
* _U _U1 _U2 etc.

**Comment by yakra** [comment]
On the one hand, siteupdate could automatically capitalize these for us.
OTOH, a datacheck helps us find typos like `sMEX/TX` or `xI-10/110`.
