### ISSUE TITLE
Use native code solutions for parsing CSV-like files

### ISSUE THREAD

**Issue by wjorda** [TravelMapping/DataProcessing#49]
As mentioned [here](http://tm.teresco.org/forum/index.php?topic=2052.msg6206#msg6206) (as well as from some profiling tests I ran) parsing various CSV-like files represents the bulk of the processing time spent by the script. We could potentially see large time savings by converting the pure python parsing code to native-implemented parsers such as `pandas.read_csv()` or `numpy.fromfile()`, which both have nearly 50x improvements on parsing speed compared to standard implementations.
[(source)](https://softwarerecs.stackexchange.com/questions/7463/fastest-python-library-to-read-a-csv-file)

I plan on looking into this sometime this summer.

**Comment by jteresco** [comment]
@yakra do you feel like this is relevant for C++ reading of CSVs?  Please feel free to close if not.
