### ISSUE TITLE
Different ConnectedRoutes that can be combined

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#492]
These will not always be flagged by the datachecks proposed in #338.
https://github.com/TravelMapping/DataProcessing/issues/338#issuecomment-1042097123
https://forum.travelmapping.net/index.php?topic=3652.msg19191#msg19191

Examples as of 0df0a8c1d1f5469a7b534ed899108c9101690acb:
[KY/IN: I-265FutLou](https://forum.travelmapping.net/index.php?topic=4823)
[ENG/SCT: B6318 & B6452](https://forum.travelmapping.net/index.php?topic=4824)
[DEU: A270 & B208](https://forum.travelmapping.net/index.php?topic=4825)
[ITA RA5 & RA6](https://forum.travelmapping.net/index.php?topic=2095.msg26969#msg26969)
[ESP: A15](https://forum.travelmapping.net/index.php?topic=4827)
[TKM/UZB: A381](https://forum.travelmapping.net/index.php?topic=4828)

FPs are possible, e.g. AB201.

Probably best to address #338 first, see what hash tables that produces, and get a better idea of how to proceed.

**Comment by yakra** [comment]
I forget my reasoning behind thinking hash tables would be involved. Need to review #338.
That said...
* Is the end of a ConnectedRoute colocated?
* If so, is a colocated point on a different ConnectedRoute in the same HighwaySystem?
* If so, is it `ConnectedRoute::first_point()` or `ConnectedRoute::last_point`? 
  *(These functions don't exist yet, but are what they say on the tin. Piece of cake to implement.)*
* If so, does this ConnectedRoute have the same route + banner?
  *(Will figure out what to do with groupName as I start to implement this & see what results I get.)*
* If so, flag a datacheck error.

...Unless I'm missing something?

**Comment by yakra** [comment]
```sh
grep COMBINE_CON_RTES logs/datacheck.log \
| sed -r 's~^(.+)(;.+;;;COMBINE_CON_RTES;)(.+)(@.*)~[\1](https://travelmapping.net/hb/showroute.php?cr\&r=\1)\2[\3](https://travelmapping.net/hb/showroute.php?cr\&r=\3)\4~'
```
**All 16 results:**
[deuby.b019wur](https://travelmapping.net/hb/showroute.php?cr&r=deuby.b019wur);BY/BW;;;COMBINE_CON_RTES;[deubw.b019](https://travelmapping.net/hb/showroute.php?cr&r=deubw.b019)@BY/BW
[deusn.b093bor](https://travelmapping.net/hb/showroute.php?cr&r=deusn.b093bor);SN/TH;;;COMBINE_CON_RTES;[deuth.b093](https://travelmapping.net/hb/showroute.php?cr&r=deuth.b093)@SN/TH
[frabfc.d005788](https://travelmapping.net/hb/showroute.php?cr&r=frabfc.d005788);BFC/GES;;;COMBINE_CON_RTES;[frages.d005788rup](https://travelmapping.net/hb/showroute.php?cr&r=frages.d005788rup)@BFC/GES
[frabfc.d005788beu](https://travelmapping.net/hb/showroute.php?cr&r=frabfc.d005788beu);BFC/GES;;;COMBINE_CON_RTES;[frages.d005788ram](https://travelmapping.net/hb/showroute.php?cr&r=frages.d005788ram)@BFC/GES
[frabfc.d005788beu](https://travelmapping.net/hb/showroute.php?cr&r=frabfc.d005788beu);GES/BFC;;;COMBINE_CON_RTES;[frages.d005788rup](https://travelmapping.net/hb/showroute.php?cr&r=frages.d005788rup)@GES/BFC
[frages.d003708ren](https://travelmapping.net/hb/showroute.php?cr&r=frages.d003708ren);GES/HDF;;;COMBINE_CON_RTES;[frahdf.d003708](https://travelmapping.net/hb/showroute.php?cr&r=frahdf.d003708)@GES/HDF
[frages.d005788](https://travelmapping.net/hb/showroute.php?cr&r=frages.d005788);GES/BFC;;;COMBINE_CON_RTES;[frabfc.d005788](https://travelmapping.net/hb/showroute.php?cr&r=frabfc.d005788)@GES/BFC
[frages.d005788ram](https://travelmapping.net/hb/showroute.php?cr&r=frages.d005788ram);GES/BFC;;;COMBINE_CON_RTES;[frabfc.d005788cha](https://travelmapping.net/hb/showroute.php?cr&r=frabfc.d005788cha)@GES/BFC
[frages.d098051ant](https://travelmapping.net/hb/showroute.php?cr&r=frages.d098051ant);GES/HDF;;;COMBINE_CON_RTES;[frahdf.d098051vie](https://travelmapping.net/hb/showroute.php?cr&r=frahdf.d098051vie)@GES/HDF
[frages.d098051ver](https://travelmapping.net/hb/showroute.php?cr&r=frages.d098051ver);GES/HDF;;;COMBINE_CON_RTES;[frahdf.d098051](https://travelmapping.net/hb/showroute.php?cr&r=frahdf.d098051)@GES/HDF
[frahdf.d003708](https://travelmapping.net/hb/showroute.php?cr&r=frahdf.d003708);HDF/GES;;;COMBINE_CON_RTES;[frages.d003708sev](https://travelmapping.net/hb/showroute.php?cr&r=frages.d003708sev)@HDF/GES
[frahdf.d098051](https://travelmapping.net/hb/showroute.php?cr&r=frahdf.d098051);HDF/GES;;;COMBINE_CON_RTES;[frages.d098051ant](https://travelmapping.net/hb/showroute.php?cr&r=frages.d098051ant)@HDF/GES
[frahdf.d098051vie](https://travelmapping.net/hb/showroute.php?cr&r=frahdf.d098051vie);HDF/GES;;;COMBINE_CON_RTES;[frages.d098051](https://travelmapping.net/hb/showroute.php?cr&r=frages.d098051)@HDF/GES
[indmh.ka010](https://travelmapping.net/hb/showroute.php?cr&r=indmh.ka010);MH/KA;;;COMBINE_CON_RTES;[indka.ka010](https://travelmapping.net/hb/showroute.php?cr&r=indka.ka010)@MH/KA
[indmh.ka122](https://travelmapping.net/hb/showroute.php?cr&r=indmh.ka122);MH/KA;;;COMBINE_CON_RTES;[indka.ka122](https://travelmapping.net/hb/showroute.php?cr&r=indka.ka122)@MH/KA
[indtg.ka010](https://travelmapping.net/hb/showroute.php?cr&r=indtg.ka010);KA/TG;;;COMBINE_CON_RTES;[indka.ka010](https://travelmapping.net/hb/showroute.php?cr&r=indka.ka010)@KA/TG
@michihdeu, do the ones in your regions all look like legitimate cases that could be combined? Any FPs?

**Comment by michihdeu** [comment]
Fixed. No FP. Thanks @yakra for that great error check 😄

**Comment by michihdeu** [comment]
Will this error check be live soon? I'd like to check that I didn't miss one....

**Comment by yakra** [comment]
@michihdeu, what's your opinion on whether this should be red or blue on the datacheck page?

**Comment by michihdeu** [comment]
It doesn't falsify user stats if they use 4-field entries. Blue. But if 6-field.... hm, red?

**Comment by yakra** [comment]
For 6-field entries, it wouldn't *falsify* anything; it simply wouldn't allow the entry to be made.

**Comment by yakra** [comment]
I'm going with red, simply because that's what no-build in [that part of the code](https://github.com/TravelMapping/Web/blob/d02c25acdde9259253219746b7021efd7b845d84/devel/datacheck.php#L75-L104) gives us.
If later on we decide blue is better, we can do that.

**Comment by michihdeu** [comment]
> For 6-field entries, it wouldn't _falsify_ anything; it simply wouldn't allow the entry to be made.

Then, I prefer having it blue!
