### ISSUE TITLE
only produce stats CSVs for active/preview systems

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#498]
Stats CSVs are produced for all systems, even devel.

Not much useful info in devel systems; take **cannss-all.csv** for example:
```
Traveler,Total,NS
TOTAL,1889.48,1889.48
```
This info is also available from highwaydatastats.log if anyone really needs it.
@jteresco, any objections to nixing stats CSVs for devel systems and only doing active/preview?

**Comment by jteresco** [comment]
No objections.
