### ISSUE TITLE
Compute and store more graph information

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#50]
Other information about the graphs generated for METAL that might be useful to compute and store:

- average/max vertex degree
- number of connected components
- bounding box
- average density (something like vertices per square mile)

**Comment by yakra** [comment]
> number of connected components

this would be interesting to compare before/after doing a large number of NMP fixes

**Comment by jteresco** [comment]
You can already see a preliminary version of the algorithm visualization of the computation of connected components at http://courses.teresco.org/metal/avtest/

Load up the graph you want and choose the connected components algorithm.  It was just implemented last week and there will be fixes and enhancements coming, but it already might be instructive to help find important NMPs or it might just be fun to watch.

**Comment by jteresco** [comment]
This one seems harder: check if each graph is planar.

**Comment by jteresco** [comment]
This is now done as part of the archive graph creation.  We can create new issues for information we might want to add about archived graphs.
