### ISSUE TITLE
DEL

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#514]
.

**Comment by yakra** [comment]
You figured it out; everything makes sense now?

**Comment by jteresco** [comment]
Assuming this means we're good to close.  Feel free to reopen if necessary.

**Comment by yakra** [comment]
Must have been Lisdorf?

**Comment by michihdeu** [comment]
> Must have been Lisdorf?

yep, haven't seen it on the map when planning the trip. I thought that I would have clinched all B roads in SL but also missed a very short section in [Perl](https://travelmapping.net/user/system.php?u=michih&sys=deub&rg=DEU-SL). I'm looking forward torevisit the region :)
