### ISSUE TITLE
Site update: NMP by region page improvements

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#533]
https://forum.travelmapping.net/index.php?topic=3656.msg27805;topicseen#new

Two possibilities:

1. Just don't generate `.nmp` files for regions with no NMPs
2. Don't generate entries on the `index.html` file for 0-byte `.nmp`s.

**Comment by jteresco** [comment]
Haven't looked to see how hard this might be (I don't think it's hard) but we could also list the number of unmarked NMPs, those detected as LI, and those marked as FPs on the `index.html`.

**Comment by yakra** [comment]
@michihdeu [wrote](https://forum.travelmapping.net/index.php?topic=3656.msg27817#msg27817):
> files with just FPs might also be marked. Both would ease maintaining regions.

This is simple enough to do in a bash script, though maybe handling everything in a revamped `nmpbyregion` program may be the way to go. Nmpbyregion itself could write index.html...
* Less code cluttering up 4 [different flavors](https://github.com/TravelMapping/DataProcessing/pull/532) of localupdate.sh
* > Just don't generate .nmp files for regions with no NMPs
* More efficiently gather stats, as @jeteresco [noted](https://github.com/TravelMapping/DataProcessing/issues/533#issuecomment-1140368564). I wouldn't personally find a LI count useful, but that's just me. Anyone else?
* index.html could be ordered by...
  * descending order of unresolved NMP pairs
  * one section for files with unmarked NMPs & another section for files with only FPs, both in alphabetical order
  * something else? Thoughts/preferences?

That program could use a rewrite anyway. For something of its size & simplicity, it's pretty bloated.

**Comment by michihdeu** [comment]
> I wouldn't personally find a LI count useful, but that's just me. Anyone else?

Seconded!

**Comment by jteresco** [comment]
Moving the responsibility into the C++ program makes a lot of sense.

**Comment by yakra** [comment]
I'll remove nmpbyregion.log, as that info is in siteupdate.log now.

**Comment by yakra** [comment]
@jteresco:
`zip -q nmpbyregion.zip *.nmp` -> `zip -q nmpbyregion.zip *.nmp index.html` ?

**Comment by yakra** [comment]
sanity check for .nmp file contents:
```sh
for file in `2>/dev/null curl https://travelmapping.net/logs/nmpbyregion/ | sed -r "s~.*https://travelmapping.net/logs/nmpbyregion/(.+\.nmp)'>file.*~\1~" | tail -n +4 | head -n -1`; do
  local_file=`echo $file | tr -d '\-'`
  remote_data=`2>/dev/null curl https://travelmapping.net/logs/nmpbyregion/$file`
  if [ `echo -n "$remote_data" | wc -c` != 0 ]; then
    delta=`diff $local_file <(echo "$remote_data")`
    if [ `echo -n "$delta" | wc -c` != 0 ]; then echo $file; fi
  fi
done
```

**Comment by jteresco** [comment]
I'm wondering if the zip file is of any use with it being easier to bring the files right up in HDX from this new index page. Even before that, I see only 3 successful downloads of it in the web logs in 2022, none since February.  I say let's drop it.

**Comment by yakra** [comment]
I wonder how many of those 3 were robots.
