### ISSUE TITLE
Allow non-integer radius for area graphs in site update

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#536]
I've updated the Python site update code to allow non-integer values for the area graphs.  Will need the same in C++ if it's not already allowing that.

**Comment by yakra** [comment]
With the Python changes, area graph filenames have changed, e.g. `siena10-area.tmg` -> `siena10.0-area.tmg`.
Do you want to keep the old filenames, without a trailing `.0` for non-integers?
Or shall I change the C++ version to do "Python-style floats"?

**Comment by yakra** [comment]
Is something like `siena10_0-area.tmg` preferable, or is `siena10.0-area.tmg` fine?
TM already has periods before the final extension in .wpt filenames, but might graphs or METAL projects want to play by different rules?

**Comment by jteresco** [comment]
For Python, the ones that are integer values will go back to the integer only in tonight's update.  Only `siena2.5-area.tmg` will retain the extra `.`.

**Comment by yakra** [comment]
Oops, I meant to use a more clear example like that, with something other than `0` after the `.`.
Looks like the `.` is fine per the `siena2.5-area.tmg` example.

**Comment by jteresco** [comment]
Yes, the extra `.` should not be a problem.  Thanks!
