### ISSUE TITLE
C++ site update archive graphs support

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#539]
The Python site update code and its `localupdate.sh` now repopulate the DB with information about archived graph sets.  C++ needs to be updated to match.

**Comment by yakra** [comment]
Also:
CentOS is dead; long live localupdate_centos.sh!

**Comment by jteresco** [comment]
C++ `localupdate.sh` is fixed.  I can easily enough update the centos-specific files but maybe instead I'll tackle #551.
