### ISSUE TITLE
Graph archives: extraneous double quotes around descr field

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#540]
For now, removing manually from the .sql file generated but that's not a good solution.

**Comment by yakra** [comment]
What table & field?

**Comment by jteresco** [comment]
I'm going to see what I can do about this.  The extra quotes are breaking my new graph index code.

**Comment by jteresco** [comment]
> What table & field?

In `GraphArchiveSets`, the ``descr` field.  The problem is in the interaction between

https://github.com/TravelMapping/DataProcessing/blob/f9ba8e06d8461f40bfbb05f67fb4498859a31851/ArchiveGraphs/archive_graphs.sh#L47

and the command-line parameter handling in `archivegraphs.c`.  Should actually be a pretty easy fix and will take care of it soon.
