### ISSUE TITLE
Update documentation for production C++ site update

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#548]
SETUP.md needs a general update, in particular to point to C++.

@yakra @michihdeu what else should be revisited?

**Comment by michihdeu** [comment]
RUNNING.md also needs to be updated: https://github.com/TravelMapping/DataProcessing/blob/master/RUNNING.md#running-the-site-update-code-in-highway-data-check-mode

**Comment by yakra** [comment]
Nothing else I can think of. OK to close?
