### ISSUE TITLE
Efficiency of creating listupdates.txt

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#550]
The site update scripts create a file `listupdates.txt` that is used by the Python and C++ site update programs to get the timestamp of the last commit that modified each list file.  It's a slow process, with a call to `git log` for each list file.

Could this be improved by having a `Makefile` that creates something like a `terescoj.time` file with this info for each list entry, and which would only then need to make the `git log` call when the `.list` file has been updated?

**Comment by yakra** [comment]
siteupdate could then dispense with listupdates.txt entirely, and work directly with the .time files.

**Comment by jteresco** [comment]
Even better!

**Comment by yakra** [comment]
* [x] Makefile is done.
* [x] siteupdate.py is in its final state.
* [ ] C++ functions identically to Python, but is in a "partway there" state -- `update` is a `std::string*` allocated on the heap, and I'd like it to be a `std::string` allocated on the stack.
* [ ] localupdate scripts
