### ISSUE TITLE
datacheck.sh multi-thread usage

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#555]
https://forum.travelmapping.net/index.php?topic=5342.msg30132#msg30132

> datacheck.sh doesn't take any command line arguments other than `nopull`. Jim or I will have to edit datacheck.sh to run siteupdate with the appropriate number of threads.

running.md docu also needs to be updated, please refer to #548

**Comment by yakra** [comment]
I wanna make some other changes to lines of the code that will be affected by this, so it seems a good time to get this done too.
https://github.com/TravelMapping/DataProcessing/blob/12af4dd32fd662c709b3b02d75788f83eda624c9/siteupdate/cplusplus/datacheck.sh#L42-L43

needs to use `make` for Linux systems.
My first thought was to base the make/gmake decision on `uname`, but that looks like a bad idea -- there are potential systems other than `Linux` or `FreeBSD` to account for, some of which may use either `make` or `gmake` for all I know.
@jteresco's solution in siteupdate.sh appears more robust...
```sh
if hash gmake 2>/dev/null; then
    gmake siteupdate
else
    make siteupdate
fi
```

That aside, how many threads should we use for siteupdate in datacheck? 4? 8? 10? Something else (don't recommend more)?

**Comment by michihdeu** [comment]
I'd say, either give users the ability to chose the number of threads via the command, or go with 4 or 8

**Comment by yakra** [comment]
I think siteupdate should be automatically compiled for datacheck, at least. Keep it simple for contributors & ensure they have the latest version.

**Comment by michihdeu** [comment]
I think we can close the issue,  don't we?
