### ISSUE TITLE
Stop generating nmp_merged

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#565]
I don't think anyone uses the files generated in `nmp_merged` by each site update.  We can always generate them on demand if someone wants.  I'd like to make the default in the site update programs to be that these files are not generated.

**Comment by yakra** [comment]
That'd certainly help with run time on BSD & its kin.

**Comment by jteresco** [comment]
If anyone ever does want to generate these, the C++ and Python code can still do so if the `-n` flag is given.  The `siteupdate.sh` script now takes a new flag `--nmpmerged` that can be used to pass along that `-n` flag and the old directory name `nmp_merged`.  This shaves off a few seconds from the site update and reduces the archive space for each update.
