### ISSUE TITLE
Common datacheck for noreaster

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#571]
Instead of everyone who needs it only for datacheck having to clone/build/maintain their own clones of this repository, I will look into installing and maintaining a current version in a common area.

**Comment by yakra** [comment]
This way, if we upgrade to C++14 or C++17, we won't need to worry about walking everyone through `gmake clean` and assorted rigamarole.

**Comment by jteresco** [comment]
This is now live and in production, please open new Issues for any problems this has created for any problem reports or suggestions related to the new datacheck.
