### ISSUE TITLE
List of large "colocations" output by site update

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#597]
I doubt anyone looks at that list very often.  Remove it?  Disable it with a command-line parameter?  Only enable it with a command-line parameter?

**Comment by yakra** [comment]
Disabled by default makes more sense than enabled by default IMO.

From time to time I've thought about...
There's some function in some header or other (I forget which one) that gives us the width of terminal. I've thought about using that to line the points up in neat little rows & columns, but it's never been a high enough priority to go ahead and do it. Just kinda hand-wave it away on a "keep the C++ output looking like the Python version" basis.
The Python equivalent seems to be a no-go; it appears to only work in the Python shell, not when running a script via `python3`.

I guess it wouldn't bother me to see it go, even if I don't get the chance to do that. :) **Anyone else?**

I expect to have get hands in [WaypointQuadtree::final_report](https://github.com/yakra/DataProcessing/blob/80f27243bf26579c53c6c7a215a5aeb22347317a/siteupdate/cplusplus/classes/WaypointQuadtree/WaypointQuadtree.cpp#L251-L277) in the next few days, as the last remaining phase of the big `TMArray` conversion will change Waypoint ownership from the WaypointQuadtree to their respective Routes.
(Locally, siteupdate is already Valgrind clean! :grinning:)
The changes could be as simple as removing the `delete w;` line, or I may end up deleting the function entirely, creating an ordinary WaypointQuadtree destructor, and handling colocation lists as part of Waypoint destruction, similar to what will be done for HighwaySegment concurrency lists.

**Comment by jteresco** [comment]
Thanks.  I'm thinking it can go unless you want to put in a parameter that specifies the threshold above which to report colocations.  Disabled by default.

**Comment by jteresco** [comment]
No comments in favor of keeping these as is now after 4 weeks, so I'm about to commit and push the addition of a command-line parameter `--colocationlimit` that takes an `int` value that can be specified as some positive number if one wants to see all the points with colocation counts at least as large as that number.  The default is 0, and I suspect that the parameter will very rarely be used.

I did not make a conforming change to Python.

**Comment by yakra** [comment]
https://github.com/TravelMapping/DataProcessing/blob/1af229da874b9a5b6fe3c6568e1fdc6fada07d34/siteupdate/cplusplus/classes/Args/Args.cpp#L44

If I run `./siteupdate '' 10` etc., I'll get an occupation report.
This could potentially cause Wacky Hijinks with a shell script that substitutes a blank string for an unused argument. (Not actually looking  to see if this is the case, but I believe some of mine may do this.)
I see three ways around this:
1. Use `"--colocationlimit"` for both arguments to the `ARG` macro.
2. Don't use the macro for this one option.
3. This is what I prefer, be consistent and have both a short and long arg available for this switch.
   A few options here; I don't have a strong preference between them:
   * **Q** as in **Q**uadtree final report
     (IMO it makes sense to reserve lowercase **q** for a potential future **--quiet** mode. A fairly common switch for lots of Unix programs)
   * **W** as in **W**aypointQuadtree::final_report
   * **L** as in Colocation **L**imit

**Comment by jteresco** [comment]
I'll go with `-l`, thanks for catching the potential problem here.

**Comment by jteresco** [comment]
https://github.com/TravelMapping/DataProcessing/commit/1f92c6cc4499d5f0641ad91c505747f1b5d108b8
