### ISSUE TITLE
Remove EXIT0 and EXIT999 datachecks

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#60]
We are moving toward a decision to remove these datachecks, which are left over from CHM's transition from 0 and 999 being used as border points on connected routes.  Removing these would also involve removing all such entries from datacheckfps.csv.

**Comment by jteresco** [comment]
We'll allow a few days, let's say until August 12, for any objections to be raised, before carrying this out.

**Comment by yakra** [comment]
No objections from me.

**Comment by jteresco** [comment]
All done.  No more EXIT0 or EXIT999 datachecks.
