### ISSUE TITLE
Something broken for time stamp in relation to recent changes?

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#601]
https://travelmapping.net/logs/users/michih.log

```
Log file created at: Sun Jul 30 22:27:19 2023
michih.list last updated: 2023-07-28 18:42:11 +0200
Route updated 2023-07-30: DEU-BB B102
Route updated 2023-07-28: ESP-AN AP7
Route updated 2023-07-28: ESP-PV A8
Route updated 2023-07-28: POL DK18
Route updated 2023-07-28: POL A18Zar
```
List file updated on 30th but the log outputs route update entries from 28th. I got the same yesterday when running data check by myself. I'm quite sure that the issue didn't exist 2-3 weeks ago.

**Comment by michihdeu** [comment]
The "last updated" timestamp is incorrect. It's the 2nd to last timestamp.

**Comment by jteresco** [comment]
It's possible this is related to the switch to the common code for highway and railway site updates.  For a short time (covering a few updates on each site) the time files directory that gets created was shared, so it could be updated by both the `list_files` and `rlist_files` entries.  Now, the railway update uses a separate directory for its time files.  I'm thinking I should clear both of those time file directories to make sure they're based on the appropriate .list.

**Comment by michihdeu** [comment]
Could you clear it meanwhile? I submitted my list file again. There are still the update entries from July 28 in the log.

**Comment by jteresco** [comment]
I did, can try again.  Maybe there's something else going on.

**Comment by jteresco** [comment]
I think I cleared the wrong ones.  We'll see if it helps on the next site update.

**Comment by jteresco** [comment]
Running one now.

**Comment by yakra** [comment]
https://travelmapping.net/logs/users/michih.log
> Log file created at: Fri Aug  4 10:33:51 2023
Processed 7498 good lines marking 81831 segments traveled.
Clinched Highway Statistics

No "last updated" timestamp at all now.
Do the .time files not exist?

**Comment by michihdeu** [comment]
I found a log with April update entry: https://travelmapping.net/logs/users/barefoot_driver.log

**Comment by yakra** [comment]
```
Log file created at: Sun Jul 30 22:27:19 2023
michih.list last updated: 2023-07-28 18:42:11 +0200
```
This is what you're looking for -- on the 2nd line of the .log file, it should say when the .list file was updated.

https://travelmapping.net/logs/users/barefoot_driver.log
```
Log file created at: Fri Aug  4 10:33:51 2023
Waypoint label WI13 not found in line: wi wi137 us2 wi13
  Route updated 2023-04-03: WI WI137
```
This refers to when the route was updated. Since #502, this is always done for broken .list entries, whether siteupdate knows when the .list file itself was updated or not.

---

Looks like the .time files are indeed missing:
```
[yakra@noreaster /fast/home/terescoj/travelmapping/UserData/time_files]$ ls -l
total 4
-rw-r--r--  1 terescoj  terescoj  118 Jan  6  2023 Makefile
```

I took a look at siteupdate.sh but don't see anything immediately obviously wrong.

**Comment by jteresco** [comment]
I think the problem is in this line:

https://github.com/TravelMapping/DataProcessing/blob/54fecf1e42a51cae358d12a5bf1f8b2cf4a0e935/siteupdate/siteupdate.sh#L326

Maybe the replacement of the hard-coded `list_files` directory name with `$listdir` isn't expanding properly in this context.

**Comment by yakra** [comment]
`$listdir` inside single quotes

**Comment by michihdeu** [comment]
I don't know if it helps or is just confusing....

I run data check right now:
```
Log file created at: Sat Aug  5 14:18:58 2023
michih.list last updated: 2023-07-23 11:48:25 +0200
Route updated 2023-07-30: DEU-BB B102
Route updated 2023-07-23: DEU-NI B213
Route updated 2023-07-23: DEU-NI B402
Route updated 2023-07-23: DEU-NI L5
Route updated 2023-07-23: DEU-SN A72
Route updated 2023-07-23: DEU-SN B95Rot
Route updated 2023-07-28: ESP-AN AP7
Route updated 2023-07-28: ESP-PV A8
Route updated 2023-08-03: HUN F4
Route updated 2023-07-28: POL DK18
Route updated 2023-07-28: POL A18Zar
Route updated 2023-08-04: TUR O5
Route updated 2023-08-02: TUR O30
Route updated 2023-08-02: TUR O33
Processed 7510 good lines marking 81921 segments traveled.
```

I did **not** update my user repo fork.

**Comment by yakra** [comment]
You still have your old .time files in /home/michih/$wherever. The bug in datacheck is causing them to not be overwritten.
Meanwhile, for production siteupdate.sh, the .time files are deleted and not being created.

---

@jteresco, if you change
```sh
for t in `ls ../$listdir/*.list | sed -r 's~../$listdir/(.*).list~\1.time~'`; do $make -s $t; done
```
to
```sh
for t in `ls ../$listdir/*.list | sed -r "s~../$listdir/(.*).list~\1.time~"`; do $make -s $t; done
```
I think it should be fixed.

**Comment by jteresco** [comment]
Thanks, @yakra, it looks like it's generating the time files with that fix.

**Comment by yakra** [comment]
```
Log file created at: Sun Aug  6 22:08:02 2023
michih.list last updated: 2023-08-06 20:05:28 +0200
Processed 7526 good lines marking 82115 segments traveled.
```

OK to close?

**Comment by michihdeu** [comment]
The files are not updated here: /fast/home/michih/UserData/time_files
What do I need to do?

We have a directory for railway data now: https://github.com/TravelMapping/UserData/tree/master/rtime_files
However, there is none for ski data yet.

**Comment by jteresco** [comment]
> The files are not updated here: /fast/home/michih/UserData/time_files What do I need to do?

Those should be populated during the site update process.  If you don't run a full site update, they won't be generated.

> We have a directory for railway data now: https://github.com/TravelMapping/UserData/tree/master/rtime_files However, there is none for ski data yet.

If and when ski data gets a little more mature, I'll add that directory.

**Comment by michihdeu** [comment]
> Those should be populated during the site update process. If you don't run a full site update, they won't be generated.

I run `/fast/tm/datacheck` which redirects to `siteupdate.sh`

`/fast/tm/DataProcessing/siteupdate` is not up-to-date. `siteupdate.sh` is from 2023-07-30, one commit behind master. Please update it. Thanks.

**Comment by michihdeu** [comment]
Thanks. Now it's really fine. Closing again 😄
