### ISSUE TITLE
Data check for double quotes in systems.csv

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#606]
A `"` in system names [crashes findroute.php](https://github.com/TravelMapping/Web/issues/763). 

@jteresco [wrote](https://github.com/TravelMapping/Web/issues/763#issuecomment-1681420378):
> I'd prefer disallowing double quotes and possibly a hard error if and when that happens.

**Comment by yakra** [comment]
Do we need to check...
* just the one csv field that was affected?
* some but not all?
* all fields?

**Comment by jteresco** [comment]
It would cause problems in any field, but I think it's highly unlikely that someone would put quotes in anything except the Name field.

**Comment by yakra** [comment]
> It would cause problems in any field

Good news, in that case.
It makes the check blindingly simple:
```c++
if (strchr(line.data(), '"'))
  el.add_error("Double quotes in systems.csv line: "+line);
```
