### ISSUE TITLE
__builtin_ctz (count trailing zeros)

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#616]
@jteresco, does this little program compile & run without issue on MacOS?
```c++
#include <iostream>

int main()
{	for (unsigned short n = 1; n; n <<= 1)
	  std::cout << n << " has " << __builtin_ctz(n) << " trailing 0(s).\n";
}
```

**Comment by jteresco** [comment]
No compiler warnings or errors.  Output:

<pre>
1 has 0 trailing 0(s).
2 has 1 trailing 0(s).
4 has 2 trailing 0(s).
8 has 3 trailing 0(s).
16 has 4 trailing 0(s).
32 has 5 trailing 0(s).
64 has 6 trailing 0(s).
128 has 7 trailing 0(s).
256 has 8 trailing 0(s).
512 has 9 trailing 0(s).
1024 has 10 trailing 0(s).
2048 has 11 trailing 0(s).
4096 has 12 trailing 0(s).
8192 has 13 trailing 0(s).
16384 has 14 trailing 0(s).
32768 has 15 trailing 0(s).
</pre>

**Comment by yakra** [comment]
Nice, thanks for checking that out.

Was slightly worried about portability, though... how much should we be, really?
* siteupdate is "officially" built with clang, per the Makefile.
* Intended for use in Unix-like systems.
* ...for which clang will *(should?)* be freely available.

GCC has `__builtin_ctz` too.
C++20 does have [std::countr_zero](https://en.cppreference.com/w/cpp/numeric/countr_zero), though this project still uses C++11.

**Thoughts?**

---

**Use case:** [TMBitset iteration](https://github.com/TravelMapping/DataProcessing/blob/387c99b0c260938c870457bb9793d4f78b09987f/siteupdate/cplusplus/templates/TMBitset.cpp#L61-L6.).
On BiggaTomato @ 4 threads:
* 11% speedup when computing stats.
* 2% speedup during graph generation.
  A little surprising. For each subgraph, we iterate once through a TMBitset of ~400 `TravelerList*`s and that's it.
  In the future, when iterating twice each thru TMBitsets of 882K vertices & 1M+ edges, both with long runs of 0 bits, the time saved could be much more substantial.

**Comment by yakra** [comment]
Upcoming pull request will use `__builtin_ctzl` and `__builtin_clzl`.
Note the `l` t the end of the function names; these versions work with longs rather than ints.
