### ISSUE TITLE
System abbreviation error output

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#621]
>  the errors given when two lines in systems.csv have the same system abbreviation are not very helpful at diagnosing the problem

https://github.com/TravelMapping/RailwayData/pull/140#issue-2257045450 by @neroute2

**Comment by yakra** [comment]
Tried it out for myself and I see what you mean. :grimacing:

The solution is easy enough, just use an `unordered_set` to make sure system codes are unique when reading systems.csv.
Though if I'm doing that, may as well make a `static unordered_map` member of the `HighwaySystem` class, similar to [Region::code_hash](https://github.com/TravelMapping/DataProcessing/blob/fd96ac64ba2eff23600e86df8dcc84e94cb0a916/siteupdate/cplusplus/classes/Region/Region.h#L54). That will help clean up the routines that parse [systemgraphs.csv](https://github.com/TravelMapping/HighwayData/blob/master/graphs/systemgraphs.csv), [multisystem.csv](https://github.com/TravelMapping/HighwayData/blob/master/graphs/multisystem.csv) & [fullcustom.csv](https://github.com/TravelMapping/HighwayData/blob/master/graphs/fullcustom.csv), thus tying in with #614, but I don't expect it to get much use other than that.

Similar stuff we could also do (though is it worth the bother?):
* A similar check for region codes in regions.csv (which doesn't get edited all that much)
* A check for duplicate *full* names. Could be useful if a systems.csv line is copied & pasted, and then not fully edited.

**Comment by yakra** [comment]
Upcoming pull request will check for duplicate system abbreviations and report those, rather than the flood of unhelpful error messages @neroute2 noted.

It will *not* add either of the other checks I considered above.
