### ISSUE TITLE
CUW-region-intonly graph has undefined aspect ratio

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#631]
The entire graph in Curaçao (CUW-region) is a loop made up of a single route, so it has no intersections with other routes.  This leads to the intersection-only graph being just a single vertex with a loop edge.  Nothing bad about that, in fact it's great that we have that example in the dataset.  However, this leads to the aspect ratio of the graph, which is based only on the vertex positions, being undefined (shows up as 'nan').  It should be given a valid aspect ratio, probably 1.0.

**Comment by yakra** [comment]
Or should this take into account `intermediate_points`?
See also #613

**Comment by jteresco** [comment]
I think either way is fine here: compute the aspect ratio to include shaping points and avoid the issue, or just set it to 1 when there's just one point.  The aspect ratio number isn't used by anything I'm aware of at this point, it's just there as a way to help pick graphs of interest or ones that would fit nicely on a screen for a demo, like Delaware if you want something tall and narrow, Jamaica if you want something short and wide.
