### ISSUE TITLE
User names case-sensitive in listfileinfo.csv?

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#637]
[Should user names be case-sensitive or not?](https://github.com/TravelMapping/UserData/pull/11561#issuecomment-2211092323)

Either make the `listfileinfo.csv` column case-insensitive, or update the manual and add a data check (#635).

**Comment by jteresco** [comment]
I think this was already addressed, at least for the manual entry.

For a datacheck, a report of all entries that don't match a list file name can be reported.  That would cover a case mismatch.

**Comment by jteresco** [comment]
Given that the manual is already updated, I'm going to close this as a duplicate of #635
