### ISSUE TITLE
need to use .rtime files

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#646]
Railway mode still uses the `.time` files (built from `.list` files) intended for Highway mode.
I'll do a quick-n-dirty fix in the immediate term, to be followed up with something more cohesive later on.

```sh
for u in `grep -l 'last updated' * | cut -f1 -d.`; do
  diff ~/tm/UserData/time_files/$u.time <(grep 'last updated' $u.log | sed 's~.* last updated: ~~')
done
```

**Comment by yakra** [comment]
@jteresco, the Makefile is set up to create & clean up `.time` files in the `rtime_files` directory.
Shall we go ahead & do that, or use the `.rtime` extension instead?

**Comment by jteresco** [comment]
I don't think extension matters there as long as we're consistent.  The only reason for the switch to `.rlist` for rail user lists is so I can more automatically process user file updates that come in by email.
