### ISSUE TITLE
Idea for new TMG option

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#67]
Idea: have an option to include traveler stats (either a list or a count) on each edge in the graph.  This would allow interesting visualizations using an enhanced version of HDX and open up some interesting possibilities for computations.

**Comment by yakra** [comment]
You're open to the possibility of file format changes, then?

**Comment by jteresco** [comment]
Never noticed the comment here months ago when it was posted.  I would be open to new and enhanced file formats.

**Comment by yakra** [comment]
Collapsed graphs could be tricky:
http://tm.teresco.org/hb/index.php?units=miles&u=terescoj&r=nh.us004
Zoom in on `NH120_N` & `NH120_S`

**Comment by jteresco** [comment]
Good point.  Each segment would have to be all or nothing.

**Comment by yakra** [comment]
Not a big deal, AIUI now. A hidden vertex can become a visible one, as already done with VISIBLE_HIDDEN_COLOC or HIDDEN_JUNCTION cases.

**Comment by jteresco** [comment]
I thought I had something somewhere about this already.  Closing this one to use the new issue for further discussion and hopefully to guide a quick implementation,
