### ISSUE TITLE
Improve duplicate routes/roots checks

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#70]
https://github.com/TravelMapping/DataProcessing/blob/a48aa24acc09fc80050bac396ae4837bb7b3c780/siteupdate/python-teresco/siteupdate.py#L1999

A hash table or other better lookup mechanism can significantly improve the efficiency of the checks that begin here.  It's up to almost a minute with the growth of our highway data.

**Comment by yakra** [comment]
How did you do the markdown for the code snippet above?

**Comment by jteresco** [comment]
Go to the code view of a file, click on the little grey number, and copy that URL and paste it in.  GitHub then makes it look pretty here.

**Comment by yakra** [comment]
Ah! I copied such a URL and pasted into a comment, but I only previewed it rather than post. I guess that I guess that's not enough to work its magic.

**Comment by yakra** [comment]
Strange, this mechanism doesn't seem to work all the time.
https://github.com/TravelMapping/DataProcessing/issues/87#issuecomment-392536307 for example.
You may have seen a notification or email about me responding to that thread; I tried copying & pasting your comment and separating out the URL to its own line. No luck. Tried posting only the URL as a comment. No luck. Weird...

**Comment by jteresco** [comment]
Switched the lists to sets and this part goes from about a minute to about .2 seconds.  Yes, should have made that simple switch years ago.
