### ISSUE TITLE
Graph generation only in regions/systems that have changed

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#79]
With graph generation taking the largest single chunk of time in the site update process, we could consider ways to generate new graphs only in regions/systems that have had data changes since the last graph generation.  TBD is how to tell what's changed and which graphs are affected.

**Comment by yakra** [comment]
* Have the shell script copy the existing HighwayData directory to a "HighwayData.old" (or somesuch) backup, before the git pull
* Run some DIFFs
* ???
* Profit

(Can the **os** (module, library, what do I call it?) do things of this nature?)

**Comment by michihdeu** [comment]
Bash outputs the changed files when executing `git pull`

**Comment by yakra** [comment]
even better!

**Comment by Thing342** [comment]
Makefiles. :P

**Comment by jteresco** [comment]
A Makefile-like system of dependencies and usage of timestamps seems to be the way we'd go.  This is also a pretty low priority at this point but I welcome the discussion and ideas.

**Comment by yakra** [comment]
With the significant speedup of graph generation a little while back, is this still a priority?

**Comment by jteresco** [comment]
I don't think it is.   Marking with a new label "low priority", since some day we might want to think about it.  Automatic generation of graphs on demand from the DB would be a more useful approach now.

**Comment by jteresco** [comment]
Like with #78, I deem this to be less important given a few years of improvements in this process.
