### ISSUE TITLE
Stats csv files

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#8]
To do hopefully soon: create csv files that will be posted with logs that summarize per-user stats to support easy computation of rankings.  These will be suitable for loading into a spreadsheet for sorting or other processing.  The current plan is to include two:

- per user by region
- per user by system

Files are proposed to look something like this

    Traveler,AL,AK, ..., WY
    terescoj,89.2,523.1, ..., 1212.3
    ...
    TOTAL,2322.2,2032.3, ..., 2932.4

one for travels broken down by region, the other by system.  The first line is a header, the last is the total so the raw mileage can easily be converted to a percentage.

This is intended to be a way to more easily access stats until a better web interface is developed (which remains a lower priority for me than several other TM tasks - still hoping someone will step forward to take the lead on that part).

**Comment by jteresco** [comment]
A first version of this is in place.  Post coming in AARoads thread as soon as update completes.

**Comment by jteresco** [comment]
To do: add miles clinched by route/connected route, number of routes traveled/clinched by region/system.

**Comment by michihdeu** [comment]
Where is the first version of the csv file located?

**Comment by jteresco** [comment]
Linked from the same place as the logs:

http://tm.teresco.org/logs/
and
http://tm.teresco.org/devlogs/

**Comment by jteresco** [comment]
I think these csv files are rarely used now that there are better capabilities through the main web interface.  Closing this issue, but please feel free to open new issues or create topics in the forum for requests for more information in csv format.
