### ISSUE TITLE
datacheck.log: header row

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#84]
after `These entries should be in a format ready to paste into datacheckfps.csv.`
and before the first datacheck entry,
a header row such as `Root;Waypoint1;Waypoint2;Waypoint3;Error;Info`
would provide some extra convenience for copy-pasting into a spreadsheet app such as LibreOffice.

**Comment by yakra** [comment]
I'll look into adding this.

**Comment by jteresco** [comment]
Please feel free to remove the "header" printouts I have in there too if it makes it harder to use in your spreadsheet.

**Comment by yakra** [comment]
[I let those stay](https://github.com/TravelMapping/DataProcessing/pull/86/files); no harm in having them.
I just start copying from the 4th line of the file. Wicked easy.
