### ISSUE TITLE
datacheck: phantom VISIBLE_HIDDEN_COLOC errors

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#85]
Running `./siteupdate.py -e | tee logs/siteupdate.log 2>&1 || exit 1` on my local machine, from the `python-teresco` directory.

Repositories downloaded Wednesday 2018-05-23 13:53:15
https://github.com/TravelMapping/DataProcessing/tree/23a22244e34f678479fe02cfd753428969e54f79
https://github.com/TravelMapping/HighwayData/tree/75d717c4575951ea04a7810736b3a145e000d655
https://github.com/TravelMapping/UserData/tree/0715370537810ae809039e077d7930a5f589d90b

On successive passes running *siteupdate*, with no changes to any of the data in any of the three repositories, I get different results in datacheck.log

```DIFF
yakra@BiggaTomato:~/TravelMapping/DataProcessing/siteupdate/python-teresco$ diff datacheck_0_NoChanges_1.log datacheck_0_NoChanges_2.log 
1c1
< Log file created at: 2018-05-23 17:48:06.713635
---
> Log file created at: 2018-05-23 17:57:55.860903
3a4
> geo.ah082;+ABK/GEO;;;VISIBLE_HIDDEN_COLOC;geo.m027@End
4a6
> geo.e97;+ABK/GEO;;;VISIBLE_HIDDEN_COLOC;geo.m027@End
```

Sometimes they're there. Sometimes not. They always appear to be `VISIBLE_HIDDEN_COLOC`s. ~~On some previous passes, there were even 1 or 2 more, other than just these two.~~ <--Actually, I don't think's that's correct... It might just be these two, disappearing & reappearing.

**Comment by yakra** [comment]
Nota bene: I plan on opening a pull request for siteupdate.py in the very near future.

**Comment by jteresco** [comment]
OK, please feel free.  I am not planning on getting my hands in siteupdate.py until I finish the Leaflet stuff for HDX.

**Comment by yakra** [comment]
http://forum.travelmapping.net/index.php?topic=2073
