### ISSUE TITLE
Graph generation: list of systems in the graphs directory instead of hard-coded

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#88]
https://github.com/TravelMapping/DataProcessing/blob/ec1289ae5733676d54e035dd346f04355a39e6a8/siteupdate/python-teresco/siteupdate.py#L3105

This hard-coded list should be replaced with a list of system graphs desired over in the HighwayData/graphs directory.

**Comment by yakra** [comment]
Does this need to be anything more complicated than just a plain, say, **systemgraphs.txt**, reading
```
usai
usaus
cantch
eure
```

**Comment by jteresco** [comment]
That's it.  I wonder if it makes sense to name it as a .csv for consistency with the others in the graphs directory, even though each line would have a single value with no separators.

**Comment by jteresco** [comment]
Yes, let's include a header row, thanks.
