### ISSUE TITLE
Graph generation: label simplification on borders

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#93]
Idea for a new label simplification: allow reversed border labels to match.

`DE491@DE/PA&PA491@PA/DE`

would become

`DE491/PA491@PA/DE`

Could do similar things when states/provinces/countries are mixed rather than matched at a border.

**Comment by yakra** [comment]
`US12@IL/IN&US20@IL/IN&US41@IN/IL&US12@IL/IN&US20@IL/IN&US41@IN/IL`
would become
`US12/US20/US41@IL/IN`

**Comment by yakra** [comment]
HighwayData @ 3405ad2362d9761e95f0e0936fefbe037eadca16
```
yakra@BiggaTomato:~/TravelMapping/yakra/DataProcessing/siteupdate/cplusplus/logs$ cat waypointsimplification.log | grep 'Keep failsafe: ' | grep '.\+@.\+/.\+&.\+@.\+/.\+' | wc -l
1258
```

**Comment by yakra** [comment]
Lol, took longer to write this than it would have to just implement the darn thing!
```sh
labels=`cat waypointsimplification.log | grep 'Keep failsafe: ' | sed 's/Keep failsafe: \(.*\)/\1/' | grep '.*@.*/.*&.*@.*/.*'`
for label in $labels; do
  points=`echo $label | tr '&' ' '`
  count=`echo $points | wc -w`
  CanonicalBoundary=`echo $points | sed 's/.*@\(.*\)$/\1/'`
  matches=0
  routes=""
  for point in $points; do
    route=`echo $point | sed 's/\(.*\)@\(.*\)/\1/'`
    routes=`echo $routes $route`
    boundary=`echo $point | sed 's/\(.*\)@\(.*\)/\2/'`
    foo=`echo $boundary | sed 's!\(.*\)/\(.*\)!\1!'`
    bar=`echo $boundary | sed 's!\(.*\)/\(.*\)!\2!'`
    if [ "$foo/$bar" == $CanonicalBoundary ] || [ "$bar/$foo" == $CanonicalBoundary ]; then
      matches=`expr $matches + 1`
    fi
  done
  if [ $matches == $count ]; then
    echo -en "$count\t$label\t->\t"
    routes=`for route in $routes; do echo $route; done | sort | uniq`
    echo -n $routes | tr ' ' '/'
    echo "@$CanonicalBoundary"
  fi
done
```
Cleans things up rather nicely.
The six examples with the most routes involved, and what they boil down to:

failsafe | shortened
-- | --
E61@SVN/ITA&E70@ITA/SVN&RA14@ITA/SVN&SS58@ITA/SVN&A3@SVN/ITA&E61@SVN/ITA&E70@ITA/SVN | A3/E61/E70/RA14/SS58@ITA/SVN
A1@CHE/FRA&E25@CHE/FRA&E62@FRA/CHE&A41@FRA/CHE&E21@FRA/CHE&E25@CHE/FRA&E62Bou@FRA/CHE | A1/A41/E21/E25/E62/E62Bou@FRA/CHE
AH5@KAZ/KGZ&AH61@KGZ/KAZ&E125@KAZ/KGZ&E40@KGZ/KAZ&AH5@KAZ/KGZ&AH61@KGZ/KAZ&E125@KAZ/KGZ&E40@KGZ/KAZ&EM01@KGZ/KAZ | AH5/AH61/E125/E40/EM01@KGZ/KAZ
AH5Shy@KGZ/KAZ&AH7@KAZ/KGZ&E40Shy@KAZ/KGZ&AH5@KGZ/KAZ&AH7@KAZ/KGZ&E40@KAZ/KGZ&EM01@KAZ/KGZ | AH5/AH5Shy/AH7/E40/E40Shy/EM01@KAZ/KGZ
A2@KAZ/UZB&AH5Shy@KAZ/UZB&AH62@KAZ/UZB&E123@KAZ/UZB&E40Shy@UZB/KAZ&AH5@KAZ/UZB&AH62@KAZ/UZB&E123@KAZ/UZB&E40@UZB/KAZ&M39@KAZ/UZB | A2/AH5/AH5Shy/AH62/E123/E40/E40Shy/M39@KAZ/UZB
AP1@ESP/FRA&AP8@FRA/ESP&E5@FRA/ESP&E70@ESP/FRA&E80@ESP/FRA&A63@ESP/FRA&E5@FRA/ESP&E70@ESP/FRA&E80@ESP/FRA | A63/AP1/AP8/E5/E70/E80@ESP/FRA
I-55@TN/AR&US61@TN/AR&US64@AR/TN&US70@AR/TN&US79@AR/TN&I-55@TN/AR&US61@TN/AR&US64@AR/TN&US70@AR/TN&US79@AR/TN | I-55/US61/US64/US70/US79@AR/TN
