### ISSUE TITLE
tmg2html in localupdate.sh

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#95]
Once the symbolic link to the tmg2html executable is in place, how would I want to include tmg2html in `localupdate.sh`?

Would I want to change:
https://github.com/TravelMapping/DataProcessing/blob/a12a054e7303e7caef606d6e5755479448f55c29/siteupdate/python-teresco/localupdate.sh#L62-L65
to something like this?
```SH
if [ "$graphflag" != "-k" ]; then
    graphs="ls "$datestr/$graphdir"/*.tmg"
    for g in $graphs
    do
        tmg2html $g $g".html"                                        
    done
    mv $tmwebbase/$graphdir $tmpdir/$datestr
    mv $datestr/$graphdir $tmwebbase
fi
```

**Comment by jteresco** [comment]
You can see how I did this for nmpfilter in the latest localupdate.sh .

**Comment by yakra** [comment]
nmpfilter only needs to be run once; it creates .nmp files for all regions.
tmg2html, OTOH, only processes one .tmg file at a time, so it needs to be run from a for loop inside the shell script.

**Comment by jteresco** [comment]
It might be easier to call it from Python as each .tmg file is created.  If this is done every time graphs are generated, links to the .html versions could be added to http://travelmapping.net/graphs/ also.

**Comment by yakra** [comment]
If that could work, then that could work...
You can call/run other programs using the OS module then, I take it?
I'm divided on whether it could be a Good Thing though. Seems it may be better practice to not make siteupdate.py too reliant on a patchwork of other programs that may or may not be there, especially if someone is setting up their first instance of the site.
Two cents.

**Comment by jteresco** [comment]
Yes, there is some benefit in keeping things relatively simple.  One possibility is to have the equivalent functionality (in Python) right in siteupdate.py.  

We can at the least check for existence of the program before trying to execute, like how the nmpfilter in localupdate.sh is protected in

<pre>
if [ -x ../../nmpfilter/nmpfilter ]; then
</pre>

**Comment by jteresco** [comment]
Are we still interested in tmg2html support?

**Comment by yakra** [comment]
Nah. I almost never use it anymore. Can't remember the last time.
