### ISSUE TITLE
Data check for incorrect abbrv in csv

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/DataProcessing#97]
See https://github.com/TravelMapping/HighwayData/pull/2146

I've renamed b87apo to b87 and b87 to b87kra but [forgot "abbrev" change](https://github.com/TravelMapping/HighwayData/pull/2146/commits/75d5ddbe6339f546e99a4cbfebd48e74a822fcd9) only. It was not detected but should be (if possible).

**Comment by yakra** [comment]
The only way I can conceive of to check for this is with a [readable_name() / root mismatch](https://github.com/TravelMapping/DataProcessing/issues/255) check.
Closing this issue & folding the concept into the more general #255.

**Comment by yakra** [comment]
Reopening this because a less ambitious, more manageable & contained solution is just to compare the end of the root to the banner. *Doy.*

**Comment by yakra** [comment]
Everything here and more gets picked up by a fix for #255 (another comment coming there shortly).
If we ignore everything in *espn* flagged over there because of Roman numerals in the designation, we might overlook 3 examples in that this does flag (ping @si404):
```
espan.n004acar;;;;ABBREV_ROOT_MISMATCH;Cap <-> car
espcl.n002;;;;ABBREV_ROOT_MISMATCH;Arc <-> 002
espct.n002a;;;;ABBREV_ROOT_MISMATCH;Igu <-> 02a
```

**Comment by michihdeu** [comment]
> If we ignore everything in espn flagged over there because of Roman numerals in the designation, we might overlook 3 examples in that this does flag (ping @si404)

@yakra what do you expect from @si404?

**Comment by yakra** [comment]
Looks like 640ae48678be88bc437315a1ee21b4bac415f679 takes care of everything I was looking at.

I think I'd still like to keep the issue open for the time being though, just to make sure I have everything I need when I get back around to working on the datacheck.

**Comment by jteresco** [comment]
Still keep open @yakra @michihdeu @si404 ?

**Comment by michihdeu** [comment]
I think nothing has changed, the issue still persists. I don't know how important it is. Do we have mismatches in hwy data right now? How many? What is the result to users, what's broken in the DB at the end of the day? @yakra what do you think?

**Comment by yakra** [comment]
Let's keep this open.

**Comment by michihdeu** [comment]
@yakra is it (simply) possible for you to find out if we have mismatches at all? Just to be able to evaluate the importance.

**Comment by yakra** [comment]
The issue's kind of a special case of #255. The world won't end if anyone does choose to close it. I've linked here from there, so should be able to find this issue and re-read for reference purposes.

**Comment by michihdeu** [comment]
Ok, closing as it is a special case of #255
